"""Sakura collection in real Chromium. In-memory localStorage, not an iOS test."""
from pathlib import Path
from playwright.sync_api import sync_playwright
import json,traceback
R=Path(__file__).resolve().parents[2];O=R/'tests/055';rows=[]
html=(R/'ONIZLEME.html').read_text()
def check(name,truth,detail=''):
 rows.append(dict(name=name,passed=bool(truth),detail=detail));print('PASS' if truth else 'FAIL',name,detail,flush=True)
def setup(b,enabled=False,allowed=False):
 p=b.new_page(viewport={'width':390,'height':844},has_touch=True);p.set_default_timeout(6500)
 p.evaluate("Object.defineProperty(window,'localStorage',{value:{getItem:k=>window.__store?.[k]||null,setItem:(k,v)=>{(window.__store||={})[k]=v},removeItem:k=>delete window.__store[k]}})")
 p.evaluate('(v)=>{window.LUMA_TEST_COINS_ALLOWED=v}',allowed)
 p.set_content(html.replace('LUMA_TEST_COINS_SWITCH = false','LUMA_TEST_COINS_SWITCH = true') if enabled else html)
 p.wait_for_function('ready');return p
with sync_playwright() as w:
 b=w.chromium.launch(executable_path='/usr/bin/chromium',headless=True,args=['--no-sandbox','--enable-unsafe-swiftshader']);p=setup(b);errors=[];p.on('pageerror',lambda e:errors.append(str(e)))
 try:
  check('055 UI build',p.evaluate("LIVING_BUILD==='LUMA-0.5.5-SAKURA-COLLECTION'"))
  check('Fresh wallet unchanged; no test budget or seeded purchases',p.evaluate("wallet()===0&&S.world.purchases.every(x=>x.cost===0)&&!testCoinsLedger(S)"))
  check('30 new catalogue entries',p.evaluate('Object.keys(SAKURA_CATALOG055).length===30'))
  check('24 outdoor and 6 indoor objects',p.evaluate("Object.keys(SAKURA_CATALOG055).filter(k=>!DECOR[k].roomOnly).length===24&&Object.keys(SAKURA_CATALOG055).filter(k=>DECOR[k].roomOnly).length===6"))
  check('Every new model is distinct',p.evaluate('new Set(Object.values(SAKURA_ART055).map(x=>JSON.stringify(x))).size===30'))
  check('No blank model or label fallback',p.evaluate("Object.keys(SAKURA_CATALOG055).every(k=>SAKURA_ART055[k].length>=10&&pixel(k,64).includes('<svg')&&!pixel(k).includes('<text'))"))
  check('Positive integer coin prices',p.evaluate('Object.keys(SAKURA_CATALOG055).every(k=>Number.isSafeInteger(DECOR[k].price)&&DECOR[k].price>0)'))
  check('All prior decorators have models too',p.evaluate('Object.keys(DECOR).every(k=>DECOR_ART054[k])'))
  p.evaluate("()=>{UI.shopTab='decor';route('shop')}")
  p.locator('[data-action=shop-tab][data-tab=sakura055]').click()
  check('Sakura store tab opens all 30 cards',p.locator('.sakura-card055').count()==30)
  check('Sakura tab announces selected state',p.locator('[data-tab=sakura055]').get_attribute('aria-selected')=='true')
  check('No required mode purchase',p.evaluate("!ownsAtmosphere054('sakura')") and p.locator('.sakura-intro055').inner_text().find('tüm temalarda')>=0)
  for key,count in [('water',4),('home',6),('lights',8),('garden',12),('all',30)]:
   p.locator('[data-action=sakura-filter055][data-filter='+key+']').click()
   # Derive correct categories from catalogue; literal expected values catch unnoticed omissions.
   actual=p.locator('.sakura-card055').count();derived=p.evaluate('(k)=>Object.keys(SAKURA_CATALOG055).filter(id=>k===\'all\'||DECOR[id].category===k).length',key)
   check('Filter '+key,actual==derived,f'{actual} entries')
  p.locator('[data-action=sakura-detail055][data-item=jpTorii]').click()
  check('Detail sheet has model, description and price',p.locator('.sakura-preview055 svg').count()==1 and '1.650' in p.locator('.sheet').inner_text())
  p.locator('.sheet [data-action=sakura-buy055]').click()
  check('Insufficient budget does not buy',p.evaluate("!owns('decor','jpTorii')&&wallet()===0"))
  p.evaluate('closeSheet()')
  p.evaluate('()=>{S.living.baseCoins=50000;window.start055=wallet();}')
  p.locator('[data-action=sakura-buy055][data-item=jpTorii]').click();p.wait_for_function("owns('decor','jpTorii')")
  check('Buy debits once without fake study time',p.evaluate("wallet()===start055-1650&&worldSeconds()===0"))
  p.evaluate("buyItem('decor','jpTorii')")
  check('Owned item cannot charge twice',p.evaluate("wallet()===start055-1650&&S.world.purchases.filter(x=>x.item==='jpTorii').length===1"))
  p.locator('[data-action=sakura-place055][data-item=jpTorii]').click();p.wait_for_function("UI.route==='garden'")
  check('Place uses existing edit mode and selection',p.evaluate("UI.gardenEdit&&UI.selectedLiving==='decor:jpTorii'&&!S.living.placement['decor:jpTorii'].room"))
  p.evaluate("()=>{window.beforePos055={...S.living.placement['decor:jpTorii']};}")
  p.evaluate("enhancedAction('living-nudge',{dataset:{direction:'right'}},{})")
  check('Directional arrows still move only selected object',p.evaluate("S.living.placement['decor:jpTorii'].x>beforePos055.x"))
  p.evaluate("()=>{UI.gardenRoom=false;UI.gardenEdit=false;UI.shopTab='sakura055';route('shop');}")
  p.evaluate("()=>{window.persist055=persist;persist=async()=>{throw Error('disk unavailable')};window.beforePurchase055=JSON.stringify(S.world);}")
  err=p.evaluate("buyItem('decor','jpKoiPond').then(()=>null).catch(e=>e.message)")
  check('Failed purchase rolls back',err=='disk unavailable' and p.evaluate('JSON.stringify(S.world)===beforePurchase055'))
  p.evaluate('()=>{persist=window.persist055;}')
  p.evaluate("async()=>{for(const key of Object.keys(SAKURA_CATALOG055))await buyItem('decor',key);}")
  check('Can own complete collection',p.evaluate("Object.keys(SAKURA_CATALOG055).every(k=>owns('decor',k))"))
  p.evaluate('()=>{window.preNorm055=JSON.stringify(S.world.purchases);S=normalize(JSON.parse(JSON.stringify(S)));}')
  check('New ownership survives normalized reload',p.evaluate('JSON.stringify(S.world.purchases)===preNorm055'))
  p.evaluate("enhancedAction('sakura-place055',{dataset:{item:'jpKotatsu'}},{})")
  check('Indoor purchase placed in cabin',p.evaluate("UI.gardenRoom&&S.living.placement['decor:jpKotatsu'].room===true"))
  p.evaluate("()=>{window.beforeBalance055=wallet();window.beforePlots055=JSON.stringify(S.world.plots);UI.shopTab='sakura055';route('shop');}")
  p.evaluate("enhancedAction('sakura-place055',{dataset:{item:'jpKoiPond'}},{})")
  check('Outdoor place exits room mode',p.evaluate("!UI.gardenRoom&&!S.living.placement['decor:jpKoiPond'].room"))
  check('Placing owned objects is free and does not alter seeds',p.evaluate('wallet()===beforeBalance055&&JSON.stringify(S.world.plots)===beforePlots055'))
  p.evaluate("()=>{UI.gardenEdit=false;S.preferences.motion=true;applyTheme();render();}")
  p.wait_for_timeout(200)
  # Test on actual canvas pointer handling; coordinates derived from current rendered hit rect.
  hit=p.evaluate("()=>{const g=[...gardenInstances].find(x=>!x.passive),h=g.hits.find(x=>x.item==='jpKoiPond'),r=g.canvas.getBoundingClientRect(),f=g.fit;window.g055=g;return {x:r.left+f.ox+(h.x+h.w/2)*f.scale,y:r.top+f.oy+(h.y+h.h/2)*f.scale};}")
  p.mouse.click(hit['x'],hit['y'])
  check('Koi touch triggers bounded visual interaction',p.evaluate("!!g055.sakuraTap055?.jpKoiPond"))
  # Snapshot just the new models, not the rest of the garden's independent effects.
  samples=p.evaluate("()=>{const g=g055;window.sample055=(k,t)=>{const old=g.ctx,c=document.createElement('canvas');c.width=c.height=128;g.ctx=c.getContext('2d');g.art054(k,64,112,100,t);g.ctx=old;return c.toDataURL();};return ['jpKoiPond','jpFrogPond','jpBambooFountain','jpWindChime'].map(k=>({k,changes:sample055(k,1)!==sample055(k,7)}));}")
  for q in samples:check('Animated model '+q['k'],q['changes'])
  p.evaluate("document.body.classList.add('no-motion')")
  still=p.evaluate("()=>['jpKoiPond','jpFrogPond','jpBambooFountain','jpWindChime'].map(k=>({k,still:sample055(k,1)===sample055(k,7)}))")
  check('Reduced-motion rendering deterministic',all(x['still'] for x in still))
  p.evaluate("document.body.classList.remove('no-motion')")
  view=p.evaluate("()=>{const g=g055;g.zoom=1;g.pan={x:0,y:0};g.paint(1000);const r=g.canvas.getBoundingClientRect();return {x:r.left+r.width/2,y:r.top+r.height*.3};}")
  p.mouse.move(view['x'],view['y']);p.mouse.down();p.mouse.move(view['x']+60,view['y']+45,steps=5);p.mouse.up()
  check('Normal drag does not pan garden',p.evaluate('g055.pan.x===0&&g055.pan.y===0'))
  p.evaluate('g055.setZoom(1.65)');check('Zoom remains enabled',p.evaluate('g055.zoom===1.65'))
  p.evaluate("enhancedAction('garden-reset-view',{dataset:{}},{})")
  check('Reset zoom fits garden',p.evaluate('g055.zoom===1'))
  for width in [320,375,390,430,768]:
   p.set_viewport_size({'width':width,'height':844});p.evaluate("()=>{UI.shopTab='sakura055';UI.sakuraFilter055='all';route('shop')}")
   check('No page overflow at '+str(width),p.evaluate('document.documentElement.scrollWidth<=innerWidth+1'))
   check('Buy buttons retain touch target '+str(width),p.evaluate("[...document.querySelectorAll('.sakura-card055 .shop-buy')].every(x=>x.getBoundingClientRect().height>=39)"))
  check('No unhandled UI errors',not errors,'; '.join(errors));p.close()
  # Existing dev-wallet plus the new catalogue. Emulates native dev flag; not the native gate itself.
  d=setup(b,enabled=True,allowed=True)
  check('Explicit development test wallet still grants 100m',d.evaluate('TEST_COINS_ACTIVE&&wallet()===100000000'))
  d.evaluate("()=>{S.living.baseCoins=400;window.notebook055=JSON.stringify(S.notes);}")
  d.evaluate("buyItem('decor','jpKoiPond')")
  check('New shop uses test wallet before real coins',d.evaluate('testCoinsBreakdown().test===99997600&&testCoinsBreakdown().real===400'))
  d.evaluate("()=>{S=normalize(JSON.parse(JSON.stringify(S)));S=normalize(JSON.parse(JSON.stringify(S)));}")
  check('Reload does not refill spent test budget',d.evaluate('testCoinsBreakdown().test===99997600'))
  d.evaluate("()=>{window.paidState055=structuredClone(S);S.world.purchases.push({id:'real-old',type:'decor',item:'bench',cost:85});S.preferences[TEST_COINS_KEY].originalPurchaseIds.push('real-old');window.raw055=structuredClone(S);}")
  raw=d.evaluate('raw055');d.close()
  prod=setup(b,enabled=True,allowed=False)
  check('Native gate absent defaults OFF even when switch ON',prod.evaluate('!TEST_COINS_ACTIVE&&wallet()===0'))
  prod.evaluate('(raw)=>{S=normalize(raw);}',raw)
  check('Production cleanup removes test-bought new decorations',prod.evaluate("!owns('decor','jpKoiPond')&&!testCoinsLedger(S)"))
  check('Production cleanup preserves pretest owned objects and real balance',prod.evaluate("owns('decor','bench')&&wallet()===315"))
  check('Cleanup preserves notes and working time',prod.evaluate('S.notes.length>0&&worldSeconds()===0'))
  prod.close()
 except Exception as e:
  traceback.print_exc();check('Unhandled test exception',False,str(e))
 finally:
  b.close();(O/'collection-results.json').write_text(json.dumps(rows,ensure_ascii=False,indent=2));print('RESULT',sum(x['passed'] for x in rows),'/',len(rows))
  if any(not x['passed'] for x in rows):raise SystemExit(1)
