"""Real Chromium, memory localStorage adapter. Native APIs/PDF vendors are not emulated as device tests."""
import json,time,traceback
from pathlib import Path
from playwright.sync_api import sync_playwright
ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'tests'; OUT.mkdir(exist_ok=True)
results=[]; errors=[]
def check(name,ok,detail=''):
 results.append({'name':name,'pass':bool(ok),'detail':str(detail)[:600]})
 print(('PASS ' if ok else 'FAIL ')+name, str(detail)[:180],flush=True)
with sync_playwright() as p:
 b=p.chromium.launch(executable_path='/usr/bin/chromium',headless=True,args=['--no-sandbox'])
 page=b.new_page(viewport={'width':390,'height':844},device_scale_factor=1)
 page.on('pageerror',lambda e:errors.append(str(e)))
 page.evaluate("Object.defineProperty(window,'localStorage',{value:{getItem:k=>window.__store?.[k]||null,setItem:(k,v)=>{(window.__store||={})[k]=v},removeItem:k=>delete window.__store[k]}})")
 page.set_content((ROOT/'ONIZLEME.html').read_text(),wait_until='load');page.wait_for_timeout(750)
 def ev(s):return page.evaluate(s)
 def ck(name,js):
  try:check(name,ev(js))
  except Exception as e:check(name,False,e)
 def reset():
  ev("closeSheet();S=fresh();S.preferences.finishSound=false;S.preferences.soundWithFocus=false;UI.editorId=null;UI.immersive=false;UI.gardenFull=false;UI.gardenEdit=false;UI.groundBrush=null;UI.query='';UI.category='Tümü';UI.trash=false;UI.archived=false;route('home');")
 try:
  ck('Initial schema 3',"S.schema===3")
  ck('Fresh installs have no invented coin balance',"wallet()===0")
  ck('Nine themes including personal garden',"!!themes.garden && !themes.sakura && Object.keys(themes).length>=9")
  ck('Ten available seeds',"Object.keys(SEEDS).length===10")
  ck('Seven study choices including custom',"Object.keys(STUDY_METHODS).length===7")
  ck('Original strawberry and pumpkin sprites',"spriteGrid('berry')!==null && spriteGrid('pumpkin')!==null")
  ck('Paper normalization rejects unknown kind',"normalizePaper({kind:'evil',opacity:3}).kind==='dark' && normalizePaper({opacity:3}).opacity===1")
  ck('Ink normalization rejects invalid points',"normalizeInk([{points:[[.1,.2],[NaN,.3]],color:'url(x)'}])[0].points.length===1")
  ck('Future schema fails rather than replacing state',"(()=>{try{normalize({schema:99});return false}catch{return S.schema===3}})()")
  ck('Migration preserves historical balance',"(()=>{const old=fresh04();old.world.credits={old:6000};old.world.purchases=[{id:'p',type:'pet',item:'cat',cost:40,at:new Date().toISOString()}];old.focusHistory=[{id:'old',completedSeconds:6000,completedMinutes:100,plannedMinutes:100,completed:true,phase:'focus',endedAt:new Date().toISOString()}];S=normalize(old);return wallet()===60&&S.living.baseCoins===100})()")
  ck('New seconds use 3/min without retroactive multiplier',"(()=>{S.world.credits.new=60;return wallet()===63})()")
  ck('Schema 3 reload keeps same balance',"(()=>{const before=wallet();S=normalize(JSON.parse(JSON.stringify(S)));return wallet()===before})()")
  reset();ev("route('garden')");page.wait_for_timeout(200)
  ck('Garden canvas mounted',"gardenInstances.size===1 && !!$('.living-canvas')")
  ck('Default world has scenery hit targets and three pots',"(()=>{const g=[...gardenInstances][0];g.paint(performance.now());return g.hits.filter(h=>h.kind==='pot').length===3&&g.hits.some(h=>h.kind==='cabin')&&g.hits.some(h=>h.kind==='pond')})()")
  ck('Garden zoom controls installed',"$$('[data-action=\"garden-zoom\"]').length===2")
  ev("enhancedAction('garden-full',{dataset:{}},{})");page.wait_for_timeout(100)
  ck('Garden fullscreen hides navigation',"UI.gardenFull && $('#navigation').classList.contains('hidden') && $('.garden-full')!==null")
  ck('Garden fullscreen canvas fits viewport',"$('.garden-stage').getBoundingClientRect().height>600")
  ev("enhancedAction('garden-zoom',{dataset:{delta:.3}},{})")
  ck('Explicit zoom increments scale',"[...gardenInstances].some(g=>g.zoom>1)")
  ev("enhancedAction('garden-full',{dataset:{}},{})")
  ck('Exit full garden restores normal layout',"!UI.gardenFull && !$('#navigation').classList.contains('hidden')")
  ev("S.living.time='day';S.living.weather='rain';render()")
  ck('Rain and time choice persisted in state',"gardenWeather()==='rain'&&gardenTime()==='day'")
  ck('Garden weather independent of audio',"S.preferences.volumes.rain>=0&&!S.preferences.soundPlaying")
  ck('Rendering does not leak canvas instances',"(()=>{for(let i=0;i<6;i++)render();return gardenInstances.size===1})()")
  ev("plantSeed(0,'daisy')")
  ck('Plant seed occupies only selected pot',"S.world.plots[0]?.kind==='daisy' && S.world.plots[1]===null")
  ck('Immature plant cannot be transplanted',"(async()=>{await harvestPlant(0);return S.world.plots[0]!==null&&S.world.harvested.length===0})()")
  ck('Manual watering gives no time or coins',"(async()=>{const before=wallet(),seconds=worldSeconds();await enhancedAction('living-water',{dataset:{slot:0}},{});return wallet()===before&&worldSeconds()===seconds})()")
  ck('New growth stage queues watering',"(()=>{S.world.credits.testgrowth=720;queueGrowth();return S.living.watering[S.world.plots[0].id]>0&&S.living.growthSeen[S.world.plots[0].id]>=1})()")
  ck('Mature plant moves into garden and frees pot',"(async()=>{S.world.credits.testgrowth=2100;const id=S.world.plots[0].id;await harvestPlant(0);return S.world.plots[0]===null&&S.world.harvested.some(x=>x.id===id)&&S.world.layout.some(x=>x.type==='plant'&&x.item===id)&&S.living.album.includes('daisy')})()")
  ck('Harvest is idempotent',"(async()=>{const n=S.world.harvested.length;await harvestPlant(0);return S.world.harvested.length===n})()")
  ck('Duplicate animal purchase not charged twice',"(async()=>{await buyItem('pet','cat');const coins=wallet();await buyItem('pet','cat');return owns('pet','cat')&&wallet()===coins})()")
  ck('Insufficient coins never create purchase',"(async()=>{const old=JSON.stringify(S.world.purchases);const k=Object.keys(PETS).find(k=>PETS[k].price>wallet());if(!k)return false;await buyItem('pet',k);return JSON.stringify(S.world.purchases)===old})()")
  ev("S.preferences.theme='garden';applyTheme();route('focus')")
  ck('Focus uses personal garden state',"$$('[data-living-host]').length===1&&[...gardenInstances][0].passive")
  ev("enhancedAction('immersive',{dataset:{}},{})")
  ck('Fullscreen focus shows only clock and backdrop',"$('.focus-cinema')!==null && !$('.cinema-controls').offsetParent===false && $('.cinema-controls').hasAttribute('inert') && $('#navigation').classList.contains('hidden')")
  ck('Fullscreen controls start visually hidden',"getComputedStyle($('.cinema-controls')).opacity==='0'")
  ev("showCinemaControls()")
  ck('Tap reveals exit controls',"$('.focus-cinema').classList.contains('show-controls')&&!$('.cinema-controls').hasAttribute('inert')")
  page.set_viewport_size({'width':844,'height':390});page.wait_for_timeout(100)
  ck('Landscape has no horizontal overflow',"document.documentElement.scrollWidth<=850")
  ck('Landscape counter stays inside viewport',"(()=>{const r=$('#timer-digits').getBoundingClientRect();return r.left>=0&&r.right<=844&&r.bottom<391})()")
  for style in ['simple','pixel','flip']:
   ev(f"S.preferences.timerStyle='{style}';render()")
   ck('Clock style '+style,f"$('.clock-{style}')!==null")
  page.set_viewport_size({'width':390,'height':844});reset()
  # Actual app functions, synthetic elapsed timestamps (no waiting 25 min).
  ev("startFocus(25)")
  ck('Starting session awards no coins',"wallet()===0&&S.timer.status==='running'")
  ev("toggleFocus()")
  ck('Pause keeps session without reward',"S.timer.status==='paused'&&wallet()===0&&S.focusHistory.length===0")
  ck('Pause survives serialized reload',"(()=>{const time=S.timer.remainingMs;S=normalize(JSON.parse(JSON.stringify(S)));return S.timer.status==='paused'&&S.timer.remainingMs===time})()")
  ev("toggleFocus()")
  ck('Resume keeps remaining duration',"S.timer.status==='running'&&remaining(S.timer)<=1500&&remaining(S.timer)>1497")
  ev("S.timer.status='paused';S.timer.remainingMs=(1500-125)*1000;S.timer.remaining=1375")
  ev("endFocus(false,false)")
  ck('Partial work rewards recorded seconds only',"S.focusHistory.length===1&&S.focusHistory[0].completedSeconds===125&&wallet()===6")
  ck('Partial save offers configured rest',"S.practice.pending?.phase==='break'&&S.practice.pending.minutes===5")
  ck('Repeated completion cannot double award',"(async()=>{const balance=wallet();await endFocus(true,false);return balance===wallet()&&S.focusHistory.length===1})()")
  ev("startFocus(1,{phase:'break'})")
  ev("S.timer.status='paused';S.timer.remainingMs=0;S.timer.remaining=0;endFocus(true,false)")
  ck('Break creates no coins or focus session',"wallet()===6&&S.focusHistory.length===1&&S.practice.pending.phase==='focus'")
  ev("closeSheet();S.practice.cycle=3;startFocus(25)")
  ev("S.timer.status='paused';S.timer.remainingMs=0;S.timer.remaining=0;endFocus(true,false)")
  ck('Fourth pomodoro proposes long rest',"S.practice.cycle===4&&S.practice.pending.minutes===20")
  ck('25 full minutes yields 75 coins',"S.focusHistory[0].completedSeconds===1500 && S.focusHistory[0].coinsAwarded===75")
  ev("S.preferences.method='flow';startFocus(25)")
  ck('Flowtime is count-up mode',"S.timer.flow===true&&currentClock()==='00:00'")
  ev("S.timer.status='paused';S.timer.remainingMs=(43200-600)*1000;S.timer.remaining=42600")
  ck('Flow clock shows elapsed 10 minutes',"currentClock()==='10:00'")
  ev("endFocus(false,false)")
  ck('Flowtime computes adjustable suggested rest',"S.practice.pending.minutes===3&&S.focusHistory[0].completedSeconds===600")
  # Visible reward animation with real frame timing.
  ev("route('focus');void(window.__rewardTest=coinCelebration(12,80,92))")
  page.wait_for_timeout(150)
  ck('Reward overlay has rotating center coin',"!!$('.coin-celebration')&&!!$('.flying-coin')")
  page.wait_for_timeout(1100)
  ck('Reward coin flies toward wallet',"$('.coin-celebration')?.classList.contains('fly')")
  page.wait_for_timeout(1300)
  ck('Reward overlay completes and removes itself',"!$('.coin-celebration')")
  reset();ev("route('notes')")
  ck('Notes add control is fixed',"getComputedStyle($('.note-fab05')).position==='fixed'")
  ev("createNote('blank')");page.wait_for_timeout(200)
  ck('One-step new note opens editor',"!!UI.editorId&&!!$('#rich-editor')")
  ev("$('#editor-title').value='Test notu';$('#rich-editor').innerHTML='<p>Deneme yazısı</p>';flushEditor()")
  ck('Note write persists content',"getNote(UI.editorId).plainText.includes('Deneme')")
  ck('Sanitizer permits editable table but not script',"(()=>{const v=sanitizeHTML('<table><tr><td>Hücre</td></tr></table><script>alert(1)</script>');return v.includes('<table')&&v.includes('<td')&&!v.includes('<script')})()")
  ev("getNote(UI.editorId).paper={kind:'grid',opacity:.2};applyNotePaper(getNote(UI.editorId));openInk()")
  ck('Grid handwriting paper opens',"$('.ink-paper05').dataset.paper==='grid'")
  box=page.locator('#ink-canvas05').bounding_box();x=box['x']+box['width']*.25;y=max(box['y']+20,200)
  page.mouse.move(x,y);page.mouse.down();page.mouse.move(x+70,y+70,steps=12);page.mouse.up()
  ck('Real pointer handwriting records stroke',"inkEditor.strokes.length===1&&inkEditor.strokes[0].points.length>3")
  ev("enhancedAction('ink-undo',{dataset:{}},{})")
  ck('Handwriting undo',"inkEditor.strokes.length===0")
  ev("enhancedAction('ink-redo',{dataset:{}},{})")
  ck('Handwriting redo',"inkEditor.strokes.length===1")
  ev("closeInk()")
  ck('Ink remains in note after close',"getNote(UI.editorId).ink.length===1&&!!$('.ink-preview05')")
  ev("route('notes')")
  ck('Returning list has written note',"$('.note-row05')!==null")
  row=page.locator('.note-open05').first.bounding_box();page.mouse.move(row['x']+70,row['y']+20);page.mouse.down();page.wait_for_timeout(610);page.mouse.up()
  ck('Long press opens trash menu without opening note',"UI.overlay==='note-card'&&!UI.editorId&&!!$('[data-action=\"card-trash\"]')")
  ev("trashFromList(S.notes[0].id)")
  ck('Trash is reversible and list removes note',"!!S.notes[0].deletedAt&&!filteredNotes().some(n=>n.id===S.notes[0].id)&&!!$('.toast-undo')")
  ev("enhancedAction('undo-trash',{dataset:{id:S.notes[0].id}},{})")
  ck('Undo restores same note',"!S.notes[0].deletedAt&&!!$('.note-row05')")
  ev("notesFilter()")
  handle=page.locator('.sheet-head').bounding_box();x=handle['x']+handle['width']/2;y=handle['y']+10
  page.mouse.move(x,y);page.mouse.down();page.mouse.move(x,y+120,steps=15);page.mouse.up();page.wait_for_timeout(150)
  ck('Bottom sheet dismisses by drag',"!UI.overlay")
  # More notes: fixed add remains at same y while scrolling.
  ev("(()=>{const n=S.notes[0];for(let i=0;i<35;i++)S.notes.push({...n,id:uid(),title:'Not '+i});render()})()")
  before=ev("$('.note-fab05').getBoundingClientRect().top")
  ev("$('#screen').scrollTo(0,1500)");page.wait_for_timeout(100)
  ck('Add button stays visible after many notes',f"Math.abs($('.note-fab05').getBoundingClientRect().top-{before})<2 && $('.note-fab05').getBoundingClientRect().bottom<844")
  ck('Schema reload preserves all notes and ink',"(()=>{const len=S.notes.length;S=normalize(JSON.parse(JSON.stringify(S)));return S.notes.length===len&&S.notes[0].ink.length===1})()")
  ev("openEditor(S.notes[0].id);paperSheet()")
  ck('Paper drawer has photo option and five paper kinds',"$$('[data-action=\"set-paper\"]').length===5 && !!$('[data-action=\"paper-image\"]')")
  ev("closeSheet();mixerSheet()")
  ck('Mixer contains independent piano and nature channels',"!!$('[data-sound=\"piano\"]')&&!!$('[data-sound=\"rain\"]')&&!!$('[data-sound=\"fire\"]')&&!!$('[data-sound=\"ocean\"]')")
  ck('Undownloaded audio labelled synthesized rather than real recording',"Object.values(window.LUMA_AUDIO_META).every(v=>v.kind==='synth')&&$('.sheet').innerText.includes('Üretilmiş demo')")
  ck('Fallback piano and nature data embedded for offline use',"['piano','rain','ocean','fire'].every(k=>window.LUMA_AUDIO_DATA[k]?.length>10000)")
  ev("closeSheet()")
  ck('PDF missing library fails explicitly, not a silent share-only substitute',"(async()=>{try{await ensurePdfLibraries();return false}catch(e){return e.message.includes('PDF bileşenleri')}})()")
  # Pure PDF vector overlay tests, independent of the missing PDF render vendor.
  ck('PDF overlay does not orphan active stroke on repaint',"(()=>{pdfView={noteId:S.notes[0].id,file:{id:'pdf-test'},page:1};const data=pdfPageData(),stroke={id:'a',color:'#112233',width:3,points:[[.1,.1]]};data.strokes.push(stroke);pdfPageData();stroke.points.push([.2,.2]);const ok=pdfPageData().strokes[0].points.length===2;pdfView=null;return ok})()")
  ck('PDF coordinates remain normalized',"(()=>{pdfView={noteId:S.notes[0].id,file:{id:'pdf-test2'},page:1};S.notes[0].pdfInk['pdf-test2']={1:{strokes:[{points:[[3,-2]]}],texts:[{text:'Türkçe',x:3,y:-2,color:'bad'}]}};const d=pdfPageData(),ok=d.strokes[0].points[0][0]===1&&d.texts[0].x===1&&d.texts[0].y===0;pdfView=null;return ok})()")
  check('No uncaught browser exceptions',len(errors)==0,errors)
 except Exception as e:
  check('Test execution completed',False,traceback.format_exc())
 finally:
  (OUT/'browser-results.json').write_text(json.dumps({'environment':'Chromium / memory localStorage / no native APIs / no PDF vendor','checks':results,'uncaught_errors':errors},ensure_ascii=False,indent=2))
  b.close()
print('TOTAL',sum(x['pass'] for x in results),'/',len(results))
