import json,hashlib
from pathlib import Path
from playwright.sync_api import sync_playwright
R=Path(__file__).resolve().parents[1]; rows=[]; errors=[]
def record(n,ok,detail=''):
 rows.append({'name':n,'pass':bool(ok),'detail':str(detail)[:300]});print(('PASS ' if ok else 'FAIL ')+n,detail,flush=True)
with sync_playwright() as pw:
 b=pw.chromium.launch(executable_path='/usr/bin/chromium',headless=True,args=['--no-sandbox'])
 page=b.new_page(viewport={'width':390,'height':844});page.on('pageerror',lambda e:errors.append(str(e)))
 page.evaluate("Object.defineProperty(window,'localStorage',{value:{getItem:k=>window.__store?.[k]||null,setItem:(k,v)=>{(window.__store||={})[k]=v}}})")
 page.set_content((R/'ONIZLEME.html').read_text());page.wait_for_timeout(350)
 ev=page.evaluate
 try:
  ev("S=fresh();S.preferences.finishSound=false;S.living.time='day';route('garden');UI.gardenEdit=true;render()")
  def hitcoords(kind):
   return ev("""kind=>{const g=[...gardenInstances].find(g=>!g.passive),h=g.hits.find(h=>h.kind===kind),r=g.canvas.getBoundingClientRect();return{x:r.x+(h.x+h.w/2)*g.fit.scale+g.fit.ox,y:r.y+(h.y+h.h/2)*g.fit.scale+g.fit.oy}}""",kind)
  def worldcoords(x,y):
   return ev("""([x,y])=>{const g=[...gardenInstances].find(g=>!g.passive),r=g.canvas.getBoundingClientRect();return{x:r.x+x*g.fit.scale+g.fit.ox,y:r.y+y*g.fit.scale+g.fit.oy}}""",[x,y])
  pos=worldcoords(200,180);target=worldcoords(250,230)
  page.mouse.move(pos['x'],pos['y']-10);page.mouse.down();page.mouse.move(target['x'],target['y'],steps=15);page.mouse.up();page.wait_for_timeout(100)
  record('Animal dragged and coordinates persisted',ev("Math.abs(S.living.placement['pet:bunny']?.x-250)<5"))
  ev("enhancedAction('living-undo',{dataset:{}},{})")
  record('Drag undo restores previous placement',ev("!S.living.placement['pet:bunny']"))
  ev("UI.groundBrush='stone'");a=worldcoords(175,235);z=worldcoords(290,235)
  page.mouse.move(a['x'],a['y']);page.mouse.down();page.mouse.move(z['x'],z['y'],steps=22);page.mouse.up();page.wait_for_timeout(100)
  record('Dragging terrain brush paints multiple cells',ev("S.living.ground.length>=5"))
  ev("enhancedAction('living-undo',{dataset:{}},{})")
  record('Terrain undo removes whole brush gesture',ev("S.living.ground.length===0"))
  ev("UI.groundBrush=null;UI.gardenEdit=false;render()");pt=hitcoords('cabin');page.mouse.click(pt['x'],pt['y']);page.wait_for_timeout(100)
  record('Cabin opens by tapping actual scene',ev("UI.gardenRoom&&[...gardenInstances].some(g=>g.room)"))
  pt=hitcoords('exit');page.mouse.click(pt['x'],pt['y']);page.wait_for_timeout(100)
  record('Cabin door returns to garden',ev("!UI.gardenRoom"))
  pt=hitcoords('greenhouse');page.mouse.click(pt['x'],pt['y']);page.wait_for_timeout(100)
  record('Greenhouse opens seed album',ev("UI.overlay==='seed-album'"));ev('closeSheet()')
  pt=hitcoords('pot');page.mouse.click(pt['x'],pt['y']);page.wait_for_timeout(100)
  record('Scene pot opens seed picker',ev("UI.overlay==='seed'&&$$('.seed-card').length===10"));ev('closeSheet()')
  ev("plantSeed(0,'sunflower');S.world.credits.x=600;UI.route='focus';render();queueGrowth();")
  record('Growth waiting offscreen has pending animation',ev("S.living.pendingWater.length===1"))
  ev("route('garden')");page.wait_for_timeout(100)
  record('Opening garden plays queued watering once',ev("S.living.pendingWater.length===0&&Date.now()-S.living.watering[S.world.plots[0].id]<1500"))
  # Animation changes with time; do not confuse this with device FPS measurement.
  ev("S.living.weather='rain';render();for(const g of gardenInstances)cancelAnimationFrame(g.raf)")
  a=ev("(()=>{const g=[...gardenInstances][0];g.paint(10000);return g.world.toDataURL()})()")
  z=ev("(()=>{const g=[...gardenInstances][0];g.paint(10800);return g.world.toDataURL()})()")
  record('Rain and living scene produce different animation frames',a!=z)
  ev("S.living.watering={};document.body.classList.add('no-motion')")
  a=ev("(()=>{const g=[...gardenInstances][0];g.paint(10000);return g.world.toDataURL()})()")
  z=ev("(()=>{const g=[...gardenInstances][0];g.paint(14000);return g.world.toDataURL()})()")
  record('Reduced motion freezes scene animation',a==z)
  ev("document.body.classList.remove('no-motion');S.preferences.theme='garden';applyTheme();route('home')")
  record('Own garden can back other app pages',ev("!!$('#app-garden-bg')&&document.body.classList.contains('garden-theme')"))
  ev("route('notes');createNote('blank')");page.wait_for_timeout(250)
  ev("$('#rich-editor').focus();format('insertHTML','<p>Renkli yazı</p>');const e=$('#rich-editor'),r=document.createRange();r.selectNodeContents(e);getSelection().removeAllRanges();getSelection().addRange(r);captureRange();writingTools()")
  page.locator('[data-action="text-color"][data-color="#b44767"]').click();page.wait_for_timeout(80)
  record('Selected text accepts color formatting',ev("getNote(UI.editorId).html.includes('#b44767')||getNote(UI.editorId).html.includes('180, 71, 103')"))
  ev("closeSheet();$('#rich-editor').focus();captureRange();tableOptions();enhancedSubmit($('#table-form'))")
  record('Table insertion creates editable cells',ev("$$('#rich-editor td').length===9"))
  ev("UI.tableCell=$('#rich-editor td');UI.tableCell.textContent='Hücre';enhancedAction('table-add-row',{dataset:{}},{})")
  record('Table row insertion preserves content',ev("$$('#rich-editor tr').length===4&&$('#rich-editor').textContent.includes('Hücre')"))
  ev("enhancedAction('table-add-col',{dataset:{}},{})")
  record('Table column insertion',ev("$('#rich-editor tr').children.length===4"))
  ev("enhancedAction('table-remove-row',{dataset:{}},{})")
  record('Table row removal',ev("$$('#rich-editor tr').length===3"))
  ev("flushEditor();const n=getNote(UI.editorId);n.paper={kind:'grid',opacity:.2};applyNotePaper(n)")
  record('Paper selection does not erase rich text',ev("$$('#rich-editor td').length>0&&$('.editor-scroll').dataset.paper==='grid'"))
  ev("(()=>{const n=getNote(UI.editorId);const c=document.createElement('canvas');c.width=c.height=2;c.getContext('2d').fillRect(0,0,2,2);n.attachments.push({id:'paper-fixture',type:'image',uri:c.toDataURL(),name:'test.png'});n.paper={kind:'image',imageId:'paper-fixture',opacity:.35};openInk();})()")
  page.wait_for_timeout(150)
  record('Handwriting displays selected photo background',ev("$('.ink-paper05').style.getPropertyValue('--paper-image').includes('data:image/png')"))
  record('Photo visibility carried into handwriting page',ev("$('.ink-paper05').style.getPropertyValue('--paper-opacity')==='.35'||$('.ink-paper05').style.getPropertyValue('--paper-opacity')==='0.35'"))
  ev("closeInk();route('notes')")
  for width,height in [(320,568),(375,812),(430,932),(768,1024),(844,390)]:
   page.set_viewport_size({'width':width,'height':height})
   ev("UI.editorId=null;UI.immersive=false;route('notes')");page.wait_for_timeout(60)
   record(f'Note add reachable at {width}x{height}',ev(f"(()=>{{const r=$('.note-fab05').getBoundingClientRect();return r.left>=0&&r.right<={width}&&r.top>0&&r.bottom<={height}}})()"))
   ev("UI.gardenFull=false;route('focus');UI.immersive=true;render()");page.wait_for_timeout(60)
   record(f'Fullscreen counter fits at {width}x{height}',ev(f"(()=>{{const r=$('#timer-digits').getBoundingClientRect();return r.left>=0&&r.right<={width+1}&&r.top>=0&&r.bottom<={height+1}}})()"))
  record('No uncaught interaction errors',not errors,errors)
 except Exception as e:
  import traceback;record('Interaction suite completed',False,traceback.format_exc())
 finally:
  (R/'tests/interaction-results.json').write_text(json.dumps({'environment':'Chromium pointer events; not physical touch hardware','checks':rows,'errors':errors},ensure_ascii=False,indent=2));b.close()
print(sum(r['pass'] for r in rows),'/',len(rows))
