'use strict';
// Actual NativeServices.ts transpiled by TypeScript, with an in-memory FS and Expo API adapters.
// NOT a test of the installed Expo module binaries, physical device or cryptography.
const fs=require('fs'),path=require('path'),vm=require('vm');
let ts;try{ts=require('typescript')}catch{ts=require('/opt/nvm/versions/node/v22.16.0/lib/node_modules/typescript')}
const root=path.resolve(__dirname,'..'),checks=[];
function check(name,ok){checks.push({name,pass:!!ok});console.log(ok?'PASS':'FAIL',name)}
const text=fs.readFileSync(path.join(root,'nocturne/NativeServices.ts'),'utf8');
const compiled=ts.transpileModule(text,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022},reportDiagnostics:true});
function harness(initial={}){const files=new Map(Object.entries(initial)),calls=[],events=[];const f={documentDirectory:'file:///app/',cacheDirectory:'file:///cache/',EncodingType:{Base64:'base64'},getInfoAsync:async p=>({exists:files.has(p),size:files.get(p)?.length||0}),makeDirectoryAsync:async()=>{},readAsStringAsync:async p=>{if(!files.has(p))throw Error('not found');return files.get(p)},writeAsStringAsync:async(p,v)=>{calls.push(['write',p]);files.set(p,v)},copyAsync:async({from,to})=>{if(!files.has(from))throw Error('not found');calls.push(['copy',from,to]);files.set(to,files.get(from))},moveAsync:async({from,to})=>{calls.push(['move',from,to]);files.set(to,files.get(from));files.delete(from)},deleteAsync:async p=>{calls.push(['delete',p]);files.delete(p)}};
 const fake={ './BackupCrypto':{encryptBackup:async()=>{throw Error('Not a crypto test')},decryptBackup:async()=>{throw Error('Not a crypto test')},isEncryptedBackup:()=>false},buffer:{Buffer},'@react-native-async-storage/async-storage':{default:{getItem:async()=>null}},'expo-file-system/legacy':f,'expo-image-picker':{},'expo-document-picker':{},'expo-notifications':{},'expo-sharing':{isAvailableAsync:async()=>true,shareAsync:async()=>{}},'react-native':{Platform:{OS:'ios'},Linking:{}},'expo-keep-awake':{},'./types':{isAppData:v=>!!v&&Array.isArray(v.notes)&&Array.isArray(v.planner)&&Array.isArray(v.focusHistory)}};
 const mod={exports:{}};vm.runInNewContext(compiled.outputText,{exports:mod.exports,module:mod,require:k=>{if(!(k in fake))throw Error('Unexpected module '+k);return fake[k]},Buffer,console,setTimeout,clearTimeout,URL,Date,Math});
 const services=mod.exports.createNativeServices({emit:e=>events.push(e),setAudio:s=>calls.push(['audio',s]),setAppearance:()=>{}});const request=(type,payload={})=>services.handle({id:'test',type,payload});return{files,calls,request};}
(async()=>{for(const p of ['App.tsx','nocturne/NativeServices.ts','nocturne/AudioEngine.tsx','nocturne/BackupCrypto.ts']){const r=ts.transpileModule(fs.readFileSync(path.join(root,p),'utf8'),{fileName:p,compilerOptions:{jsx:ts.JsxEmit.React,module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022},reportDiagnostics:true});check('TypeScript syntax '+p,!r.diagnostics?.length);}
 const old='file:///app/lumanote-nocturne/',now='file:///app/lumanote-living-v05/',file=old+'files/paper.pdf';const state={schema:2,notes:[{id:'note',attachments:[{id:'a',uri:file,name:'paper.pdf',type:'pdf'}]}],planner:[],focusHistory:[],preferences:{}};const raw=JSON.stringify(state),h=harness({[old+'state.json']:raw,[file]:'JVBERi0xLjQK'});
 const s=await h.request('load');check('Old state copied rather than replaced',s.schema===2&&h.files.get(old+'state.json')===raw);check('Old attachment remains unchanged',h.files.get(file)==='JVBERi0xLjQK');check('New attachment stored in versioned directory',s.notes[0].attachments[0].uri.startsWith(now+'files/'));check('Native migration saves a local v04 snapshot',h.files.get(now+'before-v05-state.json')===raw);s.schema=3;s.notes[0].title='Updated';await h.request('save',{state:s});check('New state saved to independent versioned store',JSON.parse(h.files.get(now+'state.json')).schema===3);check('Version 04 store remains byte identical after new save',h.files.get(old+'state.json')===raw);check('No writes/deletes under old root',!h.calls.some(c=>['write','delete'].includes(c[0])&&c[1].startsWith(old)));const again=await h.request('load');check('Subsequent launch reads new state, not old',again.notes[0].title==='Updated');
 const broken=harness({[now+'state.json']:'invalid',[old+'state.json']:raw});let refused=false;try{await broken.request('load')}catch{refused=true}check('Corrupt new state never silently falls back to older state',refused);
 const recovering=harness({[now+'state.json']:'invalid',[now+'state.json.previous']:JSON.stringify(s)});check('Interrupted native write can recover previous valid state',(await recovering.request('load')).schema===3);
 const badLegacy=harness({[old+'state.json']:'invalid'});refused=false;try{await badLegacy.request('load')}catch{refused=true}check('Corrupt legacy state does not silently create empty data',refused);
 refused=false;try{await h.request('readDocument',{uri:'file:///app/../secret.pdf'})}catch{refused=true}check('PDF bridge rejects directory traversal',refused);
 refused=false;try{await h.request('readDocument',{uri:'https://example.test/private.pdf'})}catch{refused=true}check('PDF bridge never fetches remote files',refused);
 await h.request('audio',{playing:true,volumes:{piano:200,rain:-3}});const au=h.calls.findLast(c=>c[0]==='audio')[1];check('Native mixer includes piano and clamps volume',au.volumes.piano===100&&au.volumes.rain===0);
 check('Unencrypted empty backup metadata accepts schema 3',!!(await h.request('createBackup',{state:{schema:3,notes:[],planner:[],focusHistory:[],preferences:{}}})).fileName);
 fs.writeFileSync(path.join(root,'tests/native-model-results.json'),JSON.stringify({environment:'Transpiled actual TypeScript; memory FS and Expo adapters; no native/crypto binaries',checks},null,2));console.log(checks.filter(x=>x.pass).length+'/'+checks.length);
})().catch(e=>{console.error(e);process.exitCode=1;});
