"""Real Chromium checks. Native Expo APIs and persistent device storage are not run."""
from pathlib import Path
from playwright.sync_api import sync_playwright
import json, traceback
ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / 'tests/054'
rows = []

def check(name, value, detail=''):
    rows.append({'name': name, 'pass': bool(value), 'detail': detail})
    print('PASS' if value else 'FAIL', name, detail, flush=True)
with sync_playwright() as pw:
    b = pw.chromium.launch(executable_path='/usr/bin/chromium', headless=True, args=['--no-sandbox', '--enable-unsafe-swiftshader'])
    p = b.new_page(viewport={'width': 390, 'height': 844}, has_touch=True, device_scale_factor=1)
    p.set_default_timeout(6500)
    errors = []
    p.on('pageerror', lambda e: errors.append(str(e)))
    p.evaluate("Object.defineProperty(window,'localStorage',{value:{getItem:k=>window.__store?.[k]||null,setItem:(k,v)=>{(window.__store||={})[k]=v},removeItem:k=>delete window.__store[k]}})")
    try:
        p.set_content((ROOT / 'ONIZLEME.html').read_text())
        p.wait_for_function('ready')
        check('Fresh boot schema 3', p.evaluate('S.schema===3'))
        check('No artificial coin balance', p.evaluate('wallet()===0'))
        check('Movable existing furniture free ownership', p.evaluate("['rug','bookcase','desk','bed'].every(k=>owns('decor',k)&&S.world.purchases.find(p=>p.item===k).cost===0)"))
        check('Furniture migration idempotent', p.evaluate('()=>{S=normalize(JSON.parse(JSON.stringify(S)));const a=JSON.stringify(S);S=normalize(JSON.parse(JSON.stringify(S)));return JSON.stringify(S)===a}'))
        check('Every decoration has art', p.evaluate("Object.keys(DECOR).every(k=>DECOR_ART054[k]&&decorSVG054(k,64).includes('<svg'))"))
        check('All 73 placeable decoration images unique', p.evaluate('()=>{const keys=Object.keys(DECOR).filter(k=>DECOR[k].placeable!==false);return new Set(keys.map(k=>JSON.stringify(DECOR_ART054[k]))).size===keys.length}'))
        check('23 furnishings available', p.evaluate('Object.keys(FURNITURE054).length===23'))
        p.evaluate("()=>{const n=S.notes[0];n.title='Renkli notum';n.html='<p>Bu renkli bir not.</p><p>İkinci satır.</p>';n.plainText=plain(n.html);openEditor(n.id);}")
        p.wait_for_timeout(200)
        p.evaluate("()=>{window.selectText054=(a,b)=>{const ed=$('#rich-editor');ed.focus();const r=document.createRange();r.setStart(ed.firstChild.firstChild,a);r.setEnd(ed.firstChild.firstChild,b);const sel=getSelection();sel.removeAllRanges();sel.addRange(r);captureRange();};selectText054(3,9);}")
        p.locator('[data-action=writing-tools]').click()
        check('Opening formatting retains selection', p.evaluate("getSelection().toString()==='renkli'"))
        p.locator('#writing-panel054 [data-format=bold]').click()
        check('Bold only selected text', p.evaluate("$('#rich-editor').innerHTML.includes('font-weight: bold')&&$('#rich-editor span').textContent==='renkli'"))
        p.locator('#writing-panel054 [data-color="#c3567b"]').click()
        check('Colour preserves bold and selection', p.evaluate("getSelection().toString()==='renkli'&&$('#rich-editor span').style.color==='rgb(195, 86, 123)'&&$('#rich-editor span').style.fontWeight==='bold'"))
        p.locator('#writing-panel054 [data-format=italic]').click()
        check('Italic and colour combined', p.evaluate("$('#rich-editor span').style.fontStyle==='italic'&&$('#rich-editor span').style.color==='rgb(195, 86, 123)'"))
        p.locator('#writing-panel054 [data-format=bold]').click()
        check('Bold toggles off without losing colour', p.evaluate("$('#rich-editor span').style.fontWeight!=='bold'&&$('#rich-editor span').style.fontStyle==='italic'"))
        p.locator('#writing-panel054 [data-format=underline]').click()
        check('Underline selected text', p.evaluate("$('#rich-editor').innerHTML.includes('underline')"))
        check('Toolbar indicates current mark', p.locator('#writing-panel054 [data-format=italic]').get_attribute('aria-pressed') == 'true')
        p.locator('[data-format=undo]').click()
        check('Undo formatting', p.evaluate("!$('#rich-editor').innerHTML.includes('underline')"))
        p.locator('[data-format=redo]').click()
        check('Redo formatting', p.evaluate("$('#rich-editor').innerHTML.includes('underline')"))
        p.evaluate("()=>{window.savedFormatted054=$('#rich-editor').innerHTML;flushEditor();}")
        p.evaluate('closeEditor()')
        p.evaluate('openEditor(S.notes[0].id)')
        check('Formatting survives editor reopen', p.evaluate("$('#rich-editor').innerHTML===window.savedFormatted054"))
        p.evaluate("()=>{const ed=$('#rich-editor');const r=document.createRange();r.selectNodeContents(ed);getSelection().removeAllRanges();getSelection().addRange(r);captureRange();format('foreColor','#438ac7');}")
        check('Formatting across paragraphs', p.evaluate("[...$('#rich-editor').querySelectorAll('p')].every(x=>x.innerHTML.includes('rgb(67, 138, 199)'))"))
        p.evaluate("()=>{const ed=$('#rich-editor'),r=document.createRange();r.selectNodeContents(ed);r.collapse(false);getSelection().removeAllRanges();getSelection().addRange(r);captureRange();format('foreColor','#499779');document.execCommand('insertText',false,' YEŞİL');flushEditor();}")
        check('New text adopts selected colour', p.evaluate("$('#rich-editor').innerHTML.includes('rgb(73, 151, 121)')&&$('#rich-editor').textContent.endsWith(' YEŞİL')"))
        p.evaluate("()=>{const ed=$('#rich-editor'),r=document.createRange();r.selectNodeContents(ed);getSelection().removeAllRanges();getSelection().addRange(r);captureRange();format('removeFormat');}")
        check('Clear formatting retains contents', p.evaluate("!$('#rich-editor').innerHTML.includes('color:')&&$('#rich-editor').textContent.includes('renkli')"))
        check('Formatting leaves title unchanged', p.evaluate("$('#editor-title').value==='Renkli notum'"))
        p.evaluate('closeEditor()')
        p.evaluate("()=>{const n=S.notes[0];S.notes=[0,1,2,3].map(i=>({...n,id:'n'+i,title:'Not '+i,html:'<p>Metin '+i+'</p>',plainText:'Metin '+i,pinned:false,archived:false,deletedAt:undefined,attachments:[]}));UI.query='';UI.trash=false;UI.archived=false;UI.category='Tümü';route('notes');}")
        row = p.locator('[data-note-id=n0] .note-open05')
        box = row.bounding_box()
        p.mouse.move(box['x'] + 55, box['y'] + 20)
        p.mouse.down()
        p.wait_for_timeout(560)
        p.mouse.up()
        p.wait_for_timeout(710)
        check('Long press enters multi selection', p.evaluate("selection054()?.has('n0')&&selection054().size===1"))
        p.locator('[data-id=n1][data-action=note-select-toggle054]').click()
        check('Tap adds another note', p.evaluate('selection054().size===2'))
        p.locator('[data-id=n0][data-action=note-select-toggle054]').click()
        check('Tap deselects a note', p.evaluate("selection054().size===1&&!selection054().has('n0')"))
        p.locator('[data-action=notes-select-all054]').click()
        check('Select all', p.evaluate('selection054().size===4'))
        check('Bulk actions fixed above navigation', p.evaluate("()=>{const a=$('.bulk-bar054').getBoundingClientRect(),n=$('#navigation').getBoundingClientRect();return a.bottom<=n.top+5&&a.top>0;}"))
        p.locator('[data-action=bulk-trash054]').click()
        p.wait_for_function("UI.overlay==='confirm'")
        p.locator('.sheet-head [data-action=close]').click()
        check('Cancel trash retains all notes', p.evaluate('S.notes.every(n=>!n.deletedAt)'))
        p.locator('[data-action=bulk-trash054]').click()
        p.locator('[data-action=confirm]').click()
        p.wait_for_function('S.notes.every(n=>n.deletedAt)')
        check('Bulk trash is reversible', p.evaluate('S.notes.length===4&&S.notes.every(n=>n.deletedAt)'))
        p.locator('[data-action=bulk-undo054]').click()
        p.wait_for_function('S.notes.every(n=>!n.deletedAt)')
        check('Bulk undo restores notes', p.evaluate('S.notes.length===4&&S.notes.every(n=>!n.deletedAt)'))
        p.evaluate("()=>{UI.query='Not 2';UI.noteSelection054=new Set();render()}")
        p.locator('[data-action=notes-select-all054]').click()
        check('Select all respects search scope', p.evaluate("selection054().size===1&&selection054().has('n2')"))
        p.evaluate("()=>{UI.query='';UI.noteSelection054=new Set(['n0','n1']);window.confirmBak054=confirmAction;confirmAction=async()=>true;window.persistBak054=persist;persist=async()=>{throw Error('simulated disk failure')};void 0;}")
        err = p.evaluate("bulkApply054('trash').then(()=>null).catch(e=>e.message)")
        check('Failed bulk save rolls back all notes', err == 'simulated disk failure' and p.evaluate('S.notes.every(n=>!n.deletedAt)'))
        p.evaluate("()=>{persist=window.persistBak054;confirmAction=window.confirmBak054;UI.noteSelection054=null;UI.trash=false;route('garden');}")
        check('No redundant garden scenery button', p.locator('.garden-heading053 [data-action=scenery-sheet]').count() == 0)
        p.evaluate('weatherSheet()')
        check('No automatic weather/light choices', p.locator('.sheet').inner_text().find('Temaya göre') == -1 and p.locator('.sheet').inner_text().find('Manzaraya göre') == -1)
        p.locator('[data-action=set-weather][data-value=snow]').click()
        check('Snow whites the ground', p.evaluate("gardenWeather()==='snow'&&sceneryProfile().grass==='#e5eef2'"))
        head = p.locator('.sheet-drag-zone053').bounding_box()
        p.mouse.move(head['x'] + 100, head['y'] + 12)
        p.mouse.down()
        p.mouse.move(head['x'] + 100, head['y'] + 132, steps=8)
        p.mouse.up()
        p.wait_for_timeout(400)
        check('Sheet closes by dragging grip', p.evaluate('!UI.overlay'))
        p.evaluate('()=>{S.living.baseCoins=30000;window.initialBalance054=wallet();window.confirmBak054=confirmAction;confirmAction=async()=>true;void 0;}')
        p.evaluate("purchaseAtmosphere054('sakura')")
        check('Sakura one-time debit 4500', p.evaluate("wallet()===initialBalance054-4500&&atmosphere054()==='sakura'"))
        p.evaluate("purchaseAtmosphere054('sakura')")
        check('Owned mode not charged twice', p.evaluate('wallet()===initialBalance054-4500'))
        p.evaluate("setAtmosphere054('normal')")
        check('Normal restores existing scenery', p.evaluate("atmosphere054()==='normal'&&S.world.background==='night'"))
        p.evaluate('()=>{const before=wallet();S=normalize(JSON.parse(JSON.stringify(S)));window.retainedBalance054=before===wallet();}')
        check('Purchased mode survives normalized reload', p.evaluate("retainedBalance054&&ownsAtmosphere054('sakura')"))
        p.evaluate("purchaseAtmosphere054('winter')")
        check('Winter defaults snow/night/white', p.evaluate("atmosphere054()==='winter'&&gardenTime()==='night'&&gardenWeather()==='snow'&&sceneryProfile().grass==='#e5eef2'"))
        p.screenshot(path=str(OUT / 'winter.png'))
        p.evaluate("purchaseAtmosphere054('halloween')")
        check('Halloween has autumn landscape', p.evaluate("atmosphere054()==='halloween'&&sceneryProfile().grass==='#9b7950'&&gardenWeather()==='clear'"))
        p.screenshot(path=str(OUT / 'halloween.png'))
        p.evaluate("()=>{S.living.baseCoins=0;S.world.purchases=S.world.purchases.filter(p=>!p.item.startsWith('mode'));S.living.atmosphere='normal';}")
        p.evaluate("purchaseAtmosphere054('winter')")
        check('Insufficient funds blocked', p.evaluate("!ownsAtmosphere054('winter')&&wallet()===0"))
        p.evaluate("()=>{S.living.baseCoins=10000;window.oldWallet054=wallet();window.persistBak054=persist;persist=async()=>{throw Error('mode failure')};}")
        err = p.evaluate("purchaseAtmosphere054('halloween').then(()=>null).catch(e=>e.message)")
        check('Failed mode save refunds state', err == 'mode failure' and p.evaluate("!ownsAtmosphere054('halloween')&&wallet()===oldWallet054&&atmosphere054()==='normal'"))
        p.evaluate('()=>{persist=window.persistBak054;confirmAction=window.confirmBak054;}')
        p.evaluate("()=>{UI.gardenRoom=true;render();UI.shopTab='home';route('shop')}")
        check('Cabin shop remembers return room', p.evaluate("UI.shopTab==='home'&&UI.shopDestination054===true"))
        p.locator('[data-action=buy-item][data-item=sofa]').click()
        p.wait_for_function("owns('decor','sofa')")
        p.locator('[data-action=place-owned][data-item=sofa]').click()
        p.wait_for_function("UI.route==='garden'&&UI.gardenRoom")
        check('Furniture goes inside cabin', p.evaluate("S.living.placement['decor:sofa'].room===true"))
        p.evaluate("()=>{window.roomX054=S.living.placement['decor:sofa'].x;}")
        p.locator('[data-action=living-nudge][data-direction=right]').click()
        check('Furniture arrow placement', p.evaluate("S.living.placement['decor:sofa'].x===roomX054+8"))
        p.locator('[data-action=living-remove]').click()
        p.wait_for_function("!S.world.layout.some(x=>x.item==='sofa')")
        check('Removing furniture retains ownership', p.evaluate("owns('decor','sofa')&&!S.living.placement['decor:sofa']"))
        p.evaluate("placeOwned('decor','sofa')")
        check('Re-placing owned furniture costs nothing', p.evaluate("S.world.purchases.filter(x=>x.item==='sofa').length===1"))
        p.evaluate("()=>{window.sofaBefore054=JSON.stringify(S.living.placement['decor:sofa']);UI.gardenRoom=false;render();}")
        p.evaluate("enhancedAction('living-layout',{dataset:{layout:'forest'}},{})")
        check('Outdoor preset leaves furniture indoors', p.evaluate("JSON.stringify(S.living.placement['decor:sofa'])===sofaBefore054"))
        p.evaluate("()=>{S.world.purchases.push({id:'tvtest',type:'decor',item:'television',cost:0,at:new Date().toISOString()});UI.gardenRoom=true;}")
        p.evaluate("placeOwned('decor','television')")
        p.evaluate('()=>{UI.gardenEdit=false;render()}')
        p.wait_for_timeout(250)
        pt = p.evaluate("()=>{const g=[...gardenInstances].find(g=>!g.passive),hit=g.hits.find(x=>x.item==='television'),r=g.canvas.getBoundingClientRect(),f=g.fit;return {x:r.left+(hit.x+hit.w/2)*f.scale+f.ox,y:r.top+(hit.y+hit.h/2)*f.scale+f.oy}}")
        p.mouse.click(pt['x'], pt['y'])
        p.wait_for_timeout(200)
        check('TV touch turns it off', p.evaluate('S.living.roomDevices.television===false'))
        p.evaluate('()=>{UI.gardenRoom=false;UI.gardenEdit=false;render();}')
        g = p.locator('.garden-stage canvas').bounding_box()
        p.mouse.move(g['x'] + 120, g['y'] + 250)
        p.mouse.down()
        p.mouse.move(g['x'] + 200, g['y'] + 280, steps=6)
        p.mouse.up()
        check('Single drag does not pan garden', p.evaluate('[...gardenInstances].filter(g=>!g.passive).every(g=>g.pan.x===0&&g.pan.y===0)'))
        p.locator('[data-action=garden-zoom][data-delta=".25"]').click()
        check('Zoom retained', p.evaluate('[...gardenInstances].some(g=>!g.passive&&g.zoom===1.25)'))
        p.locator('[data-action=garden-reset-view]').click()
        check('Fit reset retained', p.evaluate('[...gardenInstances].filter(g=>!g.passive).every(g=>g.zoom===1)'))
        p.evaluate("()=>{UI.gardenEdit=false;S.world.petNames.bunny='A';route('focus');}")
        check('Pet name beside normal timer', p.locator('.focus-companion053').inner_text() == 'A yanında.')
        p.evaluate('()=>{UI.immersive=true;render()}')
        check('No companion clutter in immersive', p.locator('.focus-companion053').count() == 0)
        p.set_viewport_size({'width': 844, 'height': 390})
        p.wait_for_timeout(150)
        check('Landscape timer fits viewport', p.evaluate('document.documentElement.scrollWidth<=innerWidth'))
        p.evaluate("()=>{UI.immersive=false;route('garden');}")
        for w in [320, 375, 390, 430, 768]:
            p.set_viewport_size({'width': w, 'height': 844})
            p.wait_for_timeout(130)
            check('No horizontal overflow garden ' + str(w), p.evaluate("document.documentElement.scrollWidth<=innerWidth&&$('.garden-stage').getBoundingClientRect().right<=innerWidth"))
            p.evaluate("()=>{UI.shopTab='decor';route('shop')}")
            p.wait_for_timeout(60)
            check('No overflow catalogue ' + str(w), p.evaluate('document.documentElement.scrollWidth<=innerWidth'))
            p.evaluate("route('garden')")
        p.evaluate('()=>{window.preGated054=S.preferences.volumes.ocean;S.preferences.volumes.ocean=70;}')
        check('Missing real sound cannot play synthesis', p.evaluate('effectiveVolumes054(S.preferences.volumes).ocean===0&&S.preferences.volumes.ocean===70'))
        p.evaluate("window.LUMA_AUDIO_META.ocean={kind:'recording',author:'fixture'}")
        check('Real sound passes playback gate', p.evaluate('effectiveVolumes054(S.preferences.volumes).ocean===70'))
        check('No unhandled browser errors', len(errors) == 0, '; '.join(errors))
    except Exception:
        rows.append({'name': 'Unexpected exception', 'pass': False, 'detail': traceback.format_exc()})
        print(traceback.format_exc(), flush=True)
    finally:
        (OUT / 'browser-results.json').write_text(json.dumps({'checks': rows, 'errors': errors, 'passed': sum((x['pass'] for x in rows)), 'total': len(rows)}, ensure_ascii=False, indent=2))
        print('RESULT', sum((x['pass'] for x in rows)), '/', len(rows), flush=True)
        b.close()
