/* Bundled original sound design: no download, account or paid sound pack needed.
   Deliberately labelled synthesis. It must not be advertised as a field recording. */
const PIANO_TRACKS056={piano:audioInfo('piano').kind==='recording'?'Önceki piyano kaydı':'Küçük Bahçe',pianoMoon:'Ay Bahçesi',pianoDawn:'Sabah Defteri',pianoSakura:'Pembe Yapraklar'};
Object.assign(defaultPrefs.volumes,{piano:0,pianoMoon:0,pianoDawn:0,pianoSakura:0});
Object.assign(soundNames,{piano:'Piyano · Küçük Bahçe',pianoMoon:'Piyano · Ay Bahçesi',pianoDawn:'Piyano · Sabah Defteri',pianoSakura:'Piyano · Pembe Yapraklar'});
missingRecording054=function(key){return ['ocean','fire'].includes(key)&&!['procedural','recording'].includes(audioInfo(key).kind);};
function activePiano056(){return Object.keys(PIANO_TRACKS056).find(k=>Number(S.preferences.volumes[k])>0)|| (PIANO_TRACKS056[S.preferences.pianoTrack056]?S.preferences.pianoTrack056:'pianoMoon');}
function audioDescription056(key){const a=audioInfo(key);if(a.kind==='procedural')return 'Özgün ses tasarımı · pakete dahil';if(a.kind==='recording')return 'Kayıt · '+esc(a.author);return key==='brown'?'Yumuşak, üretilmiş ses':'Özgün sentez';}
function soundRow056(key,title,description){return `<div class="sound-row"><div class="row"><button class="icon-btn" data-action="toggle-channel" data-channel="${key}" aria-label="${esc(title)} aç/kapat">${icon(key==='brown'?'noise':key==='cafe'?'coffee':key.startsWith('piano')?'headphones':key,21)}</button><div class="grow"><h3>${esc(title)}</h3><p class="muted">${description}</p></div><span class="sound-value" id="vol-${key}">${S.preferences.volumes[key]||0}%</span></div>${key==='cafe'&&!S.preferences.customAudio?'<button class="text-btn" data-action="import-audio">Ses dosyası ekle</button>':`<input type="range" min="0" max="100" value="${S.preferences.volumes[key]||0}" data-sound="${key}" aria-label="${esc(title)} ses seviyesi">`}</div>`;}
mixerSheet=function(){const pk=activePiano056();sheet('Ses alanım',`<div class="presets"><button data-action="atelier-mix056" data-mix="coast">Kıyıda piyano</button><button data-action="atelier-mix056" data-mix="fire">Şömine başı</button><button data-action="atelier-mix056" data-mix="rain">Yağmur & yapraklar</button>${S.preferences.soundPresets.map((p,i)=>`<button data-action="saved-mix" data-index="${i}">${esc(p.name)}</button>`).join('')}</div>${[['rain','Yağmur'],['ocean','Kıyı dalgaları'],['fire','Odun çıtırtısı'],['brown','Yumuşak gürültü']].map(([k,n])=>soundRow056(k,n,audioDescription056(k))).join('')}<section class="piano-panel056"><div class="section-top"><h2>Piyano</h2><small>4 piyano seçeneği</small></div><div class="piano-choices056">${Object.entries(PIANO_TRACKS056).map(([k,n])=>`<button class="${k===pk?'selected':''}" aria-pressed="${k===pk}" data-action="piano-track056" data-track="${k}">${icon('headphones',16)}<span>${esc(n)}</span></button>`).join('')}</div>${soundRow056(pk,PIANO_TRACKS056[pk],audioInfo(pk).kind==='recording'?audioDescription056(pk):'Özgün beste · piyano benzeri sentez')}</section>${soundRow056('cafe','Kendi sesim',esc(S.preferences.customAudio?.name||'Kullanım hakkın olan dosyanı ekle'))}<button class="btn primary full" id="mixer-play" data-action="sound-toggle">${icon(UI.soundPlaying?'pause':'play',17)}${UI.soundPlaying?'Durdur':'Dinle'}</button><button class="text-btn full" data-action="save-mix">Karışımı kaydet</button><button class="text-btn full" data-action="audio-credits">Sesler hakkında</button><p class="hint">Kıyı ve ateş, bu proje için üretilmiş ses tasarımlarıdır; gerçek ortam kaydı değildir. İndirme gerektirmez. Telefon kilitlenince sesler durur.</p>`,'mixer');};
const audioActionBefore056=enhancedAction;
enhancedAction=async function(name,el,e){const d=el.dataset;
 if(name==='piano-track056'){if(!PIANO_TRACKS056[d.track])return true;const before={...S.preferences.volumes},previous=S.preferences.pianoTrack056,volume=Math.max(25,...Object.keys(PIANO_TRACKS056).map(k=>Number(before[k])||0));for(const k of Object.keys(PIANO_TRACKS056))S.preferences.volumes[k]=0;S.preferences.volumes[d.track]=volume;S.preferences.pianoTrack056=d.track;try{await persist(true);}catch(err){S.preferences.volumes=before;S.preferences.pianoTrack056=previous;throw err;}if(UI.soundPlaying)await setSoundPlaying(true);mixerSheet();return true;}
 if(name==='atelier-mix056'){const before={...S.preferences.volumes};for(const k of Object.keys(S.preferences.volumes))S.preferences.volumes[k]=0;const set=d.mix==='fire'?{fire:58,pianoMoon:24}:d.mix==='rain'?{rain:45,pianoSakura:27}:{ocean:58,pianoDawn:22};Object.assign(S.preferences.volumes,set);try{await persist(true);}catch(err){S.preferences.volumes=before;throw err;}await setSoundPlaying(true);mixerSheet();return true;}
 if(['sound-preset','piano-mix'].includes(name)){for(const k of Object.keys(PIANO_TRACKS056))S.preferences.volumes[k]=0;}
 if(name==='audio-credits'){sheet('Paketteki sesler',`<div class="reading-content"><p>Kıyı dalgaları, odun çıtırtısı ve üç yeni piyano bu projede kodla üretilmiştir. Doğa sesleri <strong>saha kaydı değil, sentez yaklaşımıdır</strong>. Piyanolar yeni bestelerdir; bilinen klasik eserlerin kayıtları değildir.</p>${Object.entries(window.LUMA_AUDIO_META||{}).map(([k,a])=>`<h3>${esc(soundNames[k]||k)}</h3><p>${esc(a.title||k)} · ${esc(a.author||'LumaNote')}<br>${a.kind==='procedural'?'Özgün üretim · '+Math.round(a.durationSeconds||0)+' saniye':a.kind==='recording'?'Kayıt · '+esc(a.license):'Özgün sentez'}</p>`).join('')}<p>Bu ekler ücretli ses kütüphanesi gerektirmez; üçüncü taraf piyano örnekleri kullanılmadı. Kaynak üretim kodu ve dosya bilgileri proje içindedir.</p></div>`,'audio-credits');return true;}
 return audioActionBefore056(name,el,e);
};
// Browser preview: coalesce decodes while sliders move, and release muted buffers.
// Native playback keeps using the existing Expo AudioEngine and local MP3 assets.
const webAudioBefore056=updateWebAudio;
updateWebAudio=async function(p){if(!window.LUMA_AUDIO_DATA)return webAudioBefore056(p);webAudio.desired056={...p,volumes:{...p.volumes}};
 if(!p.playing){if(webAudio.ctx)for(const [key,n] of Object.entries(webAudio.nodes)){n.gain.gain.setTargetAtTime(0,webAudio.ctx.currentTime,.12);try{n.source.stop(webAudio.ctx.currentTime+.5);}catch{}delete webAudio.nodes[key];}webAudio.custom?.pause();return true;}
 if(!webAudio.ctx){const C=window.AudioContext||window.webkitAudioContext;if(!C)throw Error('Ses motoru desteklenmiyor.');webAudio.ctx=new C();}const ctx=webAudio.ctx;await ctx.resume();webAudio.loading056 ||= {};
 const keys=Object.keys(window.LUMA_AUDIO_DATA);for(const key of keys){if(!Number(p.volumes[key]))continue;if(webAudio.nodes[key])continue;
  webAudio.loading056[key] ||= (async()=>{const data=window.LUMA_AUDIO_DATA[key],bytes=Uint8Array.from(atob(data),c=>c.charCodeAt(0)),buffer=await ctx.decodeAudioData(bytes.buffer);const latest=webAudio.desired056;if(!latest?.playing||!Number(latest.volumes[key])||webAudio.nodes[key])return;
   const overlap=Math.min(Math.floor(buffer.sampleRate*1.5),Math.floor(buffer.length/4)),loop=ctx.createBuffer(buffer.numberOfChannels,buffer.length-overlap,buffer.sampleRate);
   for(let ch=0;ch<buffer.numberOfChannels;ch++){const src=buffer.getChannelData(ch),dest=loop.getChannelData(ch);dest.set(src.subarray(0,dest.length));for(let i=0;i<overlap;i++){const q=i/overlap;dest[i]=src[buffer.length-overlap+i]*Math.cos(q*Math.PI/2)+src[i]*Math.sin(q*Math.PI/2);}}
   const source=ctx.createBufferSource(),gain=ctx.createGain();source.buffer=loop;source.loop=true;gain.gain.value=0;source.connect(gain);gain.connect(ctx.destination);source.start();webAudio.nodes[key]={source,gain};})().finally(()=>delete webAudio.loading056[key]);
 }
 await Promise.all(Object.values(webAudio.loading056));const latest=webAudio.desired056;if(!latest?.playing)return true;const sum=Object.entries(latest.volumes).filter(([k])=>k!=='cafe'||latest.customAudio).reduce((s,[,v])=>s+(Number(v)||0),0),scale=100/Math.max(100,sum);
 for(const [key,n]of Object.entries(webAudio.nodes)){const v=(Number(latest.volumes[key])||0)/100*scale*.65;n.gain.gain.setTargetAtTime(v,ctx.currentTime,.25);if(!v){try{n.source.stop(ctx.currentTime+.7);}catch{}delete webAudio.nodes[key];}}
 if(latest.customAudio){if(!webAudio.custom||webAudio.custom.src!==latest.customAudio.uri){webAudio.custom?.pause();webAudio.custom=new Audio(latest.customAudio.uri);webAudio.custom.loop=true;}webAudio.custom.volume=(latest.volumes.cafe||0)/100*scale*.65;if(latest.volumes.cafe>0)await webAudio.custom.play();else webAudio.custom.pause();}else webAudio.custom?.pause();return true;
};
