/* UI composition, room-aware placement and corrected modal layering. */
const havenRenderGarden056=renderGarden;
renderGarden=function(){if(!UI.gardenRoom){let html=havenRenderGarden056();html=html.replace('İki parmakla yakınlaş · yakınken sürükle','İki parmakla yakınlaş · çift dokunarak sıfırla');html=html.replace('<div class="garden-quiet-stats">','<div class="garden-quiet-stats"><button data-action="space-open057" data-space="salon">'+icon('home',16)+' Evim</button><button data-action="space-open057" data-space="greenhouse">'+icon('leaf',16)+' Sera</button>');return html;}
 const id=currentSpace057(),space=SPACES057[id];return `<div class="${UI.gardenFull?'garden-full':'page garden-page living-page'} indoor-page057">${UI.gardenFull?'':header()+`<div class="section-heading"><div><span class="eyebrow">${id==='greenhouse'?'CAMIN ARDINDA':'EVİM'}</span><h1>${space.name}</h1></div><button class="round-link" data-action="space-list057">${icon('home',16)} Odalar</button></div>`}<div class="garden-stage room-stage057">${livingHost('room-host057')}${stableToolbar()}${UI.gardenEdit?'<div class="garden-edit-chip">Düzenleme</div>':''}</div><div class="garden-dock"><button data-action="garden-edit" class="${UI.gardenEdit?'active':''}">${icon(UI.gardenEdit?'check':'edit',18)}${UI.gardenEdit?'Bitti':'Düzenle'}</button><button data-action="route" data-route="shop">${icon('grid',18)}Mağaza</button><button data-action="inventory">${icon('leaf',18)}Koleksiyon</button><button data-action="room-style054">${icon('sliders',18)}Oda</button></div>${UI.gardenEdit?'<div id="garden-selection"></div>':''}${UI.gardenFull?'':`<div class="space-tabs057" aria-label="Odalar">${Object.entries(SPACES057).map(([k,v])=>`<button class="${k===id?'selected':''}" aria-pressed="${k===id}" data-action="space-open057" data-space="${k}">${k==='greenhouse'?'Sera':v.name}</button>`).join('')}</div><button class="room-exit057" data-action="living-exit-room">${icon('back',16)} Bahçeye dön</button>`}</div>`;};
function spaceList057(){sheet('Evim ve kış bahçem',`<div class="space-menu057">${Object.entries(SPACES057).map(([k,v])=>`<button data-action="space-open057" data-space="${k}"><span>${pixel(({salon:'sofaSage',kitchen:'htStove057',bathroom:'htBath057',lounge:'armchair',bedroom:'bed',greenhouse:'ghShelf057'})[k],67)}</span><strong>${v.name}</strong><small>${v.subtitle}</small></button>`).join('')}</div>`,'space-list057');}
const oldGround057=groundSheet;
groundSheet=function(){if(UI.gardenRoom)return roomStyle054();sheet('Zemin ve yerleşim',`<p class="hint">Bir zemin seç, bahçede parmağını gezdir. Önceki eşyaların yerinde kalır.</p><div class="chips">${[['','Seç ve taşı'],['stone','Taş yol'],['wood','Ahşap'],['flower','Çiçek bordürü'],['erase','Zemini temizle']].map(([k,n])=>`<button class="chip" data-action="choose-ground" data-brush="${k}">${n}</button>`).join('')}</div><h3>Kulübe rengi</h3><div class="chips">${[['wood','Sıcak ahşap'],['blue','Gece mavisi'],['rose','Gül kurusu']].map(([k,n])=>`<button class="chip" data-action="home-color" data-color="${k}">${n}</button>`).join('')}</div>`,'ground');};
roomStyle054=function(){const id=currentSpace057(),s=S.living.rooms057.styles[id];if(!s)return;sheet(SPACES057[id].name+' · görünüm',`<h3>Duvar / çerçeve</h3><div class="chips">${[['cream','Krem'],['sage','Adaçayı'],['rose','Gül'],['night','Mavi'],['mist','Sis']].map(([k,n])=>`<button class="chip ${s.wall===k?'active':''}" data-action="space-style057" data-field="wall" data-value="${k}">${n}</button>`).join('')}</div><h3>Zemin</h3><div class="chips">${[['oak','Meşe'],['walnut','Ceviz'],['light','Açık ahşap'],['tile','Karo'],['stone','Taş']].map(([k,n])=>`<button class="chip ${s.floor===k?'active':''}" data-action="space-style057" data-field="floor" data-value="${k}">${n}</button>`).join('')}</div><button class="btn primary full" data-action="space-shop057">Bu alanı döşe</button><button class="btn ghost full" data-action="space-list057">Diğer odalar</button>`,'room-style');};
const shopTabsBefore057=collectionTabs056;
collectionTabs056=function(active){return `<div class="shop-tabs054 haven-tabs057" role="tablist">${[['pets','Arkadaşlar'],['decor','Bahçe'],['sakura055','Japon · Sakura'],['anatolia056','Çay & Kilim'],['winter057','Yılbaşı'],['halloween057','Cadılar Bayramı'],['interior057','Sera & Odalar'],['home','Ev eşyaları'],['modes','Özel hava'],['scenery','Manzara']].map(([id,n])=>`<button role="tab" aria-selected="${active===id}" class="${active===id?'active':''}" data-action="shop-tab" data-tab="${id}">${n}</button>`).join('')}</div>`;};sakuraTabs055=collectionTabs056;
const collectionList057={winter057:{name:'Yılbaşı',eyebrow:'KIŞIN KÜÇÜK IŞIKLARI',items:WINTER057},halloween057:{name:'Cadılar Bayramı',eyebrow:'TATLI BİR ÜRPERTİ',items:HALLOWEEN057},interior057:{name:'Sera & Odalar',eyebrow:'İÇERİDE YENİ BİR DÜNYA',items:FURNITURE057}};
function havenCard057(id){const a=DECOR[id],owned=owns('decor',id);return `<article class="shop-card haven-card057"><button class="sakura-art055" data-action="haven-detail057" data-item="${id}" aria-label="${esc(a.name)} ayrıntıları">${pixel(id,116)}</button><small>${a.recommendedRoom?SPACES057[a.recommendedRoom].name:'Bahçe / ev / sera'}</small><h3>${esc(a.name)}</h3><button class="shop-buy ${owned?'owned':''}" data-action="${owned?'haven-place057':'haven-buy057'}" data-item="${id}">${owned?'Yerleştir':coinIcon(14)+' '+a.price.toLocaleString('tr-TR')}</button></article>`;}
const shopBefore057=renderShop;
renderShop=function(){const tab=UI.shopTab,cat=collectionList057[tab];if(cat){let ids=Object.keys(cat.items);const filter=UI.interiorFilter057||'all';if(tab==='interior057'&&filter!=='all')ids=ids.filter(k=>DECOR[k].recommendedRoom===filter);return `<div class="page shop054 haven-shop057">${header('',true)}<div class="section-heading"><div><span class="eyebrow">${cat.eyebrow}</span><h1>${cat.name}</h1></div></div><div class="shop-guide">${coinIcon(16)} ${wallet().toLocaleString('tr-TR')} jeton</div>${collectionTabs056(tab)}<p class="hint">${tab==='interior057'?'Her eşya dilediğin odaya veya seraya yerleşebilir.':'Özel hava modunu satın almak gerekmez. Tek sefer al, istediğin yerde kullan.'}</p>${tab==='interior057'?`<div class="chips">${[['all','Tümü'],['greenhouse','Kış bahçesi'],['kitchen','Mutfak'],['bathroom','Banyo']].map(([id,n])=>`<button class="chip ${id===filter?'active':''}" data-action="interior-filter057" data-filter="${id}">${n}</button>`).join('')}</div>`:''}<div class="shop-grid">${ids.map(havenCard057).join('')}</div></div>`;}
 let html=shopBefore057();html=html.replace(/<div class="shop-tabs054[^\"]*" role="tablist">[\s\S]*?<\/div>/,()=>collectionTabs056(UI.shopTab));return html;};
const shortcutsBefore057=collectionsShortcut056;
collectionsShortcut056=function(){return shortcutsBefore057().replace('</section>',`<button data-action="collection-open057" data-tab="winter057">${pixel('wnSnowman057',54)}<span><strong>Yılbaşı</strong><small>24 yeni dekor</small></span>${icon('chevron',14)}</button><button data-action="collection-open057" data-tab="halloween057">${pixel('hwCauldron057',54)}<span><strong>Cadılar Bayramı</strong><small>24 yeni dekor</small></span>${icon('chevron',14)}</button></section>`);};
function havenDetail057(id){const a=DECOR[id];if(!a||!['winter057','halloween057','interior057'].includes(a.collection))return;sheet(a.name,`<div class="sakura-preview055">${pixel(id,170)}</div><p class="hint">${esc(a.description)}</p><button class="btn primary full" data-action="${owns('decor',id)?'haven-place057':'haven-buy057'}" data-item="${id}">${owns('decor',id)?'Yerleştir':coinIcon(16)+' '+a.price.toLocaleString('tr-TR')+' jetona al'}</button>`,'haven-detail057');}
function destinationSheet057(type,id){if(type!=='plant'&&!owns(type,id))return;const a=DECOR[id];sheet('Nereye yerleştirelim?',`<div class="destination-grid057">${a?.roomOnly?'':`<button data-action="place-destination057" data-type="${type}" data-item="${esc(id)}" data-space="garden">${icon('leaf',22)} Bahçeye</button>`}${Object.entries(SPACES057).map(([k,v])=>`<button data-action="place-destination057" data-type="${type}" data-item="${esc(id)}" data-space="${k}">${icon(v.icon,22)} ${v.name}</button>`).join('')}</div><p class="hint">Mevcut öğe seçtiğin alana taşınır; ikinci kez jeton harcanmaz.</p>`,'destination057');}
let placing057=false;
placeOwned=async function(type,id){const def=type==='decor'?DECOR[id]:null;if(def?.placeable===false)return;if(type==='plant'?!S.world.harvested.some(x=>x.id===id):!owns(type,id))return;
 if(def?.group==='pots'){const old=S.world.pot;S.world.pot=id;try{await persist(true);}catch(e){S.world.pot=old;throw e;}closeSheet();return;}
 if(placing057)return;placing057=true;try{let target=UI.pendingSpace057||(UI.route==='shop'?(UI.shopDestination054?(UI.shopInterior057||'salon'):'garden'):currentSpace057());UI.pendingSpace057=null;
 if(def?.roomOnly&&target==='garden')target=def.recommendedRoom||'salon';if(target!=='garden'&&!SPACES057[target])target='salon';const indoor=target!=='garden',key=type+':'+id,beforeWorld=structuredClone(S.world),beforeLiving=structuredClone(S.living);
 let item=S.world.layout.find(x=>x.type===type&&x.item===id);if(!item){if(S.world.layout.length>=180){toast('En fazla 180 öğe yerleştirilebilir. Birini koleksiyona kaldır.');return;}item={id:uid(),type,item:id,x:50,y:75};S.world.layout.push(item);}
 const previous=S.living.placement[key],priorSpace=previous?.room?(S.living.rooms057.assignments[key]||'salon'):'garden';if(!previous||priorSpace!==target)S.living.placement[key]=constrainPlacement054(key,{x:240,y:222,room:indoor});if(indoor)S.living.rooms057.assignments[key]=target;else delete S.living.rooms057.assignments[key];
 try{await persist(true);}catch(e){S.world=beforeWorld;S.living=beforeLiving;throw e;}UI.gardenEdit=true;UI.groundBrush=null;UI.selectedLiving=key;UI.shopDestination054=indoor;UI.gardenRoom=indoor;if(indoor){UI.interior057=target;UI.shopInterior057=target;}closeSheet();route('garden');
 }finally{placing057=false;UI.pendingSpace057=null;}
};
const routeBefore057=route;
route=function(name,opts={}){if(name==='shop'&&UI.route==='garden'&&UI.gardenRoom){UI.shopInterior057=currentSpace057();UI.shopDestination054=true;}const ans=routeBefore057(name,opts);if(name==='shop'&&UI.shopDestination054&&UI.shopInterior057==='greenhouse'&&UI.shopTab==='home'){UI.shopTab='interior057';UI.interiorFilter057='greenhouse';render();}return ans;};
inventorySheet=function(){const items=[...ownedPets().map(id=>({type:'pet',id,label:petLabel(id),sprite:id})),...S.world.harvested.map(p=>({type:'plant',id:p.id,label:SEEDS[p.kind].name,sprite:SEEDS[p.kind].sprite})),...S.world.purchases.filter(p=>p.type==='decor'&&DECOR[p.item]?.placeable!==false&&DECOR[p.item]?.group!=='pots').map(p=>({type:'decor',id:p.item,label:DECOR[p.item].name,sprite:p.item}))];sheet('Koleksiyonum',`<div class="inventory-grid">${items.map(p=>{const item=livingPlacements().find(x=>x.key===p.type+':'+p.id),loc=item?itemSpace057(item):null;return `<button data-action="inventory-place057" data-type="${p.type}" data-item="${esc(p.id)}">${pixel(p.sprite,64)}<strong>${esc(p.label)}</strong><small>${!loc?'Yerleştir':loc==='garden'?'Bahçede':SPACES057[loc]?.name||'Evde'}</small></button>`;}).join('')}</div>`,'inventory');};
const havenAction056=enhancedAction;
enhancedAction=async function(name,el,e){const d=el.dataset;
 if(name==='space-open057'){openSpace057(d.space);return true;}
 if(name==='living-exit-room'){exitSpace057();return true;}
 if(name==='space-list057'){spaceList057();return true;}
 if(name==='living-layout')return true; // Removed preset layouts must never rearrange personal items.
 if(name==='space-style057'){const id=currentSpace057(),styles=S.living.rooms057.styles,allowed=d.field==='wall'?['cream','sage','rose','night','mist']:d.field==='floor'?['oak','walnut','light','tile','stone']:[];if(styles[id]&&allowed.includes(d.value)){const prior=styles[id][d.field];styles[id][d.field]=d.value;try{await persist(true);}catch(err){styles[id][d.field]=prior;throw err;}for(const g of gardenInstances)g.update();roomStyle054();}return true;}
 if(name==='space-shop057'){UI.shopInterior057=currentSpace057();UI.shopDestination054=true;UI.shopTab=UI.shopInterior057==='greenhouse'?'interior057':'home';UI.interiorFilter057='greenhouse';closeSheet();route('shop');return true;}
 if(name==='shop-tab'&&collectionList057[d.tab]||name==='collection-open057'&&collectionList057[d.tab]){UI.shopTab=d.tab;UI.interiorFilter057='all';closeSheet();route('shop');return true;}
 if(name==='interior-filter057'){if(['all','greenhouse','kitchen','bathroom'].includes(d.filter)){UI.interiorFilter057=d.filter;render();}return true;}
 if(name==='haven-detail057'){havenDetail057(d.item);return true;}
 if(name==='haven-buy057'){if(DECOR[d.item]){await buyItem('decor',d.item);if(owns('decor',d.item))closeSheet();}return true;}
 if(['haven-place057','inventory-place057','sakura-place055','atelier-place056'].includes(name)||name==='place-owned'&&DECOR[d.item]?.group!=='pots'){destinationSheet057(d.type||'decor',d.item);return true;}
 if(name==='move-room057'){const p=livingPlacements().find(x=>x.key===UI.selectedLiving);if(p)destinationSheet057(p.type,p.item);return true;}
 if(name==='place-destination057'){if(d.space==='garden'||SPACES057[d.space]){UI.pendingSpace057=d.space;await placeOwned(d.type||'decor',d.item);}return true;}
 if(name==='living-nudge'){const p=livingPlacements().find(x=>x.key===UI.selectedLiving);if(!p||itemSpace057(p)!==currentSpace057())return true;}
 return havenAction056(name,el,e);
};
// A modal is a separate layer from all fixed content in #screen. Hide the bulk
// action bar while it is open and make the background unavailable to keyboard.
const sheetBefore057=sheet,closeBefore057=closeSheet;
sheet=function(...args){sheetBefore057(...args);if(UI.overlay){$('#screen')?.setAttribute('inert','');$('#navigation')?.setAttribute('inert','');}};
closeSheet=function(){const blocked=typeof pdfView!=='undefined'&&pdfView?.exporting;if(!blocked){$('#screen')?.removeAttribute('inert');$('#navigation')?.removeAttribute('inert');}closeBefore057();};
