/* Study methods, pause-safe timers, rest cycles, atomic rewards before animation. */
function methodInfo(){return STUDY_METHODS[S.preferences.method]||STUDY_METHODS.custom;}
function nextBreakMinutes(session){
 if(S.preferences.method==='flow'&&S.preferences.flowAutoRest!==false)return Math.round(clamp((session?.completedSeconds||0)/60/5,3,30));
 return S.preferences.method==='pomodoro'&&S.practice.cycle>0&&S.practice.cycle%S.preferences.rounds===0?S.preferences.longBreakMinutes:S.preferences.breakMinutes;
}
function currentClock(){const t=S.timer;if(!t)return S.preferences.method==='flow'?'00:00':clock(S.preferences.focusMinutes*60);return t.flow?clock(Math.floor((t.totalSeconds*1000-remainingMs(t))/1000)):clock(remaining(t));}
function focusScene(){return S.preferences.theme==='garden'?livingHost('focus-garden',true):'<div class="lava-host focus-lava"></div>';}
renderFocus=function(){const t=S.timer,rest=t?.phase==='break',running=t?.status==='running',method=methodInfo(),style=S.preferences.timerStyle||'simple';
 const counter=`<div class="clock-face clock-${style} ${rest?'rest-clock':''}" aria-label="${rest?'Mola':'Çalışma'} sayacı"><div id="timer-digits" aria-live="off">${currentClock()}</div></div>`;
 if(UI.immersive)return `<section class="focus-cinema ${UI.cinemaControls?'show-controls':''}">${focusScene()}<div class="cinema-shade"></div><button class="cinema-tap" data-action="cinema-controls" aria-label="Sayaç kontrollerini göster">${counter}</button><div class="cinema-controls" ${UI.cinemaControls?'':'inert'}><button class="icon-btn" data-action="immersive" aria-label="Tam ekrandan çık">${icon('shrink')}</button><button class="icon-btn" data-action="focus-toggle" aria-label="${running?'Duraklat':'Başlat'}">${icon(running?'pause':'play')}</button><button class="icon-btn" data-action="finish-partial" aria-label="Bitir ve kaydet">${icon('check')}</button><button class="icon-btn" data-action="clock-style" aria-label="Sayaç görünümü">${icon('sliders')}</button><button class="icon-btn" data-action="rotate-focus" aria-label="Yatay veya dikey ekran">${icon('expand')}</button></div></section>`;
 return `<div class="page focus-page focus05">${header()}<div class="section-heading"><div><span class="eyebrow">${rest?'BİRAZ NEFES':'TEK BİR ŞEY'}</span><h1>${rest?'Mola':'Odak'}</h1></div><button class="round-link" data-action="focus-options">${icon('sliders',17)}</button></div><section class="focus-card05">${focusScene()}<div class="focus-card-shade"></div><button class="focus-expand" data-action="immersive" aria-label="Tam ekran">${icon('expand',19)}</button><span class="method-eyebrow">${rest?'DİNLENME ZAMANI':method.name.toLocaleUpperCase('tr-TR')}</span>${counter}<span class="focus-intention">${esc(t?.title||getNote(UI.selectedNote)?.title||'Kendi ritminde.')}</span><div class="focus-buttons05"><button class="icon-btn" data-action="finish-partial" aria-label="Bitir ve kaydet" ${t?'':'disabled'}>${icon('check')}</button><button class="focus-start05" data-action="focus-toggle">${icon(running?'pause':'play',23)}${running?'Duraklat':t?'Devam et':'Başla'}</button><button class="icon-btn" data-action="clock-style" aria-label="Sayaç tipi">${icon('sliders')}</button></div>${!rest?`<span class="coin-rate">${coinIcon(15)} <span id="session-coins">${t?Math.floor((t.totalSeconds*1000-remainingMs(t))/20000):0}</span> jeton</span>`:''}</section><button class="method-summary" data-action="method-picker"><span>${icon('focus',19)}<b>${method.name}${S.preferences.method!=='flow'&&S.preferences.method!=='custom'&&(method.work!==S.preferences.focusMinutes||method.rest!==S.preferences.breakMinutes)?' · kişisel':''}</b></span><span>${S.preferences.method==='flow'?'Serbest süre':S.preferences.focusMinutes+' / '+S.preferences.breakMinutes+' dk'} ${icon('chevron',15)}</span></button>${S.preferences.method==='pomodoro'?`<div class="pomodoro-dots" aria-label="${S.practice.cycle%S.preferences.rounds} tur tamamlandı">${Array.from({length:S.preferences.rounds},(_,i)=>`<i class="${i<S.practice.cycle%S.preferences.rounds?'done':''}"></i>`).join('')}</div>`:''}<div class="focus-secondary"><button data-action="focus-intent">${icon('note',18)} Bir hedef seç</button><button data-action="mixer">${icon('headphones',18)} Sesler</button></div>${S.practice.pending&&!t?`<button class="btn ghost full" data-action="next-phase">${S.practice.pending.phase==='break'?S.practice.pending.minutes+' dk mola':'Yeni çalışma turu'} ${icon('arrow',16)}</button>`:''}<button class="weekly-link" data-action="route" data-route="weekly">${icon('calendar',19)} Haftalık ilerleme ${icon('arrow',16)}</button></div>`;
};
function methodPicker(){sheet('Çalışma ritmin',`<div class="method-grid">${Object.entries(STUDY_METHODS).map(([key,m])=>`<button class="method-card ${S.preferences.method===key?'selected':''}" data-action="choose-method" data-method="${key}"><span>${icon(m.icon,22)}</span><strong>${m.name}</strong><small>${key==='flow'?'Açık uçlu':m.work+' dk · '+m.rest+' dk mola'}</small><p>${m.tip}</p></button>`).join('')}</div><button class="btn ghost full" data-action="study-settings">Süreleri düzenle</button>`,'methods');}
function studySettings(){sheet('Çalışma ve mola',`<form id="study-settings"><div class="two-fields"><label class="field"><span>Çalışma · dakika</span><input name="work" type="number" min="1" max="720" value="${S.preferences.focusMinutes}" required></label><label class="field"><span>Kısa mola</span><input name="rest" type="number" min="1" max="120" value="${S.preferences.breakMinutes}" required></label><label class="field"><span>Uzun mola</span><input name="long" type="number" min="1" max="120" value="${S.preferences.longBreakMinutes}" required></label><label class="field"><span>Uzun molaya kadar tur</span><input name="rounds" type="number" min="1" max="12" value="${S.preferences.rounds}" required></label></div>${S.preferences.method==='flow'?`<label class="check-label"><input type="checkbox" name="flowAutoRest" ${S.preferences.flowAutoRest!==false?'checked':''}> Flowtime molasını çalışma süreme göre öner</label>`:''}<label class="check-label"><input type="checkbox" name="autoBreak" ${S.preferences.autoBreak?'checked':''}> Molayı otomatik başlat</label><label class="check-label"><input type="checkbox" name="autoFocus" ${S.preferences.autoFocus?'checked':''}> Moladan sonra çalışmayı otomatik başlat</label><button class="btn primary full" type="submit">Kaydet</button><p class="hint">Varsayılan olarak yeni çalışma sen başlatana kadar bekler.</p></form>`,'study-settings');}
focusOptions=function(){sheet('Odak ayarları',`<div class="note-menu"><button data-action="method-picker">${icon('focus')} Çalışma yöntemi</button><button data-action="study-settings">${icon('calendar')} Çalışma ve mola süreleri</button><button data-action="clock-style">${icon('sliders')} Sayaç görünümü</button><button data-action="living-weather">${icon('leaf')} Bahçemi arka plan yap</button><button data-action="mixer">${icon('headphones')} Ses karışımı</button></div><section class="card flat">${toggleMarkup('keepAwake','Ekran açık kalsın','')}${toggleMarkup('notifications','Bitişi haber ver','Telefon izni gerekir.')}${toggleMarkup('soundWithFocus','Çalışırken sesleri aç','')}${toggleMarkup('finishSound','Bitişte çan çalsın','')}</section>${S.timer?'<button class="btn primary full" data-action="finish-partial">Bitir ve kaydet</button>':''}`,'focus-options');};
const startFocus04=startFocus;
startFocus=async function(minutes,meta={}){const isRest=meta.phase==='break',flow=!isRest&&S.preferences.method==='flow';
 const before=S.timer?.id;const result=await startFocus04(flow?720:minutes,{...meta,title:meta.title||UI.focusIntention||''});
 if(S.timer&&S.timer.id!==before){UI.gardenFull=false;UI.gardenRoom=false;S.timer.flow=flow;S.timer.method=S.preferences.method;S.practice.pending=null;await persist(true);if(flow){await Native.call('cancelTimer').catch(()=>{});}render();}return result;};
const endFocus04=endFocus;
let rewardBusy=false;
endFocus=async function(completed=true,show=true){const previous=S.timer?{...S.timer}:null;if(!previous||finishingSession===previous.id||rewardBusy)return;const oldBalance=wallet(),oldCycle=S.practice.cycle;
 const session=await endFocus04(completed,false);if(!session)return;
 if(previous.phase==='break'){
  S.practice.pending={phase:'focus',minutes:S.preferences.focusMinutes};await persist(true);await ringStudyBell();
  if(S.preferences.autoFocus)await startFocus(S.preferences.focusMinutes);else breakCompleteSheet();return session;
 }
 if(session.completedSeconds>0){
  S.living.bonds[S.preferences.companion]=(S.living.bonds[S.preferences.companion]||0)+session.completedSeconds;
  if(session.completed||previous.flow)S.practice.cycle=oldCycle+1;queueGrowth();
  S.practice.pending={phase:'break',minutes:nextBreakMinutes(session)};await persist(true);
 }
 if(show&&session.completedSeconds>0){rewardBusy=true;try{closeSheet();await coinCelebration(session.coinsAwarded||0,oldBalance,wallet());await ringStudyBell();
  if(S.preferences.autoBreak)await startFocus(S.practice.pending?.minutes||S.preferences.breakMinutes,{phase:'break',title:'Biraz nefes'});else completionSheet(session);
 }finally{rewardBusy=false;}}
 return session;
};
completionSheet=function(s){UI.lastSession=s.id;sheet('Küçük bir zafer',`<div class="completion result05">${pixel(S.preferences.companion,90)}<h2>Güzel çalıştın.</h2><div class="result-numbers"><span>${Math.round(s.completedMinutes*10)/10}<small>dakika</small></span><span>${coinIcon(22)} ${s.coinsAwarded||0}<small>jeton</small></span></div><p>${S.world.plots.some(p=>p&&plantProgress(p)>=1)?'Bir bitkin bahçeye taşınmaya hazır.':'Şimdi kısa bir nefes.'}</p></div><button class="btn primary full" data-action="next-phase">${S.practice.pending?.minutes||S.preferences.breakMinutes} dk mola ${icon('play',16)}</button><div class="actions"><button class="btn ghost" data-action="completion-garden">Bahçeme git</button><button class="btn ghost" data-action="close">Şimdilik bitti</button></div>`,'completion');};
function breakCompleteSheet(){sheet('Molan tamamlandı',`<div class="completion result05">${pixel(S.preferences.companion,86)}<h2>Hazır olduğunda.</h2><p>Yeni tur seni bekliyor.</p></div><button class="btn primary full" data-action="next-phase">Çalışmaya dön ${icon('play',17)}</button><button class="text-btn full" data-action="close">Biraz daha dinlen</button>`,'break-complete');}
async function ringStudyBell(){if(S.preferences.finishSound===false)return;try{await Native.call('studyBell');}catch{/* Timer correctness never depends on sound permission. */}}
function coinCelebration(amount,before,after){return new Promise(resolve=>{
 if(amount<=0){resolve();return;}const reduced=document.body.classList.contains('no-motion');
 const layer=document.createElement('div');layer.className='coin-celebration';layer.setAttribute('role','status');layer.setAttribute('aria-label',amount+' jeton kazanıldı');
 layer.innerHTML=`<div class="reward-wallet">${coinIcon(22)}<b>${before}</b></div><div class="flying-coin">${coinIcon(104)}</div><strong class="reward-amount">+${amount}</strong><span class="reward-caption">Çalışman kaydedildi</span>`;document.body.append(layer);
 const targets=$$('[data-wallet]');targets.forEach(n=>n.textContent=String(before));
 let done=false;const finish=()=>{if(done)return;done=true;targets.forEach(n=>n.textContent=String(after));layer.remove();resolve();};
 setTimeout(()=>{if(!layer.isConnected)return;const coin=$('.flying-coin',layer),dest=$('.wallet-chip')||$('.reward-wallet',layer),box=dest.getBoundingClientRect();
  coin.style.setProperty('--fly-x',(box.left+box.width/2-window.innerWidth/2)+'px');coin.style.setProperty('--fly-y',(box.top+box.height/2-window.innerHeight/2)+'px');layer.classList.add('fly');
  const start=performance.now();function count(now){const q=Math.min(1,(now-start)/450),v=Math.round(before+(after-before)*q);targets.forEach(n=>n.textContent=String(v));$('.reward-wallet b',layer).textContent=String(v);if(q<1&&layer.isConnected)requestAnimationFrame(count);}setTimeout(()=>requestAnimationFrame(count),reduced?0:500);
 },reduced?100:1100);setTimeout(finish,reduced?650:2350);
 });}
let cinemaHide;
function showCinemaControls(){UI.cinemaControls=true;$('.focus-cinema')?.classList.add('show-controls');$('.cinema-controls')?.removeAttribute('inert');clearTimeout(cinemaHide);cinemaHide=setTimeout(()=>{if(UI.overlay)return;UI.cinemaControls=false;$('.focus-cinema')?.classList.remove('show-controls');$('.cinema-controls')?.setAttribute('inert','');},3300);}
