/* On-device PDF canvas. Libraries are bundled at setup, never loaded from a CDN
   by the app. Originals stay untouched; export is an explicitly rasterized copy. */
let pdfLibrariesPromise=null,pdfView=null;
function ensurePdfLibraries(){if(!pdfLibrariesPromise)pdfLibrariesPromise=(async()=>{
 if(!window.LUMA_PDF_MODULE||!window.PDFLib)throw new Error('PDF bileşenleri henüz hazırlanmadı. Mac’te BASLAT.command ile kurulumu tamamla. Orijinal PDF ve notların korunuyor.');
 if(!Promise.withResolvers)Promise.withResolvers=function(){let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return{promise,resolve,reject};};
 const url=URL.createObjectURL(new Blob([window.LUMA_PDF_MODULE],{type:'text/javascript'}));
 let lib;try{lib=await import(url);}finally{URL.revokeObjectURL(url);}
 lib.GlobalWorkerOptions.workerSrc=URL.createObjectURL(new Blob([window.LUMA_PDF_WORKER],{type:'text/javascript'}));return lib;
 })().catch(e=>{pdfLibrariesPromise=null;throw e;});return pdfLibrariesPromise;}
const attachmentBeforeLiving=openAttachment;
openAttachment=async function(id){const a=getNote(UI.editorId)?.attachments.find(x=>x.id===id);if(a?.type==='pdf'){if(!safeKey(a.id)){toast('PDF kimliği geçersiz. Dosyayı yeniden ekle.');return;}return openPdf(a);}return attachmentBeforeLiving(id);};
function pdfPageData(){if(!pdfView)return null;const n=getNote(pdfView.noteId);if(!n)return null;n.pdfInk=n.pdfInk||{};const all=n.pdfInk[pdfView.file.id]||(n.pdfInk[pdfView.file.id]={});const raw=all[pdfView.page]||(all[pdfView.page]={strokes:[],texts:[]});pdfView.cleanedPages=pdfView.cleanedPages||new Set();if(pdfView.cleanedPages.has(pdfView.page))return raw;pdfView.cleanedPages.add(pdfView.page);raw.strokes=normalizeInk(raw.strokes);raw.texts=(Array.isArray(raw.texts)?raw.texts:[]).filter(t=>t&&typeof t.text==='string').slice(0,100).map(t=>({...t,text:t.text.slice(0,2000),x:clamp(t.x,0,1),y:clamp(t.y,0,1),color:/^#[a-f0-9]{6}$/i.test(t.color)?t.color:'#624590'}));return raw;}
async function openPdf(file){flushEditor();const noteId=UI.editorId;closeSheet();sheet(file.name,'<div class="empty">PDF hazırlanıyor…</div>','pdf-loading');try{
 const lib=await ensurePdfLibraries();const base64=await Native.call('readDocument',{uri:file.uri});if(UI.overlay!=='pdf-loading'||UI.editorId!==noteId)return;
 const bytes=Uint8Array.from(atob(base64),c=>c.charCodeAt(0));if(bytes.length>25*1024*1024)throw new Error('PDF en fazla 25 MB olabilir.');
 const task=lib.getDocument({data:bytes,disableFontFace:true,useSystemFonts:true,useWasm:false,isEvalSupported:false,stopAtErrors:true,disableAutoFetch:true});
 task.onPassword=()=>{task.destroy();toast('Şifre korumalı PDF için önce şifresiz bir çalışma kopyası oluştur.');};
 const doc=await task.promise;if(doc.numPages>200){await doc.destroy();throw new Error('PDF çalışma alanı en fazla 200 sayfa destekliyor. Belgeyi bölerek ekle.');}
 if(UI.overlay!=='pdf-loading'||UI.editorId!==noteId){await doc.destroy();return;}
 closeSheet();pdfView={file,noteId,doc,page:1,zoom:1,tool:'hand',renderToken:0,renderTask:null,active:null,redo:[],pendingText:null};
 sheet(file.name,`<div class="pdf-toolbar"><button class="icon-btn" data-action="pdf-prev" aria-label="Önceki sayfa">${icon('back')}</button><span id="pdf-page-count"></span><button class="icon-btn" data-action="pdf-next" aria-label="Sonraki sayfa">${icon('arrow')}</button><button class="icon-btn" data-action="pdf-zoom-out" aria-label="Uzaklaştır">−</button><button class="icon-btn" data-action="pdf-zoom-in" aria-label="Yakınlaştır">+</button></div><div class="pdf-tools">${[['hand','Gezin'],['pen','Kalem'],['highlight','Vurgula'],['erase','Silgi']].map(([k,n])=>`<button data-action="pdf-tool" data-tool="${k}" class="${k==='hand'?'active':''}">${n}</button>`).join('')}<input type="color" id="pdf-color" value="#7e51a2" aria-label="PDF kalem rengi"><button data-action="pdf-text">Aa</button><button data-action="pdf-undo" aria-label="Son işareti geri al">${icon('undo',16)}</button></div><div id="pdf-text-entry" class="hidden"><input id="pdf-text-value" maxlength="500" placeholder="Notunu yaz; sayfada konumuna dokun"><button data-action="pdf-place-text">Yerleştir</button></div><div class="pdf-scroll"><div class="pdf-stack"><canvas id="pdf-page"></canvas><canvas id="pdf-ink"></canvas></div></div><button class="btn ghost full" data-action="pdf-export">İşaretli kopyayı PDF olarak paylaş</button><p class="hint pdf-hint">Orijinal korunur. Dışa aktarılan kopya sayfa görüntülerinden oluşur; metin arama ve bağlantılar korunmaz.</p>`,'pdf');
 $('.sheet').classList.add('pdf-sheet');bindPdfInk();syncPdfTool();await renderPdfPage();
 }catch(e){if(UI.overlay==='pdf-loading')closeSheet();toast('PDF açılamadı: '+e.message,9000);}}
function disposePdfView(){if(!pdfView)return;const v=pdfView;pdfView=null;v.renderToken++;v.renderTask?.cancel();v.doc.destroy().catch(()=>{});persist();}
async function renderPdfPage(){const v=pdfView;if(!v)return;const token=++v.renderToken;v.renderTask?.cancel();v.active=null;
 try{const page=await v.doc.getPage(v.page);if(pdfView!==v||token!==v.renderToken)return;const normal=page.getViewport({scale:1}),scale=Math.min(2,1200/normal.width),view=page.getViewport({scale});const c=$('#pdf-page'),ink=$('#pdf-ink'),stack=$('.pdf-stack');if(!c)return;
 c.width=ink.width=Math.ceil(view.width);c.height=ink.height=Math.ceil(view.height);stack.style.width=v.zoom*100+'%';stack.style.aspectRatio=view.width+'/'+view.height;$('#pdf-page-count').textContent=v.page+' / '+v.doc.numPages;
 v.renderTask=page.render({canvasContext:c.getContext('2d'),canvas:c,viewport:view,background:'white'});await v.renderTask.promise;if(pdfView!==v||token!==v.renderToken)return;paintPdfInk();
 }catch(e){if(e.name!=='RenderingCancelledException')toast('Sayfa görüntülenemedi: '+e.message,7000);}}
function paintPdfInk(){if(!pdfView)return;const c=$('#pdf-ink');if(!c)return;drawPdfOverlay(c.getContext('2d'),pdfPageData(),c.width,c.height);}
function drawPdfOverlay(ctx,data,w,h){drawStrokes(ctx,data?.strokes||[],w,h);for(const t of data?.texts||[]){ctx.fillStyle=t.color;ctx.font=Math.max(13,w/50)+'px -apple-system,BlinkMacSystemFont,sans-serif';ctx.textBaseline='top';const max=w*(1-t.x)-8,lines=String(t.text).split('\n');let y=t.y*h;for(const line of lines){let current='';for(const word of line.split(' ')){const next=current?current+' '+word:word;if(ctx.measureText(next).width>max&&current){ctx.fillText(current,t.x*w,y);y+=w/40;current=word;}else current=next;}ctx.fillText(current,t.x*w,y);y+=w/40;}}}
function bindPdfInk(){const c=$('#pdf-ink'),point=e=>{const r=c.getBoundingClientRect();return[clamp((e.clientX-r.left)/r.width,0,1),clamp((e.clientY-r.top)/r.height,0,1)];};
 c.addEventListener('pointerdown',e=>{const v=pdfView;if(!v||v.tool==='hand'||v.active)return;e.preventDefault();c.setPointerCapture(e.pointerId);const p=point(e),data=pdfPageData();
 if(v.tool==='text'&&v.pendingText){data.texts.push({id:uid(),text:v.pendingText,x:p[0],y:p[1],color:$('#pdf-color').value});v.pendingText=null;v.tool='hand';syncPdfTool();paintPdfInk();persist();return;}
 if(v.tool==='erase'){data.strokes=data.strokes.filter(s=>!s.points.some(q=>Math.hypot(q[0]-p[0],q[1]-p[1])<.04));data.texts=data.texts.filter(t=>Math.hypot(t.x-p[0],t.y-p[1])>.06);paintPdfInk();persist();return;}
 const s={id:uid(),points:[p],color:$('#pdf-color').value,width:v.tool==='highlight'?16:3,tool:v.tool==='highlight'?'highlight':'pen'};data.strokes.push(s);v.active={pointer:e.pointerId,stroke:s,page:v.page};v.redo=[];paintPdfInk();});
 c.addEventListener('pointermove',e=>{const v=pdfView;if(!v?.active||v.active.pointer!==e.pointerId)return;e.preventDefault();for(const ev of e.getCoalescedEvents?.()||[e])v.active.stroke.points.push(point(ev));paintPdfInk();});
 const end=()=>{if(pdfView){pdfView.active=null;persist();}};c.addEventListener('pointerup',end);c.addEventListener('pointercancel',end);}
function syncPdfTool(){if(!pdfView)return;const c=$('#pdf-ink');c.style.pointerEvents=pdfView.tool==='hand'?'none':'auto';c.style.touchAction=pdfView.tool==='hand'?'auto':'none';$$('[data-action="pdf-tool"]').forEach(b=>b.classList.toggle('active',b.dataset.tool===pdfView.tool));}
async function exportAnnotatedPdf(){const v=pdfView;if(!v||v.exporting)return;v.exporting=true;const b=$('[data-action="pdf-export"]');b.disabled=true;b.textContent='Kopya hazırlanıyor…';try{
 await persist(true);const result=await PDFLib.PDFDocument.create(),n=getNote(v.noteId);for(let i=1;i<=v.doc.numPages;i++){const page=await v.doc.getPage(i),raw=page.getViewport({scale:1}),vp=page.getViewport({scale:Math.min(2,1300/raw.width)}),c=document.createElement('canvas');c.width=Math.ceil(vp.width);c.height=Math.ceil(vp.height);const ctx=c.getContext('2d');await page.render({canvasContext:ctx,canvas:c,viewport:vp,background:'white'}).promise;
 const ink=document.createElement('canvas');ink.width=c.width;ink.height=c.height;drawPdfOverlay(ink.getContext('2d'),n.pdfInk?.[v.file.id]?.[i],c.width,c.height);ctx.drawImage(ink,0,0);const image=await result.embedJpg(c.toDataURL('image/jpeg',.88));result.addPage([raw.width,raw.height]).drawImage(image,{x:0,y:0,width:raw.width,height:raw.height});c.width=c.height=ink.width=ink.height=1;
 if(i%3===0)await new Promise(r=>setTimeout(r,20));if(i%10===0)b.textContent=i+' / '+v.doc.numPages+' sayfa';}
 const base64=await result.saveAsBase64();if(base64.length>35*1024*1024)throw new Error('İşaretli kopya çok büyük; PDF’yi bölerek dışa aktar.');await Native.call('exportBinary',{base64,name:v.file.name.replace(/\.pdf$/i,'')+'-isaretli.pdf',mimeType:'application/pdf'});toast('İşaretli kopya hazır. Orijinal değiştirilmedi.');
 }finally{v.exporting=false;if(b.isConnected){b.disabled=false;b.textContent='İşaretli kopyayı PDF olarak paylaş';}}}
async function pdfAction(name,el){if(!name.startsWith('pdf-'))return false;const v=pdfView;if(!v)return true;if(name==='pdf-prev'||name==='pdf-next'){v.page=clamp(v.page+(name==='pdf-next'?1:-1),1,v.doc.numPages);await renderPdfPage();}if(name==='pdf-zoom-in'||name==='pdf-zoom-out'){v.zoom=clamp(v.zoom+(name==='pdf-zoom-in'?.25:-.25),1,3);$('.pdf-stack').style.width=v.zoom*100+'%';}if(name==='pdf-tool'){v.tool=el.dataset.tool;syncPdfTool();}if(name==='pdf-undo'){const d=pdfPageData();d.strokes.pop();paintPdfInk();persist();}if(name==='pdf-text')$('#pdf-text-entry').classList.toggle('hidden');if(name==='pdf-place-text'){v.pendingText=$('#pdf-text-value').value.trim();if(v.pendingText){v.tool='text';syncPdfTool();$('#pdf-text-entry').classList.add('hidden');toast('Sayfada notunun yerini seç.');}}if(name==='pdf-export')await exportAnnotatedPdf();return true;}
