/* Simple note list, reversible trash, fixed add button, paper and vector ink. */
renderNotes=function(){return `<div class="page notes05">${header()}<div class="section-heading"><h1>${UI.trash?'Çöp kutusu':UI.archived?'Arşiv':'Notlar'}</h1><button class="icon-btn clear" data-action="notes-filter" aria-label="Notları filtrele">${icon('sliders')}</button></div><label class="note-search05">${icon('search',18)}<input id="note-search" value="${esc(UI.query)}" placeholder="Notlarında ara" aria-label="Notlarında ara"></label>${UI.category!=='Tümü'||UI.trash||UI.archived?`<button class="filter-tag" data-action="notes-reset">${esc(UI.trash?'Çöp kutusu':UI.archived?'Arşiv':UI.category)} ${icon('close',13)}</button>`:''}<div id="notes-results">${renderNoteResults()}</div>${!UI.trash?`<button class="note-fab05" data-action="new-note" aria-label="Yeni not ekle">${icon('plus',27)}</button>`:''}</div>`;};
renderNoteResults=function(){const notes=filteredNotes().sort((a,b)=>Number(b.pinned)-Number(a.pinned));return notes.length?`<div class="note-list05">${notes.map(n=>`<article class="note-row05" data-note-id="${esc(n.id)}"><button class="note-open05" data-action="${UI.trash?'restore-note':'edit-note'}" data-id="${esc(n.id)}"><span class="note-color05" style="--swatch:${esc(/^#[0-9a-f]{6}$/i.test(n.color)?n.color:'#bba5d7')}"></span><span class="grow"><strong>${n.pinned?icon('pin',12):''}${esc(n.title||'Başlıksız not')}</strong><span class="note-preview05">${esc(n.plainText||n.ink?.length&&'El yazısı'||n.attachments?.length&&'Ekli belge'||'Boş sayfa')}</span><small>${esc(fmtDate(n.updatedAt))}${n.attachments?.length?' · '+n.attachments.length+' ek':''}</small></span></button><button class="icon-btn clear note-overflow05" data-action="note-card-menu" data-id="${esc(n.id)}" aria-label="${esc(n.title||'Not')} seçenekleri">${icon('more',19)}</button></article>`).join('')}</div>`:`<div class="notes-empty05">${icon('note',34)}<h3>${UI.query?'Eşleşen not yok':'Düşüncelerine yer aç.'}</h3><p>${UI.query?'Başka bir kelime dene.':'Sağ alttaki + ile hemen yaz.'}</p></div>`;};
function noteCardMenu(id){const n=getNote(id);if(!n)return;UI.cardNote=id;sheet(n.title||'Başlıksız not',`<div class="note-menu">${n.deletedAt?`<button data-action="restore-note" data-id="${esc(id)}">${icon('undo')} Geri getir</button><button data-action="purge-note" data-id="${esc(id)}">${icon('trash')} Kalıcı sil</button>`:`<button data-action="card-pin" data-id="${esc(id)}">${icon('pin')} ${n.pinned?'Sabitlemeyi kaldır':'Sabitle'}</button><button data-action="card-duplicate" data-id="${esc(id)}">${icon('note')} Çoğalt</button><button class="danger" data-action="card-trash" data-id="${esc(id)}">${icon('trash')} Çöp kutusuna taşı</button>`}</div>`,'note-card');}
let notePress=null,noteIgnoreClick=0;
document.addEventListener('pointerdown',e=>{const row=e.target.closest?.('[data-note-id]');if(!row||e.target.closest('.note-overflow05'))return;notePress={x:e.clientX,y:e.clientY,id:row.dataset.noteId,timer:setTimeout(()=>{if(!notePress)return;noteIgnoreClick=Date.now()+700;beginNoteSelection054(notePress.id);notePress=null;},520)};});
function cancelNotePress(){if(notePress){clearTimeout(notePress.timer);notePress=null;}}
document.addEventListener('pointermove',e=>{if(notePress&&Math.hypot(e.clientX-notePress.x,e.clientY-notePress.y)>9)cancelNotePress();});
document.addEventListener('pointerup',cancelNotePress);document.addEventListener('pointercancel',cancelNotePress);
document.addEventListener('click',e=>{if(Date.now()<noteIgnoreClick&&e.target.closest?.('[data-note-id]')){e.preventDefault();e.stopImmediatePropagation();}},true);
document.addEventListener('contextmenu',e=>{const row=e.target.closest?.('[data-note-id]');if(row){e.preventDefault();cancelNotePress();beginNoteSelection054(row.dataset.noteId);}});
async function trashFromList(id){const n=getNote(id);if(!n)return;const previous=n.deletedAt;n.deletedAt=new Date().toISOString();try{await persist(true);}catch(e){n.deletedAt=previous;throw e;}UI.lastTrashed=id;closeSheet();render();
 const toastNode=$('#toast');toast('Not çöp kutusuna taşındı.',6000);const b=document.createElement('button');b.textContent='Geri al';b.className='toast-undo';b.dataset.action='undo-trash';b.dataset.id=id;toastNode.append(' ',b);
}
function notesFilter(){sheet('Notlar',`<div class="chips">${['Tümü',...S.preferences.categories].map(c=>`<button class="chip ${UI.category===c?'active':''}" data-action="note-category" data-category="${esc(c)}">${esc(c)}</button>`).join('')}</div><div class="note-menu"><button data-action="notes-favorites">${icon('star')} Favoriler</button><button data-action="open-archive">${icon('archive')} Arşiv</button><button data-action="open-trash">${icon('trash')} Çöp kutusu</button><button data-action="note-templates">${icon('grid')} Şablonla başla</button></div>`,'notes-filter');}
const openEditor04=openEditor;
openEditor=function(id){destroyGardens();openEditor04(id);const n=getNote(id);if(!n)return;
 const tools=$('.editor-tools');if(tools)tools.innerHTML=`<div class="note-toolbar05"><button data-action="writing-tools">Aa <span>Yazı</span></button><button data-action="open-ink">${icon('edit',19)}<span>Kalem</span></button><button data-action="note-insert">${icon('plus',19)}<span>Ekle</span></button><button data-action="note-paper">${icon('note',19)}<span>Kâğıt</span></button><button data-format="undo" aria-label="Geri al">${icon('undo',18)}</button><button data-format="redo" aria-label="Yinele">${icon('redo',18)}</button></div>`;
 n.paper=normalizePaper(n.paper);n.ink=normalizeInk(n.ink);applyNotePaper(n);renderInkPreview();};
async function applyNotePaper(n){const page=$('.editor-scroll');if(!page)return;const paper=normalizePaper(n.paper);page.dataset.paper=paper.kind;page.style.setProperty('--paper-opacity',paper.opacity);
 page.style.removeProperty('--paper-image');if(paper.kind==='image'){const file=n.attachments.find(a=>a.id===paper.imageId);if(file){try{const data=file.uri.startsWith('data:')?file.uri:await Native.call('readImage',{uri:file.uri});if(UI.editorId===n.id&&/^data:image\//.test(data))page.style.setProperty('--paper-image',`url("${data.replace(/["\\\n\r]/g,'')}")`);}catch(e){toast('Arka plan görseli açılamadı.');}}}
}
function paperSheet(){const n=getNote(UI.editorId);if(!n)return;sheet('Kâğıt',`<div class="paper-grid05">${[['dark','Nocturne'],['plain','Düz'],['grid','Kareli'],['ruled','Çizgili'],['dots','Noktalı']].map(([key,name])=>`<button data-action="set-paper" data-paper="${key}" class="${n.paper?.kind===key?'selected':''}"><i data-paper="${key}"></i>${name}</button>`).join('')}<button data-action="paper-image"><i>${icon('image',24)}</i>Galeriden</button></div><label class="field"><span>Fotoğraf görünürlüğü</span><input type="range" min="5" max="100" value="${Math.round((n.paper?.opacity||.24)*100)}" id="paper-opacity"></label>`,'note-paper');}
function writingTools(){captureRange();sheet('Yazı',`<div class="writing-controls"><button data-format="bold"><b>B</b></button><button data-format="italic"><i>I</i></button><button data-format="underline"><u>U</u></button><button data-format="insertUnorderedList">${icon('list')}</button><button data-action="insert-checklist">${icon('checkcircle')}</button></div><div class="writing-colors">${['#342f44','#eee7fa','#8657c1','#b44767','#356eac','#48826b','#ae7c25'].map(c=>`<button class="color-dot" style="--swatch:${c}" data-action="text-color" data-color="${c}" aria-label="${c} renk"></button>`).join('')}</div><button class="btn ghost full" data-action="insert-heading">Başlık ekle</button>`,'writing-tools');}
function noteInsert(){captureRange();sheet('Ekle',`<div class="note-menu"><button data-action="attach-image">${icon('image')} Fotoğraf</button><button data-action="attach-pdf">${icon('pdf')} PDF · çizim ve not</button><button data-action="table-options">${icon('grid')} Tablo</button><button data-action="insert-link">${icon('link')} Bağlantı</button><button data-action="note-templates">${icon('note')} Yeni not için şablon</button></div>`,'note-insert');}
function tableOptions(){sheet('Tablo',`<form id="table-form"><div class="two-fields"><label class="field"><span>Satır</span><input type="number" name="rows" min="1" max="20" value="3" required></label><label class="field"><span>Sütun</span><input type="number" name="cols" min="1" max="8" value="3" required></label></div><button class="btn primary full" type="submit">Tablo ekle</button></form>${UI.tableCell?.isConnected?'<div class="note-menu"><button data-action="table-add-row">Satır ekle</button><button data-action="table-add-col">Sütun ekle</button><button data-action="table-remove-row">Seçili satırı kaldır</button><button data-action="table-remove-col">Seçili sütunu kaldır</button></div>':''}`,'table');}
document.addEventListener('click',e=>{const cell=e.target.closest?.('#rich-editor td,#rich-editor th');if(cell)UI.tableCell=cell;});
function drawStrokes(ctx,strokes,w,h){ctx.clearRect(0,0,w,h);for(const s of strokes){if(!s.points.length)continue;ctx.beginPath();ctx.lineCap='round';ctx.lineJoin='round';ctx.lineWidth=s.width*w/760;ctx.strokeStyle=s.color;ctx.globalAlpha=s.tool==='highlight'?.3:1;s.points.forEach((p,i)=>i?ctx.lineTo(p[0]*w,p[1]*h):ctx.moveTo(p[0]*w,p[1]*h));if(s.points.length===1){ctx.lineTo(s.points[0][0]*w+.01,s.points[0][1]*h+.01);}ctx.stroke();}ctx.globalAlpha=1;}
let inkEditor=null;
function renderInkPreview(){const n=getNote(UI.editorId);$('.ink-preview05')?.remove();if(!n?.ink?.length)return;const b=document.createElement('button');b.className='ink-preview05';b.dataset.action='open-ink';b.setAttribute('aria-label','El yazısı sayfasını düzenle');const c=document.createElement('canvas');c.width=760;c.height=1050;b.append(c);$('#attachment-list')?.before(b);drawStrokes(c.getContext('2d'),n.ink,760,1050);}
function openInk(){flushEditor();const n=getNote(UI.editorId);if(!n)return;n.ink=normalizeInk(n.ink);sheet('El yazısı',`<div class="ink-toolbar05"><input id="ink-color" type="color" value="#7751a6" aria-label="Kalem rengi"><input id="ink-width" type="range" min="1" max="14" value="3" aria-label="Kalem kalınlığı"><button class="icon-btn" data-action="ink-undo" aria-label="Geri al">${icon('undo')}</button><button class="icon-btn" data-action="ink-redo" aria-label="Yinele">${icon('redo')}</button><button class="icon-btn" data-action="ink-eraser" aria-label="Silgi">⌫</button><button class="icon-btn" data-action="ink-highlight" aria-label="Fosforlu kalem">▰</button></div><div class="ink-scroll05"><div class="ink-paper05" data-paper="${n.paper?.kind==='dark'?'plain':n.paper?.kind||'plain'}"><canvas id="ink-canvas05" width="760" height="1050" aria-label="El yazısı çizim alanı"></canvas></div></div><button class="btn primary full" data-action="ink-done">Kaydet</button>`,'ink');
 $('.sheet')?.classList.add('ink-sheet05');inkEditor={noteId:n.id,strokes:JSON.parse(JSON.stringify(n.ink)),redo:[],active:null,erase:false,highlight:false};const c=$('#ink-canvas05'),ctx=c.getContext('2d');
 const paint=()=>drawStrokes(ctx,inkEditor?.strokes||[],760,1050);inkEditor.draw=paint;paint();
 const inkPaper=$('.ink-paper05');if(n.paper?.kind==='image'){inkPaper.style.setProperty('--paper-opacity',n.paper.opacity);const paperFile=n.attachments.find(a=>a.id===n.paper.imageId);if(paperFile)Promise.resolve(paperFile.uri.startsWith('data:')?paperFile.uri:Native.call('readImage',{uri:paperFile.uri})).then(data=>{if(inkPaper.isConnected&&typeof data==='string'&&/^data:image\//.test(data))inkPaper.style.setProperty('--paper-image',`url("${data.replace(/["\\\n\r]/g,'')}")`);}).catch(()=>toast('El yazısı arka planı açılamadı.'));}

 const pos=e=>{const r=c.getBoundingClientRect();return[clamp((e.clientX-r.left)/r.width,0,1),clamp((e.clientY-r.top)/r.height,0,1)];};
 c.addEventListener('pointerdown',e=>{if(!inkEditor||inkEditor.active)return;e.preventDefault();c.setPointerCapture(e.pointerId);const p=pos(e);if(inkEditor.erase){inkEditor.strokes=inkEditor.strokes.filter(s=>!s.points.some(q=>Math.hypot(q[0]-p[0],q[1]-p[1])<.035));paint();saveInkInMemory();return;}
  const s={id:uid(),points:[p],color:$('#ink-color').value,width:Number($('#ink-width').value),tool:inkEditor.highlight?'highlight':'pen'};inkEditor.active={id:e.pointerId,s};inkEditor.strokes.push(s);inkEditor.redo=[];paint();});
 c.addEventListener('pointermove',e=>{if(!inkEditor?.active||inkEditor.active.id!==e.pointerId)return;e.preventDefault();for(const ev of e.getCoalescedEvents?.()||[e])inkEditor.active.s.points.push(pos(ev));paint();});
 const up=e=>{if(!inkEditor?.active||inkEditor.active.id!==e.pointerId)return;inkEditor.active=null;saveInkInMemory();};c.addEventListener('pointerup',up);c.addEventListener('pointercancel',up);
}
function saveInkInMemory(){if(!inkEditor)return;const n=getNote(inkEditor.noteId);if(n){n.ink=JSON.parse(JSON.stringify(inkEditor.strokes));n.updatedAt=new Date().toISOString();persist();}}
async function closeInk(){saveInkInMemory();await persist(true);inkEditor=null;closeSheet();renderInkPreview();}
document.addEventListener('input',e=>{if(e.target.id==='paper-opacity'){const n=getNote(UI.editorId);if(n){n.paper.opacity=Number(e.target.value)/100;applyNotePaper(n);persist();}}});
