/* 0.5.4. Preserve the editor range before any toolbar focus change. Formatting
   runs synchronously in the click gesture; the palette never steals focus. */
let editorMark054=null,formatBusy054=false,bulkUndo054=null,bulkBusy054=false;
function nodePath054(node,root){const path=[];while(node&&node!==root){const parent=node.parentNode;if(!parent)return null;path.unshift(Array.prototype.indexOf.call(parent.childNodes,node));node=parent;}return node===root?path:null;}
function rangeValid054(r,ed){return !!(r&&ed&&ed.contains(r.startContainer)&&ed.contains(r.endContainer));}
captureRange=function(){const ed=$('#rich-editor'),sel=window.getSelection();if(!ed||!sel?.rangeCount)return;const r=sel.getRangeAt(0);if(!rangeValid054(r,ed))return;originalRange=r.cloneRange();editorMark054={id:UI.editorId,start:nodePath054(r.startContainer,ed),end:nodePath054(r.endContainer,ed),so:r.startOffset,eo:r.endOffset};updateWritingState054();};
function markedRange054(ed){if(editorMark054?.id!==UI.editorId)return null;try{const at=path=>path.reduce((n,i)=>n.childNodes[i],ed),a=at(editorMark054.start),b=at(editorMark054.end),r=document.createRange();r.setStart(a,Math.min(editorMark054.so,a.nodeType===3?a.length:a.childNodes.length));r.setEnd(b,Math.min(editorMark054.eo,b.nodeType===3?b.length:b.childNodes.length));return r;}catch{return null;}}
restoreRange=function(){const ed=$('#rich-editor');if(!ed)return false;const r=rangeValid054(originalRange,ed)?originalRange.cloneRange():markedRange054(ed);ed.focus({preventScroll:true});const s=window.getSelection();if(!s)return false;s.removeAllRanges();if(r)s.addRange(r);else{const end=document.createRange();end.selectNodeContents(ed);end.collapse(false);s.addRange(end);}return true;};
const oldFormat054=format;
format=function(command,value=null){if(!UI.editorId||formatBusy054)return;if(command==='undo'||command==='redo'){editorMark054=null;originalRange=null;applyEditorHistory(command==='undo'?-1:1);captureRange();return;}
 formatBusy054=true;try{pushEditorHistory();if(!restoreRange())return;try{document.execCommand('styleWithCSS',false,true);}catch{}
 const ok=document.execCommand(command,false,value);captureRange();flushEditor();pushEditorHistory();updateWritingState054();keepCaretVisible();if(!ok&&['foreColor','bold','italic','underline'].includes(command))toast('Metni seçip biçimi yeniden uygula.');
 }finally{formatBusy054=false;}
};
function writingPanel054(){return `<div id="writing-panel054" role="toolbar" aria-label="Yazı biçimi"><div class="format-row054"><button data-format="bold" aria-label="Kalın" aria-pressed="false"><b>B</b></button><button data-format="italic" aria-label="İtalik" aria-pressed="false"><i>I</i></button><button data-format="underline" aria-label="Altı çizili" aria-pressed="false"><u>U</u></button><button data-format="insertUnorderedList" aria-label="Madde işaretleri">${icon('list',19)}</button><button data-action="insert-checklist" aria-label="Kontrol listesi">${icon('checkcircle',19)}</button><button data-format="removeFormat" aria-label="Biçimi temizle">T̸</button><button data-action="writing-close054" aria-label="Yazı araçlarını kapat">${icon('close',17)}</button></div><div class="format-row054 palette054">${[['#392f45','Koyu'],['#eee7fa','Açık'],['#9666cf','Mor'],['#c3567b','Pembe'],['#438ac7','Mavi'],['#499779','Yeşil'],['#c79835','Altın']].map(([c,n])=>`<button class="color-dot" style="--swatch:${c}" data-action="text-color" data-color="${c}" aria-label="${n} yazı" aria-pressed="false"></button>`).join('')}<button data-action="text-color" data-color="default" class="color-auto054" aria-label="Kâğıda uygun varsayılan renk">A</button></div></div>`;}
writingTools=function(){captureRange();const tools=$('.editor-tools');if(!tools)return;const old=$('#writing-panel054');if(old)old.remove();else tools.insertAdjacentHTML('afterbegin',writingPanel054());tools.classList.toggle('writing-expanded054',!!$('#writing-panel054'));updateWritingState054();keepCaretVisible();};
function updateWritingState054(){if(!$('#writing-panel054'))return;for(const b of $$('[data-format]',$('#writing-panel054'))){let on=false;try{on=document.queryCommandState(b.dataset.format);}catch{}b.setAttribute('aria-pressed',String(on));}let color='';try{color=document.queryCommandValue('foreColor');}catch{}for(const b of $$('[data-action="text-color"]',$('#writing-panel054'))){const sample=document.createElement('span');sample.style.color=b.dataset.color;const probe=document.createElement('span');probe.style.color=color;b.setAttribute('aria-pressed',String(sample.style.color!==''&&sample.style.color===probe.style.color));}}
function isFormattingControl054(target){return target.closest?.('.note-toolbar05 button,#writing-panel054 button');}
// A real selection must be captured on pointerdown, not after the button has focus.
document.addEventListener('pointerdown',e=>{if(UI.editorId&&isFormattingControl054(e.target)){captureRange();if(e.cancelable)e.preventDefault();}},true);
document.addEventListener('mousedown',e=>{if(UI.editorId&&isFormattingControl054(e.target)&&e.cancelable)e.preventDefault();},true);
document.addEventListener('click',e=>{if(!UI.editorId)return;const b=e.target.closest?.('button');if(!b)return;let handled=true;const name=b.dataset.action,cmd=b.dataset.format;
 if(!cmd&&!['writing-tools','writing-close054','text-color','text-highlight','insert-checklist','insert-quote'].includes(name))return;
 e.preventDefault();e.stopImmediatePropagation();if(b.disabled)return;
 try{if(cmd)format(cmd);else if(name==='writing-tools')writingTools();else if(name==='writing-close054'){$('#writing-panel054')?.remove();$('.editor-tools')?.classList.remove('writing-expanded054');restoreRange();}else if(name==='text-color'){let color=b.dataset.color;if(color==='default')color=getComputedStyle($('#rich-editor')).color;format('foreColor',color);}else if(name==='text-highlight')format('hiliteColor','#d4b574');else if(name==='insert-quote')format('formatBlock','blockquote');else if(name==='insert-checklist')format('insertHTML','<div class="check-item"><input type="checkbox"><span>Yeni adım</span></div><p><br></p>');}catch(err){toast('Biçim uygulanamadı: '+err.message);}
},true);
const openEditor053Polish=openEditor;
openEditor=function(id){editorMark054=null;originalRange=null;UI.noteSelection054=null;openEditor053Polish(id);};
// Selection is temporary UI state, never part of the personal data backup.
function selection054(){return UI.noteSelection054 instanceof Set?UI.noteSelection054:null;}
function beginNoteSelection054(id){if(!getNote(id))return;closeSheet();UI.noteSelection054=new Set([id]);render();}
function visibleNotes054(){return filteredNotes().sort((a,b)=>Number(b.pinned)-Number(a.pinned));}
function endNoteSelection054(){UI.noteSelection054=null;render();}
function selectionBar054(){const set=selection054();if(!set)return '';return `<div class="bulk-bar054" role="toolbar" aria-label="Seçili notlar"><strong aria-live="polite">${set.size} seçili</strong>${UI.trash?`<button data-action="bulk-restore054" ${!set.size?'disabled':''}>${icon('undo',18)} Geri getir</button><button class="danger" data-action="bulk-delete054" ${!set.size?'disabled':''}>${icon('trash',18)} Kalıcı sil</button>`:`<button data-action="bulk-archive054" ${!set.size?'disabled':''}>${icon('archive',18)} ${UI.archived?'Arşivden çıkar':'Arşivle'}</button><button class="danger" data-action="bulk-trash054" ${!set.size?'disabled':''}>${icon('trash',18)} Çöpe taşı</button>`}</div>`;}
renderNotes=function(){const select=selection054();return `<div class="page notes05 ${select?'selecting054':''}">${header()}<div class="section-heading"><h1>${UI.trash?'Çöp kutusu':UI.archived?'Arşiv':'Notlar'}</h1>${select?'<button class="text-btn" data-action="notes-select-end054">Bitti</button>':'<button class="icon-btn clear" data-action="notes-filter" aria-label="Notları filtrele">'+icon('sliders')+'</button>'}</div><label class="note-search05">${icon('search',18)}<input id="note-search" value="${esc(UI.query)}" ${select?'disabled':''} placeholder="Notlarında ara" aria-label="Notlarında ara"></label>${select?`<div class="selection-head054"><span>Notlara dokunarak seç.</span><button class="text-btn" data-action="notes-select-all054">${visibleNotes054().length&&visibleNotes054().every(n=>select.has(n.id))?'Seçimi kaldır':UI.query||UI.category!=='Tümü'||UI.favorites?'Görünen tümünü seç':'Tümünü seç'}</button></div>`:''}${UI.category!=='Tümü'||UI.trash||UI.archived?`<button class="filter-tag" data-action="notes-reset">${esc(UI.trash?'Çöp kutusu':UI.archived?'Arşiv':UI.category)} ${icon('close',13)}</button>`:''}<div id="notes-results">${renderNoteResults()}</div>${select?selectionBar054():!UI.trash?`<button class="note-fab05" data-action="new-note" aria-label="Yeni not ekle">${icon('plus',27)}</button>`:''}</div>`;};
renderNoteResults=function(){const notes=visibleNotes054(),set=selection054();return notes.length?`<div class="note-list05">${notes.map(n=>`<article class="note-row05 ${set?.has(n.id)?'selected054':''}" data-note-id="${esc(n.id)}"><button class="note-open05" data-action="${set?'note-select-toggle054':UI.trash?'note-card-menu':'edit-note'}" data-id="${esc(n.id)}" ${set?`aria-pressed="${set.has(n.id)}"`:''}>${set?`<span class="selection-tick054">${set.has(n.id)?icon('check',15):''}</span>`:`<span class="note-color05" style="--swatch:${esc(/^#[0-9a-f]{6}$/i.test(n.color)?n.color:'#bba5d7')}"></span>`}<span class="grow"><strong>${n.pinned?icon('pin',12):''}${esc(n.title||'Başlıksız not')}</strong><span class="note-preview05">${esc(n.plainText||n.ink?.length&&'El yazısı'||n.attachments?.length&&'Ekli belge'||'Boş sayfa')}</span><small>${esc(fmtDate(n.updatedAt))}${n.attachments?.length?' · '+n.attachments.length+' ek':''}</small></span></button>${set?'':`<button class="icon-btn clear note-overflow05" data-action="note-card-menu" data-id="${esc(n.id)}" aria-label="${esc(n.title||'Not')} seçenekleri">${icon('more',19)}</button>`}</article>`).join('')}</div>`:`<div class="notes-empty05">${icon('note',34)}<h3>${UI.query?'Eşleşen not yok':UI.trash?'Çöp kutusu boş':'Düşüncelerine yer aç.'}</h3><p>${UI.trash?'':UI.query?'Başka bir kelime dene.':'Sağ alttaki + ile hemen yaz.'}</p></div>`;};
const cardMenuBefore054=noteCardMenu;
noteCardMenu=function(id){cardMenuBefore054(id);$('.sheet-body053 .note-menu')?.insertAdjacentHTML('afterbegin',`<button data-action="notes-select-start054" data-id="${esc(id)}">${icon('checkcircle')} Notları seç</button>`);};
const notesFilter053=notesFilter;
notesFilter=function(){notesFilter053();$('.sheet-body053 .note-menu')?.insertAdjacentHTML('afterbegin',`<button data-action="notes-select-start054">${icon('checkcircle')} Notları seç</button>`);};
async function bulkApply054(kind){if(bulkBusy054)return;const ids=[...(selection054()||[])].filter(id=>getNote(id)&&(kind==='delete'||kind==='restore'?!!getNote(id).deletedAt:!getNote(id).deletedAt));if(!ids.length)return;const op=kind==='delete'?'kalıcı olarak sil':kind==='trash'?'çöp kutusuna taşı':kind==='restore'?'geri getir':UI.archived?'arşivden çıkar':'arşivle';
 bulkBusy054=true;try{if(['delete','trash'].includes(kind)&&!await confirmAction(`${ids.length} not ${kind==='delete'?'kalıcı olarak silinsin mi':'çöp kutusuna taşınsın mı'}?`,kind==='delete'?'Bu işlem geri alınamaz. Seçili notların ekleri de notlarla birlikte erişimden çıkar.':'Notları daha sonra çöp kutusundan geri getirebilirsin.',kind==='delete'?'Kalıcı sil':'Çöp kutusuna taşı')){bulkBusy054=false;return;}}catch(e){bulkBusy054=false;throw e;}
 const prior=S.notes.map(n=>({...n})),stamp=new Date().toISOString();const snapshots=ids.map(id=>({id,deletedAt:getNote(id)?.deletedAt,archived:getNote(id)?.archived}));
 try{if(kind==='delete')S.notes=S.notes.filter(n=>!ids.includes(n.id));else for(const id of ids){const n=getNote(id);if(kind==='trash')n.deletedAt=stamp;if(kind==='restore')delete n.deletedAt;if(kind==='archive')n.archived=!UI.archived;}
  await persist(true);UI.noteSelection054=null;render();bulkUndo054=kind==='delete'?null:{snapshots};toast(`${ids.length} not ${kind==='delete'?'kalıcı olarak silindi':kind==='trash'?'çöp kutusuna taşındı':kind==='restore'?'geri getirildi':'güncellendi'}.`,6000);
  if(bulkUndo054){const b=document.createElement('button');b.className='toast-undo';b.dataset.action='bulk-undo054';b.textContent='Geri al';$('#toast')?.append(' ',b);}
 }catch(e){S.notes=prior;render();throw e;}finally{bulkBusy054=false;}
}
async function undoBulk054(){if(!bulkUndo054||bulkBusy054)return;bulkBusy054=true;const prior=S.notes.map(n=>({...n}));try{for(const p of bulkUndo054.snapshots){const n=getNote(p.id);if(!n)continue;if(p.deletedAt===undefined)delete n.deletedAt;else n.deletedAt=p.deletedAt;if(p.archived===undefined)delete n.archived;else n.archived=p.archived;}await persist(true);bulkUndo054=null;render();toast('Toplu işlem geri alındı.');}catch(e){S.notes=prior;throw e;}finally{bulkBusy054=false;}}
const actionNotes053=enhancedAction;
enhancedAction=async function(name,el,e){const id=el.dataset.id;switch(name){case'notes-select-start054':if(id)beginNoteSelection054(id);else{UI.noteSelection054=new Set();closeSheet();render();}return true;case'notes-select-end054':endNoteSelection054();return true;case'notes-select-all054':{const notes=visibleNotes054(),all=notes.length&&notes.every(n=>selection054()?.has(n.id));UI.noteSelection054=all?new Set():new Set(notes.map(n=>n.id));render();return true;}case'note-select-toggle054':{const set=selection054();if(set){set.has(id)?set.delete(id):set.add(id);render();}return true;}case'bulk-trash054':await bulkApply054('trash');return true;case'bulk-delete054':await bulkApply054('delete');return true;case'bulk-restore054':await bulkApply054('restore');return true;case'bulk-archive054':await bulkApply054('archive');return true;case'bulk-undo054':await undoBulk054();return true;}
 if(['route','notes-reset','open-trash','open-archive','note-category','notes-favorites'].includes(name))UI.noteSelection054=null;return actionNotes053(name,el,e);};
