/* Shops, purchased atmospheres and a separate indoor layout. */
function modeCards054(compact=false){return `<div class="mode-cards054 ${compact?'compact':''}">${Object.entries(ATMOSPHERES054).filter(([k])=>k!=='normal').map(([key,m])=>{const owned=ownsAtmosphere054(key),active=atmosphere054()===key;return `<article class="mode-card054 mode-${key}"><div class="mode-art054">${pixel(m.item,75)}<span>${active?'Etkin':owned?'Senin':'Özel koleksiyon'}</span></div><h3>${m.name}</h3>${compact?'':`<p>${m.description}</p>`}<button class="btn ${active?'ghost':'primary'} full" data-action="buy-mode054" data-mode="${key}" ${active?'disabled':''}>${active?'Seçili':owned?'Kullan':coinIcon(15)+' '+m.price.toLocaleString('tr-TR')}</button>${owned?'':'<small>Bir kez al · kalıcı kullan</small>'}</article>`;}).join('')}</div>`;}
weatherSheet=function(){sheet('Bahçemin havası',`<div class="weather054"><div class="option-section"><h3>Hava</h3><div class="chips">${[['clear','Açık'],['rain','Yağmur'],['snow','Kar']].map(([k,n])=>`<button class="chip ${gardenWeather()===k?'active':''}" data-action="set-weather" data-value="${k}" aria-pressed="${gardenWeather()===k}">${n}</button>`).join('')}</div><h3>Işık</h3><div class="chips">${[['day','Gündüz'],['dusk','Gün batımı'],['night','Gece']].map(([k,n])=>`<button class="chip ${gardenTime()===k?'active':''}" data-action="set-time" data-value="${k}" aria-pressed="${gardenTime()===k}">${n}</button>`).join('')}</div></div><div class="section-top"><h3>Özel havalar</h3><button class="text-btn" data-action="buy-mode054" data-mode="normal">${atmosphere054()==='normal'?'Klasik seçili':'Klasik bahçeye dön'}</button></div>${modeCards054(true)}<p class="hint">Manzaran, eşyaların ve bitkilerin korunur. Görsel hava ile ortam sesi birbirinden bağımsızdır.</p></div>`,'weather');};
const renderGarden053Polish=renderGarden;
renderGarden=function(){let html=renderGarden053Polish();html=html.replace('<button class="round-link" data-action="scenery-sheet">'+icon('image',17)+' Manzara</button>','');if(UI.gardenRoom){html=html.replace('garden-stage"','garden-stage room054"');html=html.replace('data-action="living-weather"','data-action="room-style054"').replace(icon('rain',18)+'Hava',icon('sliders',18)+'Oda');html=html.replace(/<div class="garden-quiet-stats">[\s\S]*?<\/div>/,'<p class="room-hint054">Eşyayı seç, oklarla taşı. Televizyon ve şömineye dokunarak açıp kapat.</p>');html=html.replace(/<section class="nursery053">[\s\S]*?<\/section>/,'');}return html;};
const route053Polish=route;
route=function(name,opts={}){if(name==='shop'&&UI.route==='garden'){UI.shopDestination054=!!UI.gardenRoom;UI.shopTab=UI.gardenRoom?'home':(UI.shopTab==='home'?'decor':UI.shopTab);}if(name==='garden'&&UI.route==='shop')UI.gardenRoom=!!UI.shopDestination054;return route053Polish(name,opts);};
renderShop=function(){const tab=['pets','decor','home','modes','scenery'].includes(UI.shopTab)?UI.shopTab:'pets',type=tab==='pets'?'pet':'decor';const list=tab==='pets'?Object.entries(PETS):Object.entries(DECOR).filter(([id,item])=>tab==='home'?item.group==='home':['garden','pots'].includes(item.group));return `<div class="page shop054">${header('',true)}<div class="section-heading"><div><span class="eyebrow">KÜÇÜK KEŞİFLER</span><h1>Mağaza</h1></div><div class="wallet-total">${coinIcon(23)}<strong>${wallet()}</strong></div></div><div class="shop-guide">1 dakika odak = 3 jeton <button data-action="economy-info" class="icon-btn clear" aria-label="Jetonlar nasıl kazanılır?">${icon('info',16)}</button></div><div class="shop-tabs054" role="tablist">${[['pets','Arkadaşlar'],['decor','Bahçe'],['home','Ev eşyaları'],['modes','Özel hava'],['scenery','Manzara']].map(([id,name])=>`<button role="tab" aria-selected="${id===tab}" class="${id===tab?'active':''}" data-action="shop-tab" data-tab="${id}">${name}</button>`).join('')}</div>${tab==='scenery'?sceneryCards():tab==='modes'?`<p class="hint">Üç özel dünya. Eşyalarını değiştirmeden ağaçları, kulübeyi ve atmosferi dönüştür.</p>${modeCards054()}<button class="text-btn full" data-action="buy-mode054" data-mode="normal">Klasik bahçeye dön</button>`:`${tab==='home'?'<p class="hint">Kulübene yerleştir. Televizyon, şömine ve akvaryum dokunmaya tepki verir.</p>':''}<div class="shop-grid">${list.map(([id,item])=>{const owned=owns(type,id),selected=type==='pet'&&S.preferences.companion===id;return `<article class="shop-card ${selected?'selected':''}"><div class="shop-art">${pixel(id,92)}${selected?'<span class="selected-badge">'+icon('check',12)+'</span>':''}</div><h3>${esc(item.name)}</h3><button class="shop-buy ${owned?'owned':''}" data-action="${owned&&type==='pet'?'select-pet':owned?'place-owned':'buy-item'}" data-type="${type}" data-item="${id}">${owned?(selected?'Yanımda':type==='pet'?'Yanıma al':item.group==='pots'?'Kullan':item.roomOnly?'Eve yerleştir':'Yerleştir'):coinIcon(14)+' '+item.price}</button></article>`;}).join('')}</div>`}</div>`;};
inventorySheet=function(){UI.placeDestination054=!!UI.gardenRoom;const items=[...ownedPets().map(id=>({type:'pet',id,label:petLabel(id),sprite:id})),...S.world.harvested.map(p=>({type:'plant',id:p.id,label:SEEDS[p.kind].name,sprite:SEEDS[p.kind].sprite})),...S.world.purchases.filter(p=>p.type==='decor'&&DECOR[p.item]?.placeable!==false&&DECOR[p.item]?.group!=='pots').map(p=>({type:'decor',id:p.item,label:DECOR[p.item].name,sprite:p.item}))];const selected=items.filter(p=>UI.gardenRoom?true:!DECOR[p.id]?.roomOnly);sheet(UI.gardenRoom?'Evimdeki koleksiyon':'Koleksiyonum',`<div class="inventory-grid">${selected.map(p=>{const current=livingPlacements().find(x=>x.key===p.type+':'+p.id),where=current?(current.pos.room?'Evde':'Bahçede'):'Yerleştir';return `<button data-action="place-owned" data-type="${p.type}" data-item="${esc(p.id)}">${pixel(p.sprite,64)}<strong>${esc(p.label)}</strong><small>${where}</small></button>`;}).join('')}</div>`,'inventory');};
placeOwned=async function(type,id){const definition=type==='decor'?DECOR[id]:null;if(definition?.placeable===false)return;if(definition?.group==='pots'){if(!owns(type,id))return;S.world.pot=id;await persist(true);closeSheet();route('garden');return;}
 if(type==='plant'?!S.world.harvested.some(x=>x.id===id):!owns(type,id))return;const room=definition?.roomOnly||!!(UI.route==='shop'?UI.shopDestination054:UI.gardenRoom),key=type+':'+id,priorWorld=structuredClone(S.world),priorLiving=structuredClone(S.living);let item=S.world.layout.find(x=>x.type===type&&x.item===id);if(!item){if(S.world.layout.length>=60){toast('En fazla 60 öğe yerleştirilebilir. Birini koleksiyonuna kaldır.');return;}item={id:uid(),type,item:id,x:50,y:75};S.world.layout.push(item);}const previous=S.living.placement[key];if(!previous||!!previous.room!==!!room)S.living.placement[key]={x:room?230:240,y:room?230:224,room:!!room};
 try{await persist(true);}catch(e){S.world=priorWorld;S.living=priorLiving;throw e;}UI.gardenEdit=true;UI.selectedLiving=key;UI.shopDestination054=!!room;UI.gardenRoom=!!room;closeSheet();route('garden');
};
function roomStyle054(){sheet('Kulübemi düzenle',`<h3>Duvar</h3><div class="chips">${[['cream','Krem'],['sage','Adaçayı'],['rose','Gül'],['night','Mavi']].map(([k,n])=>`<button class="chip ${S.living.roomWall===k?'active':''}" data-action="room-palette054" data-field="roomWall" data-value="${k}">${n}</button>`).join('')}</div><h3>Zemin</h3><div class="chips">${[['oak','Meşe'],['walnut','Ceviz'],['light','Açık ahşap']].map(([k,n])=>`<button class="chip ${S.living.roomFloor===k?'active':''}" data-action="room-palette054" data-field="roomFloor" data-value="${k}">${n}</button>`).join('')}</div><button class="btn primary full" data-action="room-shop054">Ev eşyalarına bak</button>`,'room-style');}
const ground053Polish=groundSheet;groundSheet=function(){if(UI.gardenRoom)return roomStyle054();return ground053Polish();};
const actionShell053=enhancedAction;
enhancedAction=async function(name,el,e){const d=el.dataset;
 if(name==='shop-tab'){UI.shopTab=['pets','decor','home','modes','scenery'].includes(d.tab)?d.tab:'pets';render();return true;}
 if(name==='buy-mode054'){await purchaseAtmosphere054(d.mode);if(d.mode==='normal')await setAtmosphere054('normal');return true;}
 if(name==='buy-item'&&DECOR[d.item]?.group==='modes'){await purchaseAtmosphere054(DECOR[d.item].mode);return true;}
 if(name==='room-style054'){roomStyle054();return true;}
 if(name==='room-shop054'){UI.shopDestination054=true;UI.shopTab='home';closeSheet();route('shop');return true;}
 if(name==='room-palette054'){const allowed=d.field==='roomWall'?['cream','sage','rose','night']:d.field==='roomFloor'?['oak','walnut','light']:[];if(allowed.includes(d.value)){const old=S.living[d.field];S.living[d.field]=d.value;try{await persist(true);}catch(e){S.living[d.field]=old;throw e;}for(const g of gardenInstances)g.update();roomStyle054();}return true;}
 if(name==='set-weather'||name==='set-time'){const field=name==='set-weather'?'weather':'time',ok=field==='weather'?['clear','rain','snow']:['day','dusk','night'];if(ok.includes(d.value)){const old=S.living[field];S.living[field]=d.value;try{await persist(true);}catch(err){S.living[field]=old;throw err;}for(const g of gardenInstances)g.update();weatherSheet();}return true;}
 if(name==='select-scenery'){const b=SCENERIES[d.key];if(b&&worldSeconds()/60>=b.minutes){const old=structuredClone(S.living),oldBg=S.world.background;S.world.background=d.key;S.living.atmosphere='normal';S.living.weather=d.key==='snow'?'snow':d.key==='pond'?'rain':'clear';S.living.time=({night:'night',cosmic:'night',meadow:'day',pond:'dusk',autumn:'dusk',snow:'day'})[d.key]||'day';try{await persist(true);}catch(e){S.living=old;S.world.background=oldBg;throw e;}closeSheet();render();}else toast('Bu manzara için biraz daha odak süresi gerekiyor.');return true;}
 if(name==='living-layout'){if(UI.gardenRoom){roomStyle054();return true;}rememberGarden();S.living.ground=[];for(let x=11;x<20;x++)S.living.ground.push({x,y:d.layout==='pond'?12:14,kind:d.layout==='camp'?'wood':'stone'});for(const [i,p]of livingPlacements().filter(p=>!p.pos.room).entries())S.living.placement[p.key]={x:100+i%7*41,y:195+Math.floor(i/7)*24,room:false};await persist(true);closeSheet();render();return true;}
 return actionShell053(name,el,e);
};
function constrainPlacement054(key,pos){const i=key.indexOf(':'),kind=key.slice(0,i),id=key.slice(i+1),size=kind==='decor'?(DECOR[id]?.size||40):36;
 if(pos.room)return {x:clamp(pos.x,37+size/2,443-size/2),y:clamp(pos.y,Math.max(88,38+size),286),room:true};
 const px=24+(pos.x-30)*312/420,py=181+(pos.y-88)*256/204,x=clamp(px,6+size/2,354-size/2),y=clamp(py,Math.max(181,105+size),437);
 return {x:30+(x-24)*420/312,y:88+(y-181)*204/256,room:false};
}
const moveBefore054=LivingGarden.prototype.move;
LivingGarden.prototype.move=function(e){moveBefore054.call(this,e);if(this.drag?.remembered&&this.drag.hit?.key){const key=this.drag.hit.key;S.living.placement[key]=constrainPlacement054(key,S.living.placement[key]);this.paint(performance.now());}};
const selectionBefore054=updateGardenSelection;
updateGardenSelection=function(){const p=livingPlacements().find(p=>p.key===UI.selectedLiving);if(p&&!!p.pos.room!==!!UI.gardenRoom)UI.selectedLiving=null;selectionBefore054();};
const actionClamp054=enhancedAction;
enhancedAction=async function(name,el,e){if(name==='living-nudge'){const p=livingPlacements().find(p=>p.key===UI.selectedLiving),d={left:[-8,0],right:[8,0],up:[0,-6],down:[0,6]}[el.dataset.direction];if(p&&d&&!!p.pos.room===!!UI.gardenRoom){rememberGarden();const prior={...p.pos};S.living.placement[p.key]=constrainPlacement054(p.key,{x:p.pos.x+d[0],y:p.pos.y+d[1],room:!!p.pos.room});try{await persist(true);}catch(err){S.living.placement[p.key]=prior;throw err;}for(const g of gardenInstances)g.paint(performance.now());}return true;}return actionClamp054(name,el,e);};
