function mondayFor(day=localDay()){return addDays(day,-((dayDate(day).getDay()+6)%7))}
function weeklyStats(start){
 const end=addDays(start,7),sessions=S.focusHistory.filter(s=>s.phase!=='break'&&s.completedMinutes>0&&localDay(new Date(s.endedAt))>=start&&localDay(new Date(s.endedAt))<end);
 const days=Array.from({length:7},(_,i)=>{const day=addDays(start,i);return {day,total:sessions.filter(s=>localDay(new Date(s.endedAt))===day).reduce((a,s)=>a+s.completedMinutes,0)}});
 const groups={};for(const s of sessions){const n=getNote(s.noteId),key=n?.category||'Serbest odak';groups[key]=(groups[key]||0)+s.completedMinutes;}
 return {sessions,days,total:days.reduce((a,d)=>a+d.total,0),activeDays:days.filter(d=>d.total>0).length,groups:Object.entries(groups).sort((a,b)=>b[1]-a[1])};
}
function renderWeekly(){
 const start=UI.weekStart||mondayFor(),stats=weeklyStats(start),prior=weeklyStats(addDays(start,-7)),goal=S.weeklyGoals[start]||{},max=Math.max(30,...stats.days.map(d=>d.total));
 return `<div class="page">${header('',true)}<div class="title-row"><h1>Haftam</h1></div><div class="week-nav"><button class="icon-btn clear" data-action="week-prev" aria-label="Önceki hafta">${icon('back',17)}</button><span>${fmtDate(start)} – ${fmtDate(addDays(start,6))}</span><button class="icon-btn clear" data-action="week-next" aria-label="Sonraki hafta" ${start>=mondayFor()?'disabled':''}>${icon('arrow',17)}</button></div>
 <div class="stats-row"><div class="stat-cell"><strong>${Math.round(stats.total)}</strong><span>dakika</span></div><div class="stat-cell"><strong>${stats.sessions.length}</strong><span>oturum</span></div><div class="stat-cell"><strong>${stats.activeDays}</strong><span>gün</span></div></div><section class="card weekly-chart"><div class="bar-chart" aria-label="Bu hafta günlük odak süreleri">${stats.days.map((d,i)=>`<button class="bar-col ${d.day===localDay()?'today':''}" data-action="week-day" data-day="${d.day}" aria-label="${fmtDate(d.day)}, ${Math.round(d.total)} dakika"><span class="bar-number">${d.total?Math.round(d.total):'—'}</span><div class="bar" style="height:${Math.max(3,d.total/max*92)}px"></div><span>${['Pzt','Sal','Çar','Per','Cum','Cmt','Paz'][i]}</span></button>`).join('')}</div><p class="hint">Önceki hafta: ${Math.round(prior.total)} dk</p></section>
 <div class="section-top"><h2>Zaman ayırdıklarım</h2></div>${stats.groups.length?`<section class="card flat category-breakdown">${stats.groups.map(([name,mins])=>`<div><span>${esc(name)}</span><strong>${fmtMinutes(mins)}</strong><div class="growth-track"><i style="width:${mins/Math.max(1,stats.total)*100}%"></i></div></div>`).join('')}</section>`:'<p class="hint">Çalışma oturumların tamamlandıkça burada görünür.</p>'}
 <div class="section-top"><h2>Küçük hedefim</h2><button class="text-btn" data-action="week-goal">${icon('edit',16)}</button></div><section class="card goal-card">${goal.minutes?`<div class="row between"><strong>${Math.round(stats.total)} / ${goal.minutes} dk</strong>${pixel(S.preferences.companion,44)}</div><div class="growth-track"><i style="width:${Math.min(100,stats.total/goal.minutes*100)}%"></i></div>${goal.intention?`<p>${esc(goal.intention)}</p>`:''}`:'<button class="text-btn" data-action="week-goal">İsteğe bağlı bir hedef ekle '+icon('plus',14)+'</button>'}</section>
 <div class="section-top"><h2>Haftadan kalan</h2><button class="text-btn" data-action="week-reflection">${icon('edit',16)}</button></div><section class="card flat reflection-card"><p>${goal.reflection?esc(goal.reflection):'Kendine bir cümle bırak.'}</p></section><button class="btn ghost full" style="margin-top:18px" data-action="weekly-to-note">${icon('note',17)} Notlarıma ekle</button></div>`;
}
function weeklyGoalSheet(reflection=false){const start=UI.weekStart||mondayFor(),g=S.weeklyGoals[start]||{};sheet(reflection?'Haftadan kalan':'Küçük hedefim',`<form id="week-goal-form"><input type="hidden" name="week" value="${start}">${reflection?`<label class="field"><span>Bu hafta bana ne iyi geldi?</span><textarea name="reflection" rows="6" maxlength="1500" placeholder="Aklından geçtiği gibi…">${esc(g.reflection||'')}</textarea></label>`:`<label class="field"><span>Haftalık dakika · 0 = hedef yok</span><input name="minutes" type="number" min="0" max="6000" value="${g.minutes||0}" inputmode="numeric"></label><label class="field"><span>Neye zaman ayırmak istiyorum?</span><input name="intention" maxlength="200" value="${esc(g.intention||'')}" placeholder="Örneğin: ders notlarımı düzenlemek"></label>`}<button type="submit" class="btn primary full">Kaydet</button></form>`,'weekly-goal')}
async function weeklyToNote(){const start=UI.weekStart||mondayFor(),stats=weeklyStats(start),g=S.weeklyGoals[start]||{},now=new Date().toISOString();const n={id:uid(),title:`Haftam · ${fmtDate(start)} – ${fmtDate(addDays(start,6))}`,html:`<h2>Odağım</h2><p>${Math.round(stats.total)} dakika · ${stats.sessions.length} oturum · ${stats.activeDays} gün</p>${stats.groups.map(([name,min])=>`<p>${esc(name)}: ${Math.round(min)} dk</p>`).join('')}<h2>Küçük hedefim</h2><p>${esc(g.intention||'')}${g.minutes?' · '+g.minutes+' dk':''}</p><h2>Haftadan kalan</h2><p>${esc(g.reflection||'')}</p>`,category:'Günlük',attachments:[],createdAt:now,updatedAt:now,font:'modern'};n.plainText=plain(n.html);if(!S.preferences.categories.includes('Günlük'))S.preferences.categories.push('Günlük');S.notes.unshift(n);await persist(true);openEditor(n.id);}
