function placedSprite(item){if(item.type==='plant'){const p=S.world.harvested.find(p=>p.id===item.item);return p?SEEDS[p.kind].sprite:'sprout';}return item.item;}
function gardenScene(){
  const w=S.world,pet=S.preferences.companion,edit=!!UI.gardenEdit;
  const layout=w.layout.filter(i=>!(i.type==='pet'&&i.item===pet));
  const buddyPlacement=w.layout.find(i=>i.type==='pet'&&i.item===pet)||{id:'buddy:'+pet,type:'pet',item:pet,x:57,y:74};
  const objects=[...layout,buddyPlacement].sort((a,b)=>a.y-b.y);
  return `<div class="pixel-world ${edit?'editing':''}" id="pixel-world" aria-label="${esc(SCENERIES[w.background].name)}">${scenerySVG(w.background)}<div class="scene-badge">${SCENERIES[w.background].name}</div>${objects.map((p,i)=>`<button class="world-item ${p.type==='pet'?'world-pet':''} ${UI.selectedWorldItem===p.id?'selected':''}" style="left:${p.x}%;top:${p.y}%;--delay:${i*.37}s" data-world-id="${esc(p.id)}" data-action="world-item" data-item="${esc(p.id)}" aria-label="${esc(p.type==='pet'?petLabel(p.item):p.type==='plant'?SEEDS[S.world.harvested.find(h=>h.id===p.item)?.kind]?.name||'Bitki':DECOR[p.item]?.name||'Dekor')}${edit?', sürükle ya da yön tuşlarıyla taşı':''}">${pixel(placedSprite(p),p.type==='pet'?62:48)}${p.id===buddyPlacement.id?'<i class="buddy-mark"></i>':''}</button>`).join('')}<div class="world-sheen"></div></div>`;
}
function renderGarden(){const total=Math.floor(worldSeconds()/60),w=S.world;
  return `<div class="page garden-page">${header()}<div class="section-heading"><div><span class="eyebrow">SANA AİT</span><h1>Bahçem</h1></div><button class="round-link" data-action="route" data-route="shop">${icon('plus',16)} Mağaza</button></div>${gardenScene()}
  <div class="world-actions"><button class="btn ${UI.gardenEdit?'primary':'ghost'}" data-action="garden-edit">${icon(UI.gardenEdit?'check':'edit',16)}${UI.gardenEdit?'Bitti':'Düzenle'}</button><button class="btn ghost" data-action="scenery-sheet">${icon('image',16)}Manzara</button><button class="btn ghost" data-action="inventory">${icon('grid',16)}Koleksiyon</button></div>
  ${UI.gardenEdit?`<div class="edit-help"><span>${UI.selectedWorldItem?'Seçili öğeyi sürükle veya oklarla taşı.':'Taşımak için bir öğe seç.'}</span><div class="nudge-bar">${[['left','←'],['right','→'],['up','↑'],['down','↓']].map(([d,l])=>`<button data-action="world-nudge" data-direction="${d}" aria-label="${d} taşı">${l}</button>`).join('')}<button data-action="world-remove" aria-label="Seçili öğeyi bahçeden kaldır">${icon('close',16)}</button></div></div>`:''}
  <div class="garden-summary"><span>${icon('focus',15)} ${fmtMinutes(total)}</span><span>${pixel('sprout',22)} ${w.harvested.length} bitki</span><span>${pixel(S.preferences.companion,25)} ${ownedPets().length} arkadaş</span></div>
  <div class="section-top"><h2>Yetiştir</h2><button class="text-btn" data-action="pot-sheet">Saksılar ${icon('chevron',12)}</button></div><div class="growing-plots">${w.plots.map((p,i)=>{const progress=plantProgress(p);return `<button class="growing-plot ${!p?'empty-plot':''} ${progress>=1?'ready-plant':''}" data-action="seed-sheet" data-slot="${i}" aria-label="${p?SEEDS[p.kind].name+', '+Math.round(progress*100)+' yüzde':'Tohum ek'}"><div class="pot-stage pot-${esc(w.pot)}">${p?pixel(activePlantSprite(p),63):icon('plus',22)}<i class="pixel-pot"></i></div><strong>${p?SEEDS[p.kind].name:'Tohum ek'}</strong><small>${p?(progress>=1?'Hazır!':`${Math.round(progress*100)}%`):'Ücretsiz'}</small><div class="growth-track"><i style="width:${progress*100}%"></i></div></button>`}).join('')}</div>
  <button class="weekly-link" data-action="route" data-route="weekly"><span>${icon('calendar',20)} Haftalık özet</span>${icon('arrow',17)}</button>
  <details class="history-details"><summary>Oturumlar <span>${S.focusHistory.length}</span></summary>${S.focusHistory.slice(0,30).map(s=>`<button class="history-row" data-action="session-detail" data-id="${esc(s.id)}">${icon(s.completed?'checkcircle':'focus',18)}<div class="grow"><h3>${esc(s.title||'Odak')}</h3><p>${esc(fmtDate(s.endedAt))}</p></div><span>${Math.round(s.completedMinutes)} dk</span></button>`).join('')||'<p class="hint">İlk oturumundan sonra burada.</p>'}</details></div>`;
}
function renderShop(){
  const tab=UI.shopTab||'pets',balance=wallet();
  return `<div class="page">${header('',true)}<div class="section-heading"><div><span class="eyebrow">KÜÇÜK KEŞİFLER</span><h1>Mağaza</h1></div><div class="wallet-total">${coinIcon(24)}<strong>${balance}</strong></div></div><div class="shop-guide">1 dakika odak = 3 jeton <button data-action="economy-info" class="icon-btn clear" aria-label="Jetonlar nasıl kazanılır?">${icon('info',16)}</button></div>
  <div class="segment-control" role="tablist">${[['pets','Arkadaşlar'],['decor','Dekor'],['scenery','Manzara']].map(([id,name])=>`<button role="tab" aria-selected="${id===tab}" class="${id===tab?'active':''}" data-action="shop-tab" data-tab="${id}">${name}</button>`).join('')}</div>
  ${tab==='scenery'?sceneryCards():`<div class="shop-grid">${Object.entries(tab==='pets'?PETS:DECOR).map(([id,item])=>{const type=tab==='pets'?'pet':'decor',owned=owns(type,id),selected=type==='pet'&&S.preferences.companion===id;return `<article class="shop-card ${selected?'selected':''}"><div class="shop-art" style="--pet-color:${item.color||'#d6b0d3'}">${pixel(id,82)}${selected?`<span class="selected-badge">${icon('check',12)}</span>`:''}</div><h3>${item.name}</h3><button class="shop-buy ${owned?'owned':''}" data-action="${owned&&type==='pet'?'select-pet':owned?'place-owned':'buy-item'}" data-type="${type}" data-item="${id}" aria-label="${item.name}, ${owned?(selected?'yanımda':'seç'):item.price+' jeton'}">${owned?(selected?'Yanımda':type==='pet'?'Yanıma al':id.startsWith('pot')?'Kullan':'Yerleştir'):`${coinIcon(14)} ${item.price}`}</button></article>`}).join('')}</div>`}</div>`;
}
function sceneryCards(){const mins=worldSeconds()/60;return `<div class="scenery-grid">${Object.entries(SCENERIES).map(([key,b])=>{const open=mins>=b.minutes,active=S.world.background===key;return `<button class="scenery-card ${active?'selected':''}" data-action="select-scenery" data-key="${key}" aria-label="${b.name}, ${open?'açık':b.minutes+' dakika çalışma gerekli'}"><div class="scenery-thumb">${scenerySVG(key)}${open?'':`<span class="scene-lock">${icon('lock',18)}</span>`}</div><div class="scenery-meta"><strong>${b.name}</strong><small>${active?'Seçili':open?'Seç':`${Math.ceil(b.minutes-mins)} dk kaldı`}</small></div>${!open?`<div class="growth-track"><i style="width:${Math.min(100,mins/b.minutes*100)}%"></i></div>`:''}</button>`}).join('')}</div>`}
function petSheet(){const pet=S.preferences.companion;sheet('Yol arkadaşım',`<div class="pet-profile">${pixel(pet,110)}<h2>${esc(petLabel())}</h2><p>${PETS[pet]?.name||''}</p></div><form id="pet-name-form"><label class="field"><span>İsmi</span><input name="petName" value="${esc(S.world.petNames[pet]||'')}" maxlength="22" placeholder="Bir isim ver"></label><button class="btn primary full" type="submit">Kaydet</button></form><div class="owned-pet-strip">${ownedPets().map(p=>`<button data-action="select-pet" data-item="${p}" aria-label="${PETS[p].name} seç" class="${p===pet?'selected':''}">${pixel(p,50)}<small>${PETS[p].name}</small></button>`).join('')}</div><button class="text-btn full" data-action="route" data-route="shop">Yeni arkadaşlar keşfet ${icon('arrow',14)}</button>`,'pet')}
function inventorySheet(){const items=[...ownedPets().map(id=>({type:'pet',id,label:petLabel(id),sprite:id})),...S.world.harvested.map(p=>({type:'plant',id:p.id,label:SEEDS[p.kind].name,sprite:SEEDS[p.kind].sprite})),...S.world.purchases.filter(p=>p.type==='decor'&&!p.item.startsWith('pot')).map(p=>({type:'decor',id:p.item,label:DECOR[p.item].name,sprite:p.item}))];sheet('Koleksiyonum',`<div class="inventory-grid">${items.map(p=>`<button data-action="place-owned" data-type="${p.type}" data-item="${esc(p.id)}">${pixel(p.sprite,58)}<strong>${esc(p.label)}</strong><small>${S.world.layout.some(x=>x.type===p.type&&x.item===p.id)?'Bahçede':'Yerleştir'}</small></button>`).join('')}</div>`,'inventory')}
async function placeOwned(type,id){
 if(type==='decor'&&id.startsWith('pot')){if(!owns('decor',id))return;S.world.pot=id;await persist(true);closeSheet();route('garden');return;}
 if(type==='pet'&&!owns('pet',id))return;if(type==='decor'&&!owns('decor',id))return;if(type==='plant'&&!S.world.harvested.some(p=>p.id===id))return;
 const existing=S.world.layout.find(p=>p.type===type&&p.item===id);if(existing){UI.selectedWorldItem=existing.id;}else{
   if(S.world.layout.length>=60){toast('Bahçede en fazla 60 öğe olabilir. Birini koleksiyona kaldır.');return;}
   const object={id:uid(),type,item:id,x:26+(S.world.layout.length*13)%50,y:71+(S.world.layout.length%4)*4};S.world.layout.push(object);UI.selectedWorldItem=object.id;
 }
 UI.gardenEdit=true;await persist(true);route('garden');
}
function potSheet(){sheet('Saksılar',`<div class="seed-grid">${[['clay','Toprak saksı'],['potLilac','Lavanta saksı'],['potMint','Nane saksı']].map(([id,name])=>`<button class="seed-card" data-action="select-pot" data-item="${id}"><div class="pot-stage pot-${id}">${pixel('sprout',58)}<i class="pixel-pot"></i></div><strong>${name}</strong><small>${S.world.pot===id?'Seçili':id==='clay'||owns('decor',id)?'Kullan':DECOR[id].price+' jeton'}</small></button>`).join('')}</div>`,'pots')}
function getWorldItem(id){if(typeof id==='string'&&id.startsWith('buddy:')){let p=S.world.layout.find(x=>x.type==='pet'&&x.item===S.preferences.companion);if(!p){p={id:'buddy:'+S.preferences.companion,type:'pet',item:S.preferences.companion,x:57,y:74};S.world.layout.push(p);}return p;}return S.world.layout.find(x=>x.id===id)}
function moveWorldItem(id,x,y){const item=getWorldItem(id);if(!item)return;item.x=clamp(x,6,94);item.y=clamp(y,59,88);const el=$(`[data-world-id="${CSS.escape(id)}"]`);if(el){el.style.left=item.x+'%';el.style.top=item.y+'%';}}
