from playwright.sync_api import sync_playwright
from pathlib import Path
import json,time,traceback
ROOT=Path(__file__).resolve().parents[2]
OUT=ROOT/'tests/053';OUT.mkdir(exist_ok=True,parents=True)
results=[]
def check(name,condition,detail=None):
 results.append({'name':name,'passed':bool(condition),'detail':detail});print(('PASS ' if condition else 'FAIL ')+name, detail if not condition else '')
with sync_playwright() as pw:
 b=pw.chromium.launch(executable_path='/usr/bin/chromium',headless=True,args=['--no-sandbox','--enable-unsafe-swiftshader'])
 p=b.new_page(viewport={'width':390,'height':844},has_touch=True,device_scale_factor=1)
 errors=[];p.on('pageerror',lambda e:errors.append(str(e)))
 p.evaluate("Object.defineProperty(window,'localStorage',{value:{getItem:k=>window.__store?.[k]||null,setItem:(k,v)=>{(window.__store||={})[k]=v},removeItem:k=>delete window.__store[k]}})")
 p.set_content((ROOT/'ONIZLEME.html').read_text());p.wait_for_function('ready');p.wait_for_timeout(120)
 check('fresh boot',p.evaluate("UI_BUILD==='LUMA-0.5.3-STABLE-GARDEN' && ready && S.schema===3"))
 p.evaluate("S.preferences.finishSound=false;S.preferences.soundWithFocus=false;window.__originalCall=Native.call.bind(Native);void 0;")
 for theme in p.evaluate('Object.keys(themes)'):
  p.evaluate('(theme)=>{S.preferences.theme=theme;applyTheme();route("focus");}',theme);p.wait_for_timeout(70)
  check('theme switch '+theme,p.locator('.screen-error').count()==0 and not errors,errors[:])
 for route in ['home','notes','calendar','garden','shop','weekly','backup','settings','themes','focus']:
  p.evaluate('(r)=>route(r)',route);p.wait_for_timeout(60)
  check('route '+route,p.locator('.screen-error').count()==0)
 p.evaluate("S.preferences.theme='garden';applyTheme();route('garden');window.__g=()=>[...gardenInstances].find(g=>!g.passive)")
 p.wait_for_timeout(100)
 check('portrait aspect ratio 3:4',p.evaluate("Math.abs($('.garden-stage').clientHeight/$('.garden-stage').clientWidth-4/3)<.01"))
 check('one scene mounted',p.evaluate('gardenInstances.size===1'))
 p.mouse.move(180,450);p.mouse.down();p.mouse.move(235,535,steps=12);p.mouse.up();p.wait_for_timeout(50)
 check('ordinary drag leaves camera at origin',p.evaluate('__g().pan.x===0 && __g().pan.y===0'))
 check('ordinary drag does not move owned items',p.evaluate('Object.keys(S.living.placement).length===0'))
 p.locator('[data-action="garden-zoom"]').first.click();p.wait_for_timeout(100)
 check('plus zoom works',p.evaluate('__g().zoom===1.25'))
 p.mouse.move(180,450);p.mouse.down();p.mouse.move(120,500,steps=12);p.mouse.up()
 check('zoomed drag also keeps camera fixed',p.evaluate('__g().pan.x===0 && __g().pan.y===0'))
 p.evaluate('__g().setZoom(100)');check('zoom max bounded',p.evaluate('__g().zoom===2.7'))
 p.locator('[data-action="garden-reset-view"]').click();check('fit button resets zoom',p.evaluate('__g().zoom===1 && __g().pan.x===0'))
 p.evaluate('UI.gardenEdit=true;render();UI.selectedLiving="pet:bunny";updateGardenSelection();window.__beforePos=livingPlacements().find(x=>x.key==="pet:bunny").pos.x')
 p.locator('[data-action="living-nudge"][data-direction="right"]').click();p.wait_for_timeout(100)
 check('right arrow updates item only',p.evaluate('S.living.placement["pet:bunny"].x===__beforePos+8 && __g().pan.x===0'))
 p.locator('[data-action="living-nudge"][data-direction="left"]').click();p.wait_for_timeout(50)
 check('left arrow restores x',p.evaluate('S.living.placement["pet:bunny"].x===__beforePos'))
 p.evaluate('window.__beforePosY=S.living.placement["pet:bunny"].y')
 p.locator('[data-action="living-nudge"][data-direction="up"]').click();p.wait_for_timeout(50)
 check('up arrow updates y',p.evaluate('S.living.placement["pet:bunny"].y===__beforePosY-6'))
 p.locator('[data-action="living-nudge"][data-direction="down"]').click();p.wait_for_timeout(50)
 check('down arrow restores y',p.evaluate('S.living.placement["pet:bunny"].y===__beforePosY'))
 # Selected-item canvas drag, convert its pixel position into browser coordinates.
 p.evaluate("$('#screen').scrollTop=0;render();UI.selectedLiving='pet:bunny';updateGardenSelection();__g().paint(performance.now());")
 pos=p.evaluate("(()=>{const g=__g(),h=g.hits.find(x=>x.key==='pet:bunny'),r=g.canvas.getBoundingClientRect();return {x:r.x+g.fit.ox+(h.x+h.w/2)*g.fit.scale,y:r.y+g.fit.oy+(h.y+h.h/2)*g.fit.scale,before:S.living.placement['pet:bunny']}})()")
 p.mouse.move(pos['x'],pos['y']);p.mouse.down();p.mouse.move(pos['x']+20,pos['y']+22,steps=10);p.mouse.up();p.wait_for_timeout(100)
 check('edit drag moves item without moving camera',p.evaluate('S.living.placement["pet:bunny"].x!=='+str(pos['before']['x'])+' && __g().pan.x===0'))
 # Persist serialization does not alter coordinate system or item ownership.
 check('coordinate normalization preserves item',p.evaluate("(()=>{const n=normalize(JSON.parse(JSON.stringify(S)));return n.living.placement['pet:bunny'].x===S.living.placement['pet:bunny'].x})()"))
 p.evaluate("UI.gardenEdit=false;render();")
 check('nursery under garden',p.evaluate("$('.nursery053').offsetTop>$('.garden-stage').offsetTop+$('.garden-stage').offsetHeight"))
 check('three restored seed cards',p.locator('.growing-plot').count()==3)
 p.evaluate("S.world.plots[0]={id:'plant-test',kind:'daisy',atSeconds:worldSeconds()};render();")
 check('seed title and remaining time', 'Papatya' in p.locator('.growing-plot').first.inner_text() and '35 dk' in p.locator('.growing-plot').first.inner_text())
 before=p.evaluate('wallet()')
 p.evaluate("enhancedAction('living-water',{dataset:{slot:'0'}},{})");p.wait_for_timeout(150)
 check('manual watering animation active',p.locator('.watering053').count()==1)
 check('watering not free money or growth',p.evaluate('wallet()')==before and p.evaluate('plantProgress(S.world.plots[0])===0'))
 # Scenery selection affects palette and follows automatic atmosphere; custom light still allowed.
 for k in p.evaluate('Object.keys(SCENERIES)'):
  p.evaluate('(k)=>{S.world.background=k;S.living.time="auto";S.living.weather="auto";render();}',k)
  check('scenery profile '+k,p.evaluate('(k)=>sceneryProfile()===SCENERIES[k]',k))
 check('night scenery is night',p.evaluate("S.world.background='night';gardenTime()==='night'"))
 check('meadow scenery is day',p.evaluate("S.world.background='meadow';gardenTime()==='day'"))
 check('pond automatic rain',p.evaluate("S.world.background='pond';gardenWeather()==='rain'"))
 check('snow automatic snow',p.evaluate("S.world.background='snow';gardenWeather()==='snow'"))
 # Real Chromium touch dispatch (not DOM synthetic pointer events).
 c=p.context.new_cdp_session(p)
 def swipe(x,y,dy,dx=0,steps=12):
  c.send('Input.dispatchTouchEvent',{'type':'touchStart','touchPoints':[{'x':x,'y':y,'id':1}]})
  for i in range(1,steps+1):
   c.send('Input.dispatchTouchEvent',{'type':'touchMove','touchPoints':[{'x':x+dx*i/steps,'y':y+dy*i/steps,'id':1}]});p.wait_for_timeout(15)
  c.send('Input.dispatchTouchEvent',{'type':'touchEnd','touchPoints':[]});p.wait_for_timeout(230)
 p.evaluate("methodPicker()")
 rect=p.locator('.sheet-drag-zone053').bounding_box();swipe(rect['x']+90,rect['y']+12,145)
 check('touch swipe grip dismisses sheet',p.evaluate('UI.overlay===null'))
 p.evaluate('methodPicker()');rect=p.locator('.sheet-head h2').bounding_box();swipe(rect['x']+15,rect['y']+12,140)
 check('touch swipe title dismisses sheet',p.evaluate('UI.overlay===null'))
 p.evaluate('methodPicker()');rect=p.locator('.sheet-drag-zone053').bounding_box();swipe(rect['x']+90,rect['y']+12,10,steps=14)
 check('small drag snaps sheet back',p.evaluate('UI.overlay!==null && $(".sheet").style.transform===""'))
 rect=p.locator('.sheet-drag-zone053').bounding_box();swipe(rect['x']+50,rect['y']+12,5,100)
 check('horizontal swipe does not dismiss',p.evaluate('UI.overlay!==null'))
 # Use a controlled generic sheet with genuinely scrollable body and plain paragraphs.
 p.evaluate("sheet('Kaydırma testi',Array.from({length:35},(_,i)=>'<p>Bir satır '+i+'</p>').join(''))")
 p.evaluate("$('.sheet-body053').scrollTop=140")
 rect=p.locator('.sheet-body053').bounding_box();swipe(rect['x']+60,rect['y']+70,70)
 check('scrolling body is not dismissed mid-list',p.evaluate('UI.overlay!==null'))
 p.evaluate("$('.sheet-body053').scrollTop=0")
 rect=p.locator('.sheet-body053').bounding_box();swipe(rect['x']+60,rect['y']+45,140)
 check('body downward swipe dismisses at top',p.evaluate('UI.overlay===null'))
 p.evaluate("sheet('Korunan giriş','<textarea style=\"height:200px;width:100%\">Çizimi ve yazıyı koru</textarea>')")
 rect=p.locator('textarea').bounding_box();swipe(rect['x']+45,rect['y']+40,110)
 check('textarea gesture not dismissed',p.evaluate('UI.overlay!==null'))
 p.evaluate('closeSheet()')
 check('sheet closure clears interaction lock',p.evaluate("!document.body.classList.contains('sheet-open053')"))
 for i in range(6):
  p.evaluate('weatherSheet()');rect=p.locator('.sheet-drag-zone053').bounding_box();swipe(rect['x']+60,rect['y']+12,135)
 check('repeated sheets still dismiss',p.evaluate('UI.overlay===null'))
 # Focus and optional native side effects that never resolve.
 p.evaluate("closeSheet();S=fresh();S.preferences.theme='garden';S.preferences.finishSound=false;S.preferences.soundWithFocus=false;S.world.petNames.bunny='A';applyTheme();route('focus');window.__saveReal=persist;void 0;")
 check('named companion restored',p.locator('.focus-companion053').inner_text().strip()=='A yanında.')
 p.evaluate("route('focus',{immersive:true})");check('fullscreen has no companion overlay',p.locator('.focus-companion053').count()==0)
 check('fullscreen navigation hidden',p.locator('#navigation').evaluate("n=>n.classList.contains('hidden')"))
 p.set_viewport_size({'width':844,'height':390});p.wait_for_timeout(100)
 check('landscape clock fits viewport',p.locator('#timer-digits').bounding_box()['x']>=0 and p.locator('#timer-digits').bounding_box()['width']<844)
 p.set_viewport_size({'width':390,'height':844})
 p.evaluate("route('focus');Native.call=(type,payload)=>['cancelTimer','scheduleTimer','audio','keepAwake','studyBell'].includes(type)?new Promise(()=>{}):__originalCall(type,payload);void 0;")
 p.evaluate("startFocus(25)");p.wait_for_timeout(70)
 check('start unblocks despite hung native notification',p.evaluate('!!S.timer && !focusBusy'))
 p.evaluate('toggleFocus()');check('pause unblocks despite hung optional operation',p.evaluate("S.timer.status==='paused' && !focusBusy"))
 remain=p.evaluate('S.timer.remainingMs');p.wait_for_timeout(220)
 check('pause keeps remaining time',p.evaluate('remainingMs(S.timer)')==remain)
 p.evaluate('toggleFocus()');check('resume unblocks',p.evaluate("S.timer.status==='running'&&!focusBusy"))
 p.evaluate("S.timer.remainingMs=(25*60-120)*1000;S.timer.remaining=S.timer.remainingMs/1000;S.timer.endAt=Date.now()+S.timer.remainingMs;S.timer.checkpointAt=Date.now();window.__savedId=S.timer.id;")
 p.evaluate('Promise.all([endFocus(false,false),endFocus(false,false)])')
 check('partial record grants 3 coins per minute',p.evaluate('wallet()')==6,p.evaluate('wallet()'))
 check('double finish records once',p.evaluate('S.focusHistory.filter(x=>x.id===__savedId).length===1'))
 check('finish releases focus lock',p.evaluate('!focusBusy && !rewardBusy && S.timer===null'))
 check('partial finish prepares rest',p.evaluate("S.practice.pending.phase==='break'"))
 p.evaluate("startFocus(5,{phase:'break'})");p.evaluate("S.timer.remainingMs=0;S.timer.remaining=0;S.timer.endAt=Date.now()-5;S.timer.checkpointAt=Date.now()-5;endFocus(true,false)")
 check('break grants no coins',p.evaluate('wallet()')==6)
 check('rest prepares study',p.evaluate("S.practice.pending.phase==='focus'"))
 # Completed 1-min timer -> normal coin animation and next sheet; bell not allowed to block.
 p.evaluate("S.preferences.finishSound=true;startFocus(1)")
 p.evaluate("S.timer.remainingMs=0;S.timer.remaining=0;S.timer.endAt=Date.now()-10;S.timer.checkpointAt=Date.now()-10;window.__finish=endFocus(true,true)")
 p.wait_for_timeout(2900)
 check('coin completion not blocked by hung bell',p.evaluate('!rewardBusy && !focusBusy && UI.overlay!==null'))
 check('completed session earns coins once',p.evaluate('wallet()')==9)
 p.evaluate("closeSheet();Native.call=__originalCall;window.__snapshot=JSON.stringify(S);Native.call=(t,p)=>t==='save'?Promise.reject(new Error('simulated disk error')):__originalCall(t,p);void 0;")
 p.evaluate("startFocus(10).catch(()=>{})")
 check('failed start rolls back timer',p.evaluate('S.timer===null && !focusBusy'))
 p.evaluate('Native.call=__originalCall;startFocus(10)')
 p.evaluate("S.timer.remainingMs=9*60*1000;S.timer.endAt=Date.now()+S.timer.remainingMs;window.__beforeWallet=wallet();Native.call=(t,p)=>t==='save'?Promise.reject(new Error('simulated disk error')):__originalCall(t,p);endFocus(false,false).catch(()=>{})")
 check('failed completion rolls back reward and timer',p.evaluate('!!S.timer && wallet()===__beforeWallet && !focusBusy && !rewardBusy'))
 p.evaluate("Native.call=__originalCall;endFocus(false,false);closeSheet()")
 p.wait_for_timeout(100)
 for i in range(14):p.evaluate("route('garden');route('focus');route('notes');")
 check('render cycles keep at most one background scene',p.evaluate('gardenInstances.size<=1'))
 p.evaluate("route('garden');for(const g of gardenInstances)g.pause();")
 check('paused scene has no scheduled timer',p.evaluate('[...gardenInstances].every(g=>g.frameTimer===null)'))
 p.evaluate("for(const g of gardenInstances)g.resume();")
 check('resumed scene runs once',p.evaluate('[...gardenInstances].every(g=>!!g.frameTimer)'))
 p.emulate_media(reduced_motion='reduce');p.evaluate('applyTheme();render()');p.wait_for_timeout(300)
 check('reduced motion stops continuous scene loop',p.evaluate('[...gardenInstances].every(g=>g.frameTimer===null)'))
 # Screenshots of functioning code with illustrative data, not shipped user progress.
 p.emulate_media(reduced_motion='no-preference');p.evaluate("S.preferences.motion=true;S.world.background='night';S.living.time='auto';S.living.weather='auto';S.world.plots[1]={id:'rose-test',kind:'rose',atSeconds:worldSeconds()};S.world.plots[2]={id:'lavender-test',kind:'lavender',atSeconds:worldSeconds()};applyTheme();route('garden');")
 p.wait_for_timeout(180);p.screenshot(path=str(OUT/'garden.png'))
 p.locator('.nursery053').scroll_into_view_if_needed();p.screenshot(path=str(OUT/'nursery.png'))
 p.evaluate('methodPicker()');p.wait_for_timeout(50);p.screenshot(path=str(OUT/'sheet.png'))
 p.evaluate("closeSheet();route('focus')");p.wait_for_timeout(70);p.screenshot(path=str(OUT/'focus.png'))
 check('no uncaught browser errors',not errors,errors)
 b.close()
(OUT/'browser-results.json').write_text(json.dumps(results,indent=2,ensure_ascii=False))
print('RESULT',sum(r['passed'] for r in results),'/',len(results))
