"""0.5.6 regression tests: real Chromium with memory storage, not physical iOS."""
from pathlib import Path
from playwright.sync_api import sync_playwright
import json, traceback
R=Path(__file__).resolve().parents[2];O=R/'tests/056';html=(R/'ONIZLEME.html').read_text();rows=[]
def check(name,truth,detail=''):
 rows.append(dict(name=name,passed=bool(truth),detail=detail));print('PASS' if truth else 'FAIL',name,detail,flush=True)
def setup(b,enabled=False):
 p=b.new_page(viewport={'width':390,'height':844},has_touch=True);p.set_default_timeout(6500)
 p.evaluate("Object.defineProperty(window,'localStorage',{value:{getItem:k=>window.__store?.[k]||null,setItem:(k,v)=>{(window.__store||={})[k]=v},removeItem:k=>delete window.__store[k]}})")
 if enabled:p.evaluate('window.LUMA_TEST_COINS_ALLOWED=true')
 p.set_content(html.replace('LUMA_TEST_COINS_SWITCH = false','LUMA_TEST_COINS_SWITCH = true') if enabled else html);p.wait_for_function('ready');return p
with sync_playwright() as w:
 b=w.chromium.launch(executable_path='/usr/bin/chromium',headless=True,args=['--no-sandbox','--enable-unsafe-swiftshader']);p=setup(b);errors=[];p.on('pageerror',lambda e:errors.append(str(e)))
 try:
  check('Version marker 056',p.evaluate("LIVING_BUILD==='LUMA-0.5.6-ATELIER'"))
  check('12 additive Anatolia entries, no starter gifts',p.evaluate("Object.keys(ANATOLIA056).length===12&&Object.keys(ANATOLIA056).every(k=>!owns('decor',k))"))
  check('Every 056 item has a distinct drawing',p.evaluate("new Set(Object.keys(ANATOLIA056).map(k=>JSON.stringify(DECOR_ART054[k]))).size===12&&Object.keys(ANATOLIA056).every(k=>DECOR_ART054[k].length>25)"))
  p.evaluate("()=>{UI.shopTab='decor';route('shop')}")
  check('Visible Japanese catalogue shortcut',p.locator('[data-action=collection-open056][data-tab=sakura055]').is_visible())
  p.locator('[data-action=collection-open056][data-tab=sakura055]').click()
  check('Japanese shortcut opens all 30 real models',p.locator('.sakura-card055').count()==30)
  p.locator('[data-action=shop-tab][data-tab=anatolia056]').click()
  check('Anatolia tab shows all 12',p.locator('.sakura-card055').count()==12)
  p.locator('[data-action=atelier-buy056][data-item=trTea056]').click()
  check('Insufficient funds guarded',p.evaluate("!owns('decor','trTea056')&&wallet()===0"))
  p.evaluate('S.living.baseCoins=25000')
  p.locator('[data-action=atelier-buy056][data-item=trTea056]').click();p.wait_for_function("owns('decor','trTea056')")
  check('Price debits exactly once',p.evaluate('wallet()===24780'))
  p.evaluate("buyItem('decor','trTea056')")
  check('Repeat purchase no debit',p.evaluate('wallet()===24780'))
  p.locator('[data-action=atelier-place056][data-item=trTea056]').click()
  p.locator('[data-action=atelier-destination056][data-room=true]').click();p.wait_for_function("UI.route==='garden'")
  check('Tea can be placed inside',p.evaluate("S.living.placement['decor:trTea056'].room===true"))
  p.evaluate("enhancedAction('atelier-destination056',{dataset:{item:'trTea056',room:'false'}},{})")
  check('Same ownership can move back outside',p.evaluate("S.living.placement['decor:trTea056'].room===false&&wallet()===24780"))
  p.evaluate("()=>{window.persist056=persist;window.old056=JSON.stringify(S.world);persist=async()=>{throw Error('disk failure')};}")
  result=p.evaluate("buyItem('decor','trKettle056').then(()=>false).catch(()=>true)")
  check('New model purchase rollback',result and p.evaluate('JSON.stringify(S.world)===old056'))
  p.evaluate('persist=window.persist056')
  p.evaluate("()=>{UI.gardenEdit=false;UI.gardenRoom=false;route('garden')}")
  check('No +/- buttons in garden toolbar',p.locator('.garden-tools [data-action=garden-zoom]').count()==0 and p.locator('.garden-tools button').count()==2)
  check('Memory section after nursery',p.evaluate("!!document.querySelector('.nursery053').nextElementSibling?.classList.contains('memories056')"))
  # Existing records get a normal selectable/movable entity, not just hardcoded drawing.
  p.evaluate("()=>{S.living.memorials=[{id:'oldmemory',name:'İlk sınavım'}];S=normalize(structuredClone(S));render();}")
  check('Legacy memory name and kind survive',p.evaluate("S.living.memorials[0].name==='İlk sınavım'&&S.living.memorials[0].kind==='tree'"))
  p.evaluate("enhancedAction('memory-move056',{dataset:{id:'oldmemory'}},{})")
  check('Legacy memory enters standard edit selection',p.evaluate("UI.selectedLiving==='memorial:oldmemory'&&UI.gardenEdit"))
  p.evaluate("()=>{window.oldPos056={...livingPlacements().find(x=>x.key==='memorial:oldmemory').pos};}")
  p.evaluate("enhancedAction('living-nudge',{dataset:{direction:'right'}},{})")
  check('Memory right arrow changes actual saved position',p.evaluate("S.living.placement['memorial:oldmemory'].x>oldPos056.x"))
  p.evaluate("()=>{window.beforeMemory056=structuredClone(S.living);S=normalize(structuredClone(S));}")
  check('Memory position remains after normalized reload',p.evaluate("S.living.placement['memorial:oldmemory'].x===beforeMemory056.placement['memorial:oldmemory'].x"))
  p.evaluate("enhancedAction('memory-hide056',{dataset:{id:'oldmemory'}},{})")
  check('Hiding memory preserves metadata and removes scene hit',p.evaluate("S.living.memorials.length===1&&S.living.memorials[0].hidden&&!livingPlacements().some(x=>x.key==='memorial:oldmemory')"))
  p.evaluate("enhancedAction('memory-move056',{dataset:{id:'oldmemory'}},{})")
  check('Hidden memory can be restored',p.evaluate("!S.living.memorials[0].hidden"))
  p.evaluate("()=>{UI.gardenEdit=false;route('garden');memorialForm056();}")
  p.locator('#memory056-form input[name=name]').fill('Bitmiş proje')
  p.locator('#memory056-form button[type=submit]').click();p.wait_for_timeout(200)
  check('No fake work for free new memorial',p.evaluate('S.living.memorials.length===1'))
  p.evaluate("()=>{S.focusHistory.push({id:'study-test',completedMinutes:25,phase:'work',startedAt:new Date().toISOString(),endedAt:new Date().toISOString()});}")
  p.locator('#memory056-form button[type=submit]').click();p.wait_for_function('S.living.memorials.length===2')
  check('New flower saved with no coin charge',p.evaluate("S.living.memorials[1].kind==='flower'&&S.living.memorials[1].name==='Bitmiş proje'"))
  check('Memory objects have canvas hit tests',p.evaluate("[...gardenInstances].some(g=>g.hits.some(h=>h.kind==='memorial'&&h.key===UI.selectedLiving))"))
  p.evaluate("()=>{UI.gardenEdit=false;route('garden');window.g056=[...gardenInstances].find(x=>!x.passive);}");p.wait_for_timeout(150)
  p.evaluate('g056.setZoom(2)')
  box=p.locator('.living-host canvas').first.bounding_box()
  x=box['x']+box['width']*.48;y=box['y']+box['height']*.40
  p.mouse.move(x,y);p.mouse.down();p.mouse.move(x+65,y+40,steps=6);p.mouse.up()
  check('Single finger/mouse pan works when zoomed',p.evaluate('g056.pan.x>30&&g056.pan.y>20'))
  for dx,dy,label in [(1e5,1e5,'bottom right'),(-1e5,-1e5,'top left'),(1e5,-1e5,'top right'),(-1e5,1e5,'bottom left')]:
   p.evaluate('([x,y])=>{g056.pan={x,y};g056.paint(performance.now());}',[dx,dy])
   check('Camera cannot expose outside '+label,p.evaluate('g056.fit.ox<=.01&&g056.fit.oy<=.01&&g056.fit.ox+g056.world.width*g056.fit.scale>=g056.width-.01&&g056.fit.oy+g056.world.height*g056.fit.scale>=g056.height-.01'))
  p.evaluate('g056.setZoom(1)')
  p.mouse.move(x,y);p.mouse.down();p.mouse.move(x+65,y+40,steps=6);p.mouse.up()
  check('Fit mode does not drift',p.evaluate('g056.pan.x===0&&g056.pan.y===0'))
  # Multi-touch through the browser input layer, not direct setZoom.
  cdp=p.context.new_cdp_session(p)
  def touch(typ,pts):cdp.send('Input.dispatchTouchEvent',{'type':typ,'touchPoints':[{'x':a,'y':b,'id':i+1}for i,(a,b)in enumerate(pts)]})
  touch('touchStart',[(x-25,y),(x+25,y)])
  for s in [30,38,48,59]:touch('touchMove',[(x-s,y),(x+s,y)])
  touch('touchEnd',[]);p.wait_for_timeout(100)
  check('Actual Chromium multi-touch zooms',p.evaluate('g056.zoom>1.3'),str(p.evaluate('g056.zoom')))
  check('Pinch releases transient gesture state',p.evaluate('!g056.touchBlock056&&!g056.touchPinch056&&g056.pointers.size===0'))
  p.evaluate('g056.setZoom(1)')
  p.evaluate('weatherSheet()');p.wait_for_timeout(100)
  grip=p.locator('.sheet-drag-zone053').bounding_box();gx=grip['x']+grip['width']/2;gy=grip['y']+grip['height']/2
  touch('touchStart',[(gx,gy)])
  for off in [15,40,70,110]:touch('touchMove',[(gx,gy+off)])
  touch('touchEnd',[]);p.wait_for_timeout(300)
  check('Sheet touch-down dismissal retained',p.locator('.sheet').count()==0)
  for theme in ['opal056','emerald056','amber056','cosmos056','nocturne','garden','opal056']:
   p.evaluate('(k)=>{S.preferences.theme=k;applyTheme();route("focus")}',theme);p.wait_for_timeout(140)
   if theme not in ['garden']:
    info=p.evaluate('({ctor:currentLava?.inner?.constructor.name,gl:!!currentLava?.inner?.gl,err:currentLava?.inner?.gl?.getError()})')
    check('Theme renderer '+theme,info['ctor']=='Lava' and (info['gl'] and info['err']==0 or p.evaluate('!!currentLava.inner.fallbackRenderer?.ctx')),str(info))
   else:check('Garden background still selected',p.evaluate('[...gardenInstances].some(g=>g.passive&&g.world.width>0)'))
  p.evaluate("()=>{S.preferences.motion=false;applyTheme();render();}")
  check('Reduced-motion lava stops its frame loop',p.evaluate('(currentLava.inner.still&&!currentLava.inner.frameId)||(currentLava.inner.fallbackRenderer?.still&&!currentLava.inner.fallbackRenderer?.id)'))
  p.evaluate("()=>{S.preferences.motion=true;applyTheme();mixerSheet();}")
  check('All 4 piano choices visible',p.locator('[data-action=piano-track056]').count()==4)
  check('Ocean and fire are not gated as missing recordings',p.evaluate("!missingRecording054('ocean')&&!missingRecording054('fire')"))
  check('Generated audio provenance shown honestly','gerçek ortam kaydı değildir' in p.locator('.sheet').inner_text())
  p.locator('[data-action=piano-track056][data-track=pianoDawn]').click()
  check('Select piano keeps a single piano track volume',p.evaluate("S.preferences.volumes.pianoDawn===25&&Object.keys(PIANO_TRACKS056).filter(k=>S.preferences.volumes[k]>0).length===1"))
  p.locator('[data-action=piano-track056][data-track=pianoSakura]').click()
  check('Switch piano zeros previous channel',p.evaluate('S.preferences.volumes.pianoDawn===0&&S.preferences.volumes.pianoSakura===25'))
  # Decode every local MP3 in the real browser without routing the OS native player.
  decoded=p.evaluate("async()=>{const c=new AudioContext(),rows=[];for(const key of ['ocean','fire','pianoMoon','pianoDawn','pianoSakura']){const bytes=Uint8Array.from(atob(LUMA_AUDIO_DATA[key]),x=>x.charCodeAt(0));const q=await c.decodeAudioData(bytes.buffer);rows.push({key,d:q.duration,ch:q.numberOfChannels});}await c.close();return rows;}")
  for d in decoded:check('Browser decodes packaged '+d['key'],d['d']>80 and d['ch']==2,str(d))
  p.evaluate("()=>{window.audioWanted056={playing:true,volumes:{ocean:40,fire:0,pianoMoon:0},customAudio:null};}")
  p.evaluate('Promise.all([updateWebAudio(audioWanted056),updateWebAudio(audioWanted056)])')
  check('Concurrent audio calls share one decoded node',p.evaluate("Object.keys(webAudio.nodes).filter(k=>k==='ocean').length===1&&Object.keys(webAudio.loading056).length===0"))
  p.evaluate("updateWebAudio({playing:false,volumes:{}})")
  check('Audio stop releases active buffers',p.evaluate('Object.keys(webAudio.nodes).length===0'))
  p.evaluate('closeSheet()')
  for width,height in [(320,700),(375,812),(390,844),(430,932),(844,390)]:
   p.set_viewport_size({'width':width,'height':height});p.evaluate("()=>{UI.gardenFull=false;UI.gardenRoom=false;route('garden');}");p.wait_for_timeout(90)
   check('Garden bounds '+str(width)+'x'+str(height),p.evaluate('document.documentElement.scrollWidth<=innerWidth+1&&[...gardenInstances].filter(g=>!g.passive).every(g=>g.fit.ox<=1&&g.fit.oy<=1)'))
   p.evaluate("()=>{UI.shopTab='anatolia056';route('shop')}")
   check('Catalogue wraps within viewport '+str(width),p.evaluate('document.documentElement.scrollWidth<=innerWidth+1'))
  check('No unhandled browser exceptions',not errors,';'.join(errors))
  p.close()
  d=setup(b,enabled=True);d.evaluate("()=>{S.living.baseCoins=43;}");d.evaluate("buyItem('decor','trKettle056')")
  check('Test purchase spends only test coins',d.evaluate('testCoinsBreakdown().test===99999460&&testCoinsBreakdown().real===43'))
  d.evaluate("()=>{S=normalize(structuredClone(S));S=normalize(structuredClone(S));}")
  check('056 reload does not grant another 100m',d.evaluate('testCoinsBreakdown().test===99999460'))
  d.close()
 except Exception as e:traceback.print_exc();check('Unhandled test exception',False,str(e))
 finally:
  b.close();(O/'atelier-results.json').write_text(json.dumps(rows,ensure_ascii=False,indent=2));print('RESULT',sum(q['passed']for q in rows),'/',len(rows))
  if any(not q['passed']for q in rows):raise SystemExit(1)
